package org.jukeboxmc.server.world

import org.cloudburstmc.protocol.bedrock.data.LevelEvent
import org.cloudburstmc.protocol.bedrock.data.LevelEventType
import org.cloudburstmc.protocol.bedrock.data.ParticleType
import org.jukeboxmc.api.world.Particle

class ParticleRegistry {

    companion object {
        private val particleType: MutableMap<Particle, LevelEventType> = mutableMapOf()

        init {

            register(Particle.BUBBLE, ParticleType.BUBBLE)
            register(Particle.BUBBLE_MANUAL, ParticleType.BUBBLE_MANUAL)
            register(Particle.CRIT, ParticleType.CRIT)
            register(Particle.BLOCK_FORCE_FIELD, ParticleType.BLOCK_FORCE_FIELD)
            register(Particle.SMOKE, ParticleType.SMOKE)
            register(Particle.EXPLODE, ParticleType.EXPLODE)
            register(Particle.EVAPORATION, ParticleType.EVAPORATION)
            register(Particle.FLAME, ParticleType.FLAME)
            register(Particle.LAVA, ParticleType.LAVA)
            register(Particle.LARGE_SMOKE, ParticleType.LARGE_SMOKE)
            register(Particle.RED_DUST, ParticleType.RED_DUST)
            register(Particle.RISING_BORDER_DUST, ParticleType.RISING_BORDER_DUST)
            register(Particle.ICON_CRACK, ParticleType.ICON_CRACK)
            register(Particle.SNOWBALL_POOF, ParticleType.SNOWBALL_POOF)
            register(Particle.LARGE_EXPLODE, ParticleType.LARGE_EXPLODE)
            register(Particle.HUGE_EXPLOSION, ParticleType.HUGE_EXPLOSION)
            register(Particle.MOB_FLAME, ParticleType.MOB_FLAME)
            register(Particle.HEART, ParticleType.HEART)
            register(Particle.TERRAIN, ParticleType.TERRAIN)
            register(Particle.TOWN_AURA, ParticleType.TOWN_AURA)
            register(Particle.PORTAL, ParticleType.PORTAL)
            register(Particle.MOB_PORTAL, ParticleType.MOB_PORTAL)
            register(Particle.WATER_SPLASH, ParticleType.WATER_SPLASH)
            register(Particle.WATER_SPLASH_MANUAL, ParticleType.WATER_SPLASH_MANUAL)
            register(Particle.WATER_WAKE, ParticleType.WATER_WAKE)
            register(Particle.DRIP_WATER, ParticleType.DRIP_WATER)
            register(Particle.DRIP_LAVA, ParticleType.DRIP_LAVA)
            register(Particle.DRIP_HONEY, ParticleType.DRIP_HONEY)
            register(Particle.STALACTITE_DRIP_WATER, ParticleType.STALACTITE_DRIP_WATER)
            register(Particle.STALACTITE_DRIP_LAVA, ParticleType.STALACTITE_DRIP_LAVA)
            register(Particle.FALLING_DUST, ParticleType.FALLING_DUST)
            register(Particle.MOB_SPELL, ParticleType.MOB_SPELL)
            register(Particle.MOB_SPELL_AMBIENT, ParticleType.MOB_SPELL_AMBIENT)
            register(Particle.MOB_SPELL_INSTANTANEOUS, ParticleType.MOB_SPELL_INSTANTANEOUS)
            register(Particle.INK, ParticleType.INK)
            register(Particle.SLIME, ParticleType.SLIME)
            register(Particle.RAIN_SPLASH, ParticleType.RAIN_SPLASH)
            register(Particle.VILLAGER_ANGRY, ParticleType.VILLAGER_ANGRY)
            register(Particle.VILLAGER_HAPPY, ParticleType.VILLAGER_HAPPY)
            register(Particle.ENCHANTING_TABLE, ParticleType.ENCHANTING_TABLE)
            register(Particle.TRACKER_EMITTER, ParticleType.TRACKER_EMITTER)
            register(Particle.NOTE, ParticleType.NOTE)
            register(Particle.WITCH_SPELL, ParticleType.WITCH_SPELL)
            register(Particle.CARROT_BOOST, ParticleType.CARROT_BOOST)
            register(Particle.MOB_APPEARANCE, ParticleType.MOB_APPEARANCE)
            register(Particle.END_ROD, ParticleType.END_ROD)
            register(Particle.DRAGON_BREATH, ParticleType.DRAGON_BREATH)
            register(Particle.SPIT, ParticleType.SPIT)
            register(Particle.TOTEM, ParticleType.TOTEM)
            register(Particle.FOOD, ParticleType.FOOD)
            register(Particle.FIREWORKS_STARTER, ParticleType.FIREWORKS_STARTER)
            register(Particle.FIREWORKS, ParticleType.FIREWORKS)
            register(Particle.FIREWORKS_OVERLAY, ParticleType.FIREWORKS_OVERLAY)
            register(Particle.BALLOON_GAS, ParticleType.BALLOON_GAS)
            register(Particle.COLORED_FLAME, ParticleType.COLORED_FLAME)
            register(Particle.SPARKLER, ParticleType.SPARKLER)
            register(Particle.CONDUIT, ParticleType.CONDUIT)
            register(Particle.BUBBLE_COLUMN_UP, ParticleType.BUBBLE_COLUMN_UP)
            register(Particle.BUBBLE_COLUMN_DOWN, ParticleType.BUBBLE_COLUMN_DOWN)
            register(Particle.SNEEZE, ParticleType.SNEEZE)
            register(Particle.SHULKER_BULLET, ParticleType.SHULKER_BULLET)
            register(Particle.BLEACH, ParticleType.BLEACH)
            register(Particle.DRAGON_DESTROY_BLOCK, ParticleType.DRAGON_DESTROY_BLOCK)
            register(Particle.MYCELIUM_DUST, ParticleType.MYCELIUM_DUST)
            register(Particle.FALLING_BORDER_DUST, ParticleType.FALLING_BORDER_DUST)
            register(Particle.CAMPFIRE_SMOKE, ParticleType.CAMPFIRE_SMOKE)
            register(Particle.CAMPFIRE_SMOKE_TALL, ParticleType.CAMPFIRE_SMOKE_TALL)
            register(Particle.DRAGON_BREATH_FIRE, ParticleType.DRAGON_BREATH_FIRE)
            register(Particle.DRAGON_BREATH_TRAIL, ParticleType.DRAGON_BREATH_TRAIL)
            register(Particle.BLUE_FLAME, ParticleType.BLUE_FLAME)
            register(Particle.SOUL, ParticleType.SOUL)
            register(Particle.OBSIDIAN_TEAR, ParticleType.OBSIDIAN_TEAR)
            register(Particle.PORTAL_REVERSE, ParticleType.PORTAL_REVERSE)
            register(Particle.SNOWFLAKE, ParticleType.SNOWFLAKE)
            register(Particle.VIBRATION_SIGNAL, ParticleType.VIBRATION_SIGNAL)
            register(Particle.SCULK_SENSOR_REDSTONE, ParticleType.SCULK_SENSOR_REDSTONE)
            register(Particle.SPORE_BLOSSOM_SHOWER, ParticleType.SPORE_BLOSSOM_SHOWER)
            register(Particle.SPORE_BLOSSOM_AMBIENT, ParticleType.SPORE_BLOSSOM_AMBIENT)
            register(Particle.WAX, ParticleType.WAX)
            register(Particle.ELECTRIC_SPARK, ParticleType.ELECTRIC_SPARK)
            register(Particle.CANDLE_FLAME, ParticleType.CANDLE_FLAME)
            register(Particle.SHRIEK, ParticleType.SHRIEK)
            register(Particle.SCULK_SOUL, ParticleType.SCULK_SOUL)
            register(Particle.SONIC_EXPLOSION, ParticleType.SONIC_EXPLOSION)
            register(Particle.BRUSH_DUST, ParticleType.BRUSH_DUST)
            register(Particle.CHERRY_LEAVES, ParticleType.CHERRY_LEAVES)
            register(Particle.DUST_PLUME, ParticleType.DUST_PLUME)
            register(Particle.WHITE_SMOKE, ParticleType.WHITE_SMOKE)

            register(Particle.PARTICLE_SHOOT, LevelEvent.PARTICLE_SHOOT)
            register(Particle.PARTICLE_DESTROY_BLOCK, LevelEvent.PARTICLE_DESTROY_BLOCK)
            register(Particle.PARTICLE_POTION_SPLASH, LevelEvent.PARTICLE_POTION_SPLASH)
            register(Particle.PARTICLE_EYE_OF_ENDER_DEATH, LevelEvent.PARTICLE_EYE_OF_ENDER_DEATH)
            register(Particle.PARTICLE_MOB_BLOCK_SPAWN, LevelEvent.PARTICLE_MOB_BLOCK_SPAWN)
            register(Particle.PARTICLE_CROP_GROWTH, LevelEvent.PARTICLE_CROP_GROWTH)
            register(Particle.PARTICLE_SOUND_GUARDIAN_GHOST, LevelEvent.PARTICLE_SOUND_GUARDIAN_GHOST)
            register(Particle.PARTICLE_DEATH_SMOKE, LevelEvent.PARTICLE_DEATH_SMOKE)
            register(Particle.PARTICLE_DENY_BLOCK, LevelEvent.PARTICLE_DENY_BLOCK)
            register(Particle.PARTICLE_GENERIC_SPAWN, LevelEvent.PARTICLE_GENERIC_SPAWN)
            register(Particle.PARTICLE_DRAGON_EGG, LevelEvent.PARTICLE_DRAGON_EGG)
            register(Particle.PARTICLE_CROP_EATEN, LevelEvent.PARTICLE_CROP_EATEN)
            register(Particle.PARTICLE_CRIT, LevelEvent.PARTICLE_CRIT)
            register(Particle.PARTICLE_TELEPORT, LevelEvent.PARTICLE_TELEPORT)
            register(Particle.PARTICLE_CRACK_BLOCK, LevelEvent.PARTICLE_CRACK_BLOCK)
            register(Particle.PARTICLE_BUBBLES, LevelEvent.PARTICLE_BUBBLES)
            register(Particle.PARTICLE_EVAPORATE, LevelEvent.PARTICLE_EVAPORATE)
            register(Particle.PARTICLE_DESTROY_ARMOR_STAND, LevelEvent.PARTICLE_DESTROY_ARMOR_STAND)
            register(Particle.PARTICLE_BREAKING_EGG, LevelEvent.PARTICLE_BREAKING_EGG)
            register(Particle.PARTICLE_DESTROY_EGG, LevelEvent.PARTICLE_DESTROY_EGG)
            register(Particle.PARTICLE_EVAPORATE_WATER, LevelEvent.PARTICLE_EVAPORATE_WATER)
            register(Particle.PARTICLE_DESTROY_BLOCK_NO_SOUND, LevelEvent.PARTICLE_DESTROY_BLOCK_NO_SOUND)
            register(Particle.PARTICLE_KNOCKBACK_ROAR, LevelEvent.PARTICLE_KNOCKBACK_ROAR)
            register(Particle.PARTICLE_TELEPORT_TRAIL, LevelEvent.PARTICLE_TELEPORT_TRAIL)
            register(Particle.PARTICLE_POINT_CLOUD, LevelEvent.PARTICLE_POINT_CLOUD)
            register(Particle.PARTICLE_EXPLOSION, LevelEvent.PARTICLE_EXPLOSION)
            register(Particle.PARTICLE_BLOCK_EXPLOSION, LevelEvent.PARTICLE_BLOCK_EXPLOSION)
            register(Particle.PARTICLE_VIBRATION_SIGNAL, LevelEvent.PARTICLE_VIBRATION_SIGNAL)
            register(Particle.PARTICLE_DRIPSTONE_DRIP, LevelEvent.PARTICLE_DRIPSTONE_DRIP)
            register(Particle.PARTICLE_FIZZ_EFFECT, LevelEvent.PARTICLE_FIZZ_EFFECT)
            register(Particle.PARTICLE_WAX_ON, LevelEvent.PARTICLE_WAX_ON)
            register(Particle.PARTICLE_WAX_OFF, LevelEvent.PARTICLE_WAX_OFF)
            register(Particle.PARTICLE_SCRAPE, LevelEvent.PARTICLE_SCRAPE)
            register(Particle.PARTICLE_ELECTRIC_SPARK, LevelEvent.PARTICLE_ELECTRIC_SPARK)
            register(Particle.PARTICLE_TURTLE_EGG, LevelEvent.PARTICLE_TURTLE_EGG)
            register(Particle.PARTICLE_SCULK_SHRIEK, LevelEvent.PARTICLE_SCULK_SHRIEK)
            register(Particle.PARTICLE_BREAK_BLOCK_DOWN, LevelEvent.PARTICLE_BREAK_BLOCK_DOWN)
            register(Particle.PARTICLE_BREAK_BLOCK_UP, LevelEvent.PARTICLE_BREAK_BLOCK_UP)
            register(Particle.PARTICLE_BREAK_BLOCK_NORTH, LevelEvent.PARTICLE_BREAK_BLOCK_NORTH)
            register(Particle.PARTICLE_BREAK_BLOCK_SOUTH, LevelEvent.PARTICLE_BREAK_BLOCK_SOUTH)
            register(Particle.PARTICLE_BREAK_BLOCK_WEST, LevelEvent.PARTICLE_BREAK_BLOCK_WEST)
            register(Particle.PARTICLE_BREAK_BLOCK_EAST, LevelEvent.PARTICLE_BREAK_BLOCK_EAST)
            register(Particle.PARTICLE_SHOOT_WHITE_SMOKE, LevelEvent.PARTICLE_SHOOT_WHITE_SMOKE)
        }

        private fun register(particle: Particle, levelEvent: LevelEventType) {
            this.particleType[particle] = levelEvent
        }

        fun getLevelEvent(particle: Particle): LevelEventType {
            return particleType[particle]!!
        }
    }

}