package org.jukeboxmc.item;

import lombok.SneakyThrows;
import org.jukeboxmc.block.*;
import org.jukeboxmc.block.type.*;

import java.util.HashMap;
import java.util.Map;

/**
 * @author LucGamesYT
 * @version 1.0
 */
public enum ItemType {

    AIR( BlockType.AIR.toItem() ),

    STONE( BlockType.STONE.<BlockStone>getBlock().setStoneType( StoneType.STONE ).toItem() ),
    GRANITE( BlockType.STONE.<BlockStone>getBlock().setStoneType( StoneType.GRANITE ).toItem() ),
    GRANITE_SMOOTH( BlockType.STONE.<BlockStone>getBlock().setStoneType( StoneType.GRANITE_SMOOTH ).toItem() ),
    DIORITE( BlockType.STONE.<BlockStone>getBlock().setStoneType( StoneType.DIORITE ).toItem() ),
    DIORITE_SMOOTH( BlockType.STONE.<BlockStone>getBlock().setStoneType( StoneType.DIORITE_SMOOTH ).toItem() ),
    ANDESITE( BlockType.STONE.<BlockStone>getBlock().setStoneType( StoneType.ANDESITE ).toItem() ),
    ANDESITE_SMOOTH( BlockType.STONE.<BlockStone>getBlock().setStoneType( StoneType.ANDESITE_SMOOTH ).toItem() ),

    GRASS( new ItemGrass() ),
    DIRT( new ItemDirt() ),
    COBBLESTONE( new ItemCobblestone() ),

    OAK_PLANKS( BlockType.PLANKS.<BlockPlanks>getBlock().setWoodType( WoodType.OAK ).toItem() ),
    SPRUCE_PLANKS( BlockType.PLANKS.<BlockPlanks>getBlock().setWoodType( WoodType.SPRUCE ).toItem() ),
    BIRCH_PLANKS( BlockType.PLANKS.<BlockPlanks>getBlock().setWoodType( WoodType.BIRCH ).toItem() ),
    JUNGLE_PLANKS( BlockType.PLANKS.<BlockPlanks>getBlock().setWoodType( WoodType.JUNGLE ).toItem() ),
    ACACIA_PLANKS( BlockType.PLANKS.<BlockPlanks>getBlock().setWoodType( WoodType.ACACIA ).toItem() ),
    DARK_OAK_PLANKS( BlockType.PLANKS.<BlockPlanks>getBlock().setWoodType( WoodType.DARK_OAK ).toItem() ),

    OAK_SAPLING( BlockType.SAPLING.<BlockSapling>getBlock().setSaplingType( SaplingType.OAK ).toItem() ),
    SPRUCE_SAPLING( BlockType.SAPLING.<BlockSapling>getBlock().setSaplingType( SaplingType.SPRUCE ).toItem() ),
    BIRCH_SAPLING( BlockType.SAPLING.<BlockSapling>getBlock().setSaplingType( SaplingType.BIRCH ).toItem() ),
    JUNGLE_SAPLING( BlockType.SAPLING.<BlockSapling>getBlock().setSaplingType( SaplingType.JUNGLE ).toItem() ),
    ACACIA_SAPLING( BlockType.SAPLING.<BlockSapling>getBlock().setSaplingType( SaplingType.ACACIA ).toItem() ),
    DARK_OAK_SAPLING( BlockType.SAPLING.<BlockSapling>getBlock().setSaplingType( SaplingType.DARK_OAK ).toItem() ),

    BEDROCK( new ItemBedrock() ),
    FLOWING_WATER( new ItemFlowingWater() ),
    WATER( new ItemWater() ),
    FLOWING_LAVA( new ItemFlowingLava() ),
    LAVA( new ItemLava() ),

    SAND( BlockType.SAND.<BlockSand>getBlock().setSandType( SandType.NORMAL ).toItem() ),
    RED_SAND( BlockType.SAND.<BlockSand>getBlock().setSandType( SandType.RED ).toItem() ),

    GRAVEL( new ItemGravel() ),
    GOLD_ORE( new ItemGoldOre() ),
    IRON_ORE( new ItemIronOre() ),
    COAL_ORE( new ItemCoalOre() ),

    OAK_LOG( BlockType.OAK_LOG.toItem() ),
    SPRUCE_LOG( BlockType.SPRUCE_LOG.toItem() ),
    BIRCH_LOG( BlockType.BIRCH_LOG.toItem() ),
    JUNGLE_LOG( BlockType.JUNGLE_LOG.toItem() ),

    OAK_LEAVES( BlockType.OAK_LEAVES.toItem() ),
    SPRUCE_LEAVES( BlockType.SPRUCE_LEAVES.toItem() ),
    BIRCH_LEAVES( BlockType.BIRCH_LEAVES.toItem() ),
    JUNGLE_LEAVES( BlockType.JUNGLE_LEAVES.toItem() ),

    DRY_SPONGE( BlockType.SPONGE.<BlockSponge>getBlock().setSpongeType( SpongeType.DRY ).toItem() ),
    WET_SPONGE( BlockType.SPONGE.<BlockSponge>getBlock().setSpongeType( SpongeType.WET ).toItem() ),

    GLASS( new ItemGlass() ),
    LAPIS_ORE( new ItemLapisOre() ),
    LAPIS_BLOCK( new ItemLapisBlock() ),
    DISPENSER( new ItemDispenser() ),

    SANDSTONE( BlockType.SANDSTONE.<BlockSandstone>getBlock().setSandStoneType( SandStoneType.DEFAULT ).toItem() ),
    CHISELED_SANDSTONE( BlockType.SANDSTONE.<BlockSandstone>getBlock().setSandStoneType( SandStoneType.HEIROGLYPHS ).toItem() ),
    CUT_SANDSTONE( BlockType.SANDSTONE.<BlockSandstone>getBlock().setSandStoneType( SandStoneType.CUT ).toItem() ),
    SMOOTH_SANDSTONE( BlockType.SANDSTONE.<BlockSandstone>getBlock().setSandStoneType( SandStoneType.SMOOTH ).toItem() ),

    NOTEBLOCK( new ItemNoteblock() ),
    BED_BLOCK( new ItemBedBlock() ),
    GOLDEN_RAIL( new ItemGoldenRail() ),
    DETECTOR_RAIL( new ItemDetectorRail() ),
    STICKY_PISTON( new ItemStickyPiston() ),
    WEB( new ItemWeb() ),

    TALLGRASS( BlockType.TALLGRASS.<BlockTallGrass>getBlock().setGrassType( GrassType.TALL ).toItem() ),
    FERN( BlockType.TALLGRASS.<BlockTallGrass>getBlock().setGrassType( GrassType.FERN ).toItem() ),
    DEFAULT( BlockType.TALLGRASS.<BlockTallGrass>getBlock().setGrassType( GrassType.DEFAULT ).toItem() ),
    SNOW1( BlockType.TALLGRASS.<BlockTallGrass>getBlock().setGrassType( GrassType.SNOW ).toItem() ),

    DEADBUSH( new ItemDeadbush() ),
    PISTON( new ItemPiston() ),
    PISTONARMCOLLISION( new ItemPistonarmcollision() ),

    WHITE_WOOL( BlockType.WOOL.<BlockWool>getBlock().setColor( BlockColor.WHITE ).toItem() ),
    ORANGE_WOOL( BlockType.WOOL.<BlockWool>getBlock().setColor( BlockColor.ORANGE ).toItem() ),
    MAGENTA_WOOL( BlockType.WOOL.<BlockWool>getBlock().setColor( BlockColor.MAGENTA ).toItem() ),
    LIGHT_BLUE_WOOL( BlockType.WOOL.<BlockWool>getBlock().setColor( BlockColor.LIGHT_BLUE ).toItem() ),
    YELLOW_WOOL( BlockType.WOOL.<BlockWool>getBlock().setColor( BlockColor.YELLOW ).toItem() ),
    LIME_WOOL( BlockType.WOOL.<BlockWool>getBlock().setColor( BlockColor.LIME ).toItem() ),
    PINK_WOOL( BlockType.WOOL.<BlockWool>getBlock().setColor( BlockColor.PINK ).toItem() ),
    GRAY_WOOL( BlockType.WOOL.<BlockWool>getBlock().setColor( BlockColor.GRAY ).toItem() ),
    SILVER_WOOL( BlockType.WOOL.<BlockWool>getBlock().setColor( BlockColor.SILVER ).toItem() ),
    CYAN_WOOL( BlockType.WOOL.<BlockWool>getBlock().setColor( BlockColor.CYAN ).toItem() ),
    PURPLE_WOOL( BlockType.WOOL.<BlockWool>getBlock().setColor( BlockColor.PURPLE ).toItem() ),
    BLUE_WOOL( BlockType.WOOL.<BlockWool>getBlock().setColor( BlockColor.BLUE ).toItem() ),
    BROWN_WOOL( BlockType.WOOL.<BlockWool>getBlock().setColor( BlockColor.BROWN ).toItem() ),
    RED_WOOL( BlockType.WOOL.<BlockWool>getBlock().setColor( BlockColor.RED ).toItem() ),
    BLACK_WOOL( BlockType.WOOL.<BlockWool>getBlock().setColor( BlockColor.BLACK ).toItem() ),
    GREEN_WOOL( BlockType.WOOL.<BlockWool>getBlock().setColor( BlockColor.GREEN ).toItem() ),

    ELEMENT_0( new ItemElement0() ),
    YELLOW_FLOWER( new ItemYellowFlower() ),

    POPPY( BlockType.RED_FLOWER.<BlockRedFlower>getBlock().setFlowerType( FlowerType.POPPY ).toItem() ),
    ORCHID( BlockType.RED_FLOWER.<BlockRedFlower>getBlock().setFlowerType( FlowerType.ORCHID ).toItem() ),
    ALLIUM( BlockType.RED_FLOWER.<BlockRedFlower>getBlock().setFlowerType( FlowerType.ALLIUM ).toItem() ),
    AZURE_BLUET( BlockType.RED_FLOWER.<BlockRedFlower>getBlock().setFlowerType( FlowerType.HOUSTONIA ).toItem() ),
    RED_TULIP( BlockType.RED_FLOWER.<BlockRedFlower>getBlock().setFlowerType( FlowerType.TULIP_RED ).toItem() ),
    ORANGE_TULIP( BlockType.RED_FLOWER.<BlockRedFlower>getBlock().setFlowerType( FlowerType.TULIP_ORANGE ).toItem() ),
    WHITE_TULIP( BlockType.RED_FLOWER.<BlockRedFlower>getBlock().setFlowerType( FlowerType.TULIP_WHITE ).toItem() ),
    PINK_TULIP( BlockType.RED_FLOWER.<BlockRedFlower>getBlock().setFlowerType( FlowerType.TULIP_PINK ).toItem() ),
    OXEYE( BlockType.RED_FLOWER.<BlockRedFlower>getBlock().setFlowerType( FlowerType.OXEYE ).toItem() ),
    CORNFLOWER( BlockType.RED_FLOWER.<BlockRedFlower>getBlock().setFlowerType( FlowerType.CORNFLOWER ).toItem() ),
    LILY_OF_THE_VALLEY( BlockType.RED_FLOWER.<BlockRedFlower>getBlock().setFlowerType( FlowerType.LILY_OF_THE_VALLEY ).toItem() ),

    BROWN_MUSHROOM( new ItemBrownMushroom() ),
    RED_MUSHROOM( new ItemRedMushroom() ),
    GOLD_BLOCK( new ItemGoldBlock() ),
    IRON_BLOCK( new ItemIronBlock() ),
    DOUBLE_STONE_SLAB( new ItemRealDoubleStoneSlab() ),
    BRICK_BLOCK( new ItemBrickBlock() ),
    TNT( new ItemTnt() ),
    BOOKSHELF( new ItemBookshelf() ),
    MOSSY_COBBLESTONE( new ItemMossyCobblestone() ),
    OBSIDIAN( new ItemObsidian() ),
    TORCH( new ItemTorch() ),
    FIRE( new ItemFire() ),
    MOB_SPAWNER( new ItemMobSpawner() ),
    OAK_STAIRS( new ItemOakStairs() ),
    CHEST( new ItemChest() ),
    REDSTONE_WIRE( new ItemRedstoneWire() ),
    DIAMOND_ORE( new ItemDiamondOre() ),
    DIAMOND_BLOCK( new ItemDiamondBlock() ),
    CRAFTING_BLOCK( new ItemCraftingTable() ),
    WHEAT_BLOCK( new ItemWheatBlock() ),
    FARMLAND( new ItemFarmland() ),
    FURNACE( new ItemFurnace() ),
    STANDING_SIGN( new ItemStandingSign() ),
    OAK_DOOR( new ItemOakDoor() ),
    LADDER( new ItemLadder() ),
    RAIL( new ItemRail() ),
    STONE_STAIRS( new ItemCobblestoneStairs() ),
    WALL_SIGN( new ItemWallSign() ),
    LEVER( new ItemLever() ),
    STONE_PRESSURE_PLATE( new ItemStonePressurePlate() ),
    IRON_DOOR_BLOCK( new ItemIronDoorBlock() ),
    WOODEN_PRESSURE_PLATE( new ItemWoodenPressurePlate() ),
    REDSTONE_ORE( new ItemRedstoneOre() ),
    GLOWING_REDSTONE_ORE( new ItemGlowingRedstoneOre() ),
    UNLIT_REDSTONE_TORCH( new ItemUnlitRedstoneTorch() ),
    REDSTONE_TORCH( new ItemRedstoneTorch() ),
    STONE_BUTTON( new ItemStoneButton() ),

    SNOW_LAYER( BlockType.SNOW_LAYER.<BlockSnowLayer>getBlock().setHeight( 0 ).toItem() ),

    ICE( new ItemIce() ),
    SNOW( new ItemSnow() ),
    CACTUS( new ItemCactus() ),
    CLAY( new ItemClay() ),
    SUGARCANE( new ItemSugarCane() ),
    JUKEBOX( new ItemJukebox() ),

    OAK_FENCE( new ItemFence().setWoodType( WoodType.OAK ) ),
    SPRUCE_FENCE( new ItemFence().setWoodType( WoodType.SPRUCE ) ),
    BIRCH_FENCE( new ItemFence().setWoodType( WoodType.BIRCH ) ),
    JUNGLE_FENCE( new ItemFence().setWoodType( WoodType.JUNGLE ) ),
    ACACIA_FENCE( new ItemFence().setWoodType( WoodType.ACACIA ) ),
    DARK_OAK_FENCE( new ItemFence().setWoodType( WoodType.DARK_OAK ) ),

    PUMPKIN( new ItemPumpkin() ),

    NETHERRACK( new ItemNetherrack() ),

    SOUL_SAND( new ItemSoulSand() ),
    GLOWSTONE( new ItemGlowstone() ),
    PORTAL( new ItemPortal() ),
    JACK_O_LANTERN( new ItemJackOLantern() ),
    CAKE_BLOCK( new ItemCakeBlock() ), //Maybe ItemCakeBlock
    UNPOWERED_REPEATER( new ItemUnpoweredRepeater() ),
    POWERED_REPEATER( new ItemPoweredRepeater() ),
    INVISIBLE_BEDROCK( new ItemInvisibleBedrock() ),
    WOODEN_TRAPDOOR( new ItemTrapdoor() ),

    INFESTED_STONE( BlockType.INFESTED_STONE.<BlockInfestedStone>getBlock().setMonsterEggStoneType( MonsterEggStoneType.STONE ).toItem() ),
    INFESTED_COBBLESTONE( BlockType.INFESTED_STONE.<BlockInfestedStone>getBlock().setMonsterEggStoneType( MonsterEggStoneType.COBBLESTONE ).toItem() ),
    INFESTED_STONE_BRICK( BlockType.INFESTED_STONE.<BlockInfestedStone>getBlock().setMonsterEggStoneType( MonsterEggStoneType.STONE_BRICK ).toItem() ),
    INFESTED_MOSSY_STONE_BRICK( BlockType.INFESTED_STONE.<BlockInfestedStone>getBlock().setMonsterEggStoneType( MonsterEggStoneType.MOSSY_STONE_BRICK ).toItem() ),
    INFESTED_CRACKED_STONE_BRICK( BlockType.INFESTED_STONE.<BlockInfestedStone>getBlock().setMonsterEggStoneType( MonsterEggStoneType.CRACKED_STONE_BRICK ).toItem() ),
    INFESTED_CHISELED_STONE_BRICK( BlockType.INFESTED_STONE.<BlockInfestedStone>getBlock().setMonsterEggStoneType( MonsterEggStoneType.CHISELED_STONE_BRICK ).toItem() ),

    STONEBRICK( BlockType.STONEBRICK.<BlockStonebrick>getBlock().setStoneBrickType( StoneBrickType.DEFAULT ).toItem() ),
    MOSSY_STONEBRICK( BlockType.STONEBRICK.<BlockStonebrick>getBlock().setStoneBrickType( StoneBrickType.MOSSY ).toItem() ),
    CRACKED_STONEBRICK( BlockType.STONEBRICK.<BlockStonebrick>getBlock().setStoneBrickType( StoneBrickType.CRACKED ).toItem() ),
    CHISELED_STONEBRICK( BlockType.STONEBRICK.<BlockStonebrick>getBlock().setStoneBrickType( StoneBrickType.CHISELED ).toItem() ),
    SMOOTH_STONEBRICK( BlockType.STONEBRICK.<BlockStonebrick>getBlock().setStoneBrickType( StoneBrickType.SMOOTH ).toItem() ),

    MUSHROOM_STEM_BLOCK( BlockType.BROWN_MUSHROOM_BLOCK.<BlockBrownMushroomBlock>getBlock().setHugeMushroom( 15 ).toItem() ),
    MUSHROOM_BLOCK( BlockType.BROWN_MUSHROOM_BLOCK.<BlockBrownMushroomBlock>getBlock().setHugeMushroom( 11 ).toItem() ),
    BROWN_MUSHROOM_BLOCK( BlockType.BROWN_MUSHROOM_BLOCK.<BlockBrownMushroomBlock>getBlock().setHugeMushroom( 14 ).toItem() ),

    RED_MUSHROOM_BLOCK( BlockType.RED_MUSHROOM_BLOCK.<BlockRedMushroomBlock>getBlock().setHugeMushroom( 14 ).toItem() ),

    IRON_BARS( new ItemIronBars() ),

    WHITE_STAINED_GLASS_PANE( BlockType.STAINED_GLASS_PANE.<BlockStainedGlassPane>getBlock().setColor( BlockColor.WHITE ).toItem() ),
    SILVER_STAINED_GLASS_PANE( BlockType.STAINED_GLASS_PANE.<BlockStainedGlassPane>getBlock().setColor( BlockColor.SILVER ).toItem() ),
    GRAY_STAINED_GLASS_PANE( BlockType.STAINED_GLASS_PANE.<BlockStainedGlassPane>getBlock().setColor( BlockColor.GRAY ).toItem() ),
    BLACK_STAINED_GLASS_PANE( BlockType.STAINED_GLASS_PANE.<BlockStainedGlassPane>getBlock().setColor( BlockColor.BLACK ).toItem() ),
    BROWN_STAINED_GLASS_PANE( BlockType.STAINED_GLASS_PANE.<BlockStainedGlassPane>getBlock().setColor( BlockColor.BROWN ).toItem() ),
    RED_STAINED_GLASS_PANE( BlockType.STAINED_GLASS_PANE.<BlockStainedGlassPane>getBlock().setColor( BlockColor.RED ).toItem() ),
    ORANGE_STAINED_GLASS_PANE( BlockType.STAINED_GLASS_PANE.<BlockStainedGlassPane>getBlock().setColor( BlockColor.ORANGE ).toItem() ),
    YELLOW_STAINED_GLASS_PANE( BlockType.STAINED_GLASS_PANE.<BlockStainedGlassPane>getBlock().setColor( BlockColor.YELLOW ).toItem() ),
    LIME_STAINED_GLASS_PANE( BlockType.STAINED_GLASS_PANE.<BlockStainedGlassPane>getBlock().setColor( BlockColor.LIME ).toItem() ),
    GREEN_STAINED_GLASS_PANE( BlockType.STAINED_GLASS_PANE.<BlockStainedGlassPane>getBlock().setColor( BlockColor.GREEN ).toItem() ),
    CYAN_STAINED_GLASS_PANE( BlockType.STAINED_GLASS_PANE.<BlockStainedGlassPane>getBlock().setColor( BlockColor.CYAN ).toItem() ),
    LIGHT_BLUE_STAINED_GLASS_PANE( BlockType.STAINED_GLASS_PANE.<BlockStainedGlassPane>getBlock().setColor( BlockColor.LIGHT_BLUE ).toItem() ),
    BLUE_STAINED_GLASS_PANE( BlockType.STAINED_GLASS_PANE.<BlockStainedGlassPane>getBlock().setColor( BlockColor.BLUE ).toItem() ),
    PURPLE_STAINED_GLASS_PANE( BlockType.STAINED_GLASS_PANE.<BlockStainedGlassPane>getBlock().setColor( BlockColor.PURPLE ).toItem() ),
    MAGENTA_STAINED_GLASS_PANE( BlockType.STAINED_GLASS_PANE.<BlockStainedGlassPane>getBlock().setColor( BlockColor.MAGENTA ).toItem() ),
    PINK_STAINED_GLASS_PANE( BlockType.STAINED_GLASS_PANE.<BlockStainedGlassPane>getBlock().setColor( BlockColor.PINK ).toItem() ),

    MELON_BLOCK( new ItemMelonBlock() ),
    PUMPKIN_STEM( new ItemPumpkinStem() ),
    MELON_STEM( new ItemMelonStem() ),
    VINE( new ItemVine() ),
    FENCE_GATE( new ItemFenceGate() ),
    BRICK_STAIRS( new ItemBrickStairs() ),
    STONE_BRICK_STAIRS( new ItemStoneBrickStairs() ),
    MYCELIUM( new ItemMycelium() ),
    WATERLILY( new ItemWaterlily() ),
    NETHER_BRICK_BLOCK( new ItemNetherBrickBlock() ),
    NETHER_BRICK_FENCE( new ItemNetherBrickFence() ),
    NETHER_BRICK_STAIRS( new ItemNetherBrickStairs() ),
    NETHER_WART_ITEM_BLOCK( new ItemNetherWartItemBlock() ),
    ENCHANTING_TABLE( new ItemEnchantingTable() ),
    BREWING_STAND_BLOCK( new ItemBrewingstandblock() ),
    CAULDRON_BLOCK( new ItemCauldronBlock() ),
    END_PORTAL( new ItemEndPortal() ),
    END_PORTAL_FRAME( new ItemEndPortalFrame() ),
    END_STONE( new ItemEndStone() ),
    DRAGON_EGG( new ItemDragonEgg() ),
    REDSTONE_LAMP( new ItemRedstoneLamp() ),
    GLOWING_REDSTONE_LAMP( new ItemLitRedstoneLamp() ),
    DROPPER( new ItemDropper() ),
    ACTIVATOR_RAIL( new ItemActivatorRail() ),
    COCOA( new ItemCocoa() ),
    SANDSTONE_STAIRS( new ItemSandstoneStairs() ),
    EMERALD_ORE( new ItemEmeraldOre() ),
    ENDER_CHEST( new ItemEnderChest() ),
    TRIPWIRE_HOOK( new ItemTripwireHook() ),
    TRIPWIRE( new ItemTripwire() ),
    EMERALD_BLOCK( new ItemEmeraldBlock() ),
    SPRUCE_STAIRS( new ItemSpruceStairs() ),
    BIRCH_STAIRS( new ItemBirchStairs() ),
    JUNGLE_STAIRS( new ItemJungleStairs() ),
    COMMAND_BLOCK( new ItemCommandBlock() ),
    BEACON( new ItemBeacon() ),

    COBBLESTONE_WALL( BlockType.COBBLESTONE_WALL.<BlockCobblestoneWall>getBlock().setWallBlockType( WallType.COBBLESTONE ).toItem() ),
    MOSSY_COBBLESTONE_WALL( BlockType.COBBLESTONE_WALL.<BlockCobblestoneWall>getBlock().setWallBlockType( WallType.MOSSY_COBBLESTONE ).toItem() ),
    GRANITE_WALL( BlockType.COBBLESTONE_WALL.<BlockCobblestoneWall>getBlock().setWallBlockType( WallType.GRANITE ).toItem() ),
    DIORITE_WALL( BlockType.COBBLESTONE_WALL.<BlockCobblestoneWall>getBlock().setWallBlockType( WallType.DIORITE ).toItem() ),
    ANDESITE_WALL( BlockType.COBBLESTONE_WALL.<BlockCobblestoneWall>getBlock().setWallBlockType( WallType.ANDESITE ).toItem() ),
    SANDSTONE_WALL( BlockType.COBBLESTONE_WALL.<BlockCobblestoneWall>getBlock().setWallBlockType( WallType.SANDSTONE ).toItem() ),
    RED_SANDSTONE_WALL( BlockType.COBBLESTONE_WALL.<BlockCobblestoneWall>getBlock().setWallBlockType( WallType.RED_SANDSTONE ).toItem() ),
    STONE_BRICK_WALL( BlockType.COBBLESTONE_WALL.<BlockCobblestoneWall>getBlock().setWallBlockType( WallType.STONE_BRICK ).toItem() ),
    MOSSY_STONE_BRICK_WALL( BlockType.COBBLESTONE_WALL.<BlockCobblestoneWall>getBlock().setWallBlockType( WallType.MOSSY_STONE_BRICK ).toItem() ),
    BRICK_WALL( BlockType.COBBLESTONE_WALL.<BlockCobblestoneWall>getBlock().setWallBlockType( WallType.BRICK ).toItem() ),
    NETHER_BRICK_WALL( BlockType.COBBLESTONE_WALL.<BlockCobblestoneWall>getBlock().setWallBlockType( WallType.NETHER_BRICK ).toItem() ),
    RED_NETHER_BRICK_WALL( BlockType.COBBLESTONE_WALL.<BlockCobblestoneWall>getBlock().setWallBlockType( WallType.RED_NETHER_BRICK ).toItem() ),
    ENDSTONE_WALL( BlockType.COBBLESTONE_WALL.<BlockCobblestoneWall>getBlock().setWallBlockType( WallType.END_BRICK ).toItem() ),
    PRISMARINE_WALL( BlockType.COBBLESTONE_WALL.<BlockCobblestoneWall>getBlock().setWallBlockType( WallType.PRISMARINE ).toItem() ),

    FLOWER_POT_BLOCK( new ItemFlowerPotBlock() ),
    CARROTS( new ItemCarrots() ),
    POTATOES( new ItemPotatoes() ),
    WOODEN_BUTTON( new ItemWoodenButton() ),
    SKULL_BLOCK( new ItemSkullBlock() ),

    ANVIL( BlockType.ANVIL.<BlockAnvil>getBlock().setDamage( AnvilDamage.UNDAMAGED ).toItem() ),
    SLIGHTLY_DAMAGED_ANVIL( BlockType.ANVIL.<BlockAnvil>getBlock().setDamage( AnvilDamage.SLIGHTLY_DAMAGED ).toItem() ),
    VERY_DAMAGED_ANVIL( BlockType.ANVIL.<BlockAnvil>getBlock().setDamage( AnvilDamage.VERY_DAMAGED ).toItem() ),
    BROKEN_ANVIL( BlockType.ANVIL.<BlockAnvil>getBlock().setDamage( AnvilDamage.UNDAMAGED ).toItem() ),

    TRAPPED_CHEST( new ItemTrappedChest() ),
    LIGHT_WEIGHTED_PRESSURE_PLATE( new ItemLightWeightedPressurePlate() ),
    HEAVY_WEIGHTED_PRESSURE_PLATE( new ItemHeavyWeightedPressurePlate() ),
    UNPOWERED_COMPARATOR( new ItemUnpoweredComparator() ),
    POWERED_COMPARATOR( new ItemPoweredComparator() ),
    DAYLIGHT_DETECTOR( new ItemDaylightDetector() ),
    REDSTONE_BLOCK( new ItemRedstoneBlock() ),
    QUARTZ_ORE( new ItemQuartzOre() ),
    HOPPER_BLOCK( new ItemHopperBlock() ),

    QUARTZ_BLOCK( BlockType.QUARTZ_BLOCK.<BlockQuartzBlock>getBlock().setQuartzType( QuartzType.DEFAULT ).toItem() ),
    QUARTZ_CHISELED( BlockType.QUARTZ_BLOCK.<BlockQuartzBlock>getBlock().setQuartzType( QuartzType.CHISELED ).toItem() ),
    QUARTZ_LINES( BlockType.QUARTZ_BLOCK.<BlockQuartzBlock>getBlock().setQuartzType( QuartzType.LINES ).toItem() ),
    QUARTZ_SMOOTH( BlockType.QUARTZ_BLOCK.<BlockQuartzBlock>getBlock().setQuartzType( QuartzType.SMOOTH ).toItem() ),

    QUARTZ_STAIRS( new ItemQuartzStairs() ),
    DOUBLE_WOODEN_SLAB( new ItemDoubleWoodenSlab() ),
    OAK_WOODEN_SLAB( BlockType.WOODEN_SLAB.<BlockWoodenSlab>getBlock().setWoodType( WoodType.OAK ).setTopSlot( false ).toItem() ),
    SPRUCE_WOODEN_SLAB( BlockType.WOODEN_SLAB.<BlockWoodenSlab>getBlock().setWoodType( WoodType.SPRUCE ).setTopSlot( false ).toItem() ),
    BIRCH_WOODEN_SLAB( BlockType.WOODEN_SLAB.<BlockWoodenSlab>getBlock().setWoodType( WoodType.BIRCH ).setTopSlot( false ).toItem() ),
    JUNGLE_WOODEN_SLAB( BlockType.WOODEN_SLAB.<BlockWoodenSlab>getBlock().setWoodType( WoodType.JUNGLE ).setTopSlot( false ).toItem() ),
    ACACIA_WOODEN_SLAB( BlockType.WOODEN_SLAB.<BlockWoodenSlab>getBlock().setWoodType( WoodType.ACACIA ).setTopSlot( false ).toItem() ),
    DARK_OAK_WOODEN_SLAB( BlockType.WOODEN_SLAB.<BlockWoodenSlab>getBlock().setWoodType( WoodType.DARK_OAK ).setTopSlot( false ).toItem() ),

    WHITE_STAINED_HARDENED_CLAY( BlockType.STAINED_HARDENED_CLAY.<BlockStainedHardenedClay>getBlock().setColor( BlockColor.WHITE ).toItem() ),
    SILVER_STAINED_HARDENED_CLAY( BlockType.STAINED_HARDENED_CLAY.<BlockStainedHardenedClay>getBlock().setColor( BlockColor.SILVER ).toItem() ),
    GRAY_STAINED_HARDENED_CLAY( BlockType.STAINED_HARDENED_CLAY.<BlockStainedHardenedClay>getBlock().setColor( BlockColor.GRAY ).toItem() ),
    BLACK_STAINED_HARDENED_CLAY( BlockType.STAINED_HARDENED_CLAY.<BlockStainedHardenedClay>getBlock().setColor( BlockColor.BLACK ).toItem() ),
    BROWN_STAINED_HARDENED_CLAY( BlockType.STAINED_HARDENED_CLAY.<BlockStainedHardenedClay>getBlock().setColor( BlockColor.BROWN ).toItem() ),
    RED_STAINED_HARDENED_CLAY( BlockType.STAINED_HARDENED_CLAY.<BlockStainedHardenedClay>getBlock().setColor( BlockColor.RED ).toItem() ),
    ORANGE_STAINED_HARDENED_CLAY( BlockType.STAINED_HARDENED_CLAY.<BlockStainedHardenedClay>getBlock().setColor( BlockColor.ORANGE ).toItem() ),
    YELLOW_STAINED_HARDENED_CLAY( BlockType.STAINED_HARDENED_CLAY.<BlockStainedHardenedClay>getBlock().setColor( BlockColor.YELLOW ).toItem() ),
    LIME_STAINED_HARDENED_CLAY( BlockType.STAINED_HARDENED_CLAY.<BlockStainedHardenedClay>getBlock().setColor( BlockColor.LIME ).toItem() ),
    GREEN_STAINED_HARDENED_CLAY( BlockType.STAINED_HARDENED_CLAY.<BlockStainedHardenedClay>getBlock().setColor( BlockColor.GREEN ).toItem() ),
    CYAN_STAINED_HARDENED_CLAY( BlockType.STAINED_HARDENED_CLAY.<BlockStainedHardenedClay>getBlock().setColor( BlockColor.CYAN ).toItem() ),
    LIGHT_BLUE_STAINED_HARDENED_CLAY( BlockType.STAINED_HARDENED_CLAY.<BlockStainedHardenedClay>getBlock().setColor( BlockColor.LIGHT_BLUE ).toItem() ),
    BLUE_STAINED_HARDENED_CLAY( BlockType.STAINED_HARDENED_CLAY.<BlockStainedHardenedClay>getBlock().setColor( BlockColor.BLUE ).toItem() ),
    PURPLE_STAINED_HARDENED_CLAY( BlockType.STAINED_HARDENED_CLAY.<BlockStainedHardenedClay>getBlock().setColor( BlockColor.PURPLE ).toItem() ),
    MAGENTA_STAINED_HARDENED_CLAY( BlockType.STAINED_HARDENED_CLAY.<BlockStainedHardenedClay>getBlock().setColor( BlockColor.MAGENTA ).toItem() ),
    PINK_STAINED_HARDENED_CLAY( BlockType.STAINED_HARDENED_CLAY.<BlockStainedHardenedClay>getBlock().setColor( BlockColor.PINK ).toItem() ),

    ACACIA_STAIRS( new ItemAcaciaStairs() ),
    DARK_OAK_STAIRS( new ItemDarkOakStairs() ),
    SLIME( new ItemSlime() ),
    GLOW_STICK( new ItemGlowStick() ),
    IRON_TRAPDOOR( new ItemIronTrapdoor() ),

    PRISMARINE_BLOCK( BlockType.PRISMARINE.<BlockPrismarine>getBlock().setPrismarineType( PrismarineType.DEFAULT ).toItem() ),
    PRISMARINE_BRICKS( BlockType.PRISMARINE.<BlockPrismarine>getBlock().setPrismarineType( PrismarineType.BRICKS ).toItem() ),
    PRISMARINE_DARK( BlockType.PRISMARINE.<BlockPrismarine>getBlock().setPrismarineType( PrismarineType.DARK ).toItem() ),

    SEALANTERN( new ItemSealantern() ),
    HAY_BLOCK( new ItemHayBlock() ),
    WHITE_CARPET( BlockType.CARPET.<BlockCarpet>getBlock().setColor( BlockColor.WHITE ).toItem() ),
    ORANGE_CARPET( BlockType.CARPET.<BlockCarpet>getBlock().setColor( BlockColor.ORANGE ).toItem() ),
    MAGENTA_CARPET( BlockType.CARPET.<BlockCarpet>getBlock().setColor( BlockColor.MAGENTA ).toItem() ),
    LIGHT_BLUE_CARPET( BlockType.CARPET.<BlockCarpet>getBlock().setColor( BlockColor.LIGHT_BLUE ).toItem() ),
    YELLOW_CARPET( BlockType.CARPET.<BlockCarpet>getBlock().setColor( BlockColor.YELLOW ).toItem() ),
    LIME_CARPET( BlockType.CARPET.<BlockCarpet>getBlock().setColor( BlockColor.LIME ).toItem() ),
    PINK_CARPET( BlockType.CARPET.<BlockCarpet>getBlock().setColor( BlockColor.PINK ).toItem() ),
    GRAY_CARPET( BlockType.CARPET.<BlockCarpet>getBlock().setColor( BlockColor.GRAY ).toItem() ),
    SILVER_CARPET( BlockType.CARPET.<BlockCarpet>getBlock().setColor( BlockColor.SILVER ).toItem() ),
    CYAN_CARPET( BlockType.CARPET.<BlockCarpet>getBlock().setColor( BlockColor.CYAN ).toItem() ),
    PURPLE_CARPET( BlockType.CARPET.<BlockCarpet>getBlock().setColor( BlockColor.PURPLE ).toItem() ),
    BLUE_CARPET( BlockType.CARPET.<BlockCarpet>getBlock().setColor( BlockColor.BLUE ).toItem() ),
    BROWN_CARPET( BlockType.CARPET.<BlockCarpet>getBlock().setColor( BlockColor.BROWN ).toItem() ),
    GREEN_CARPET( BlockType.CARPET.<BlockCarpet>getBlock().setColor( BlockColor.GREEN ).toItem() ),
    RED_CARPET( BlockType.CARPET.<BlockCarpet>getBlock().setColor( BlockColor.RED ).toItem() ),
    BLACK_CARPET( BlockType.CARPET.<BlockCarpet>getBlock().setColor( BlockColor.BLACK ).toItem() ),

    HARDENED_CLAY( new ItemHardenedClay() ),
    COAL_BLOCK( new ItemCoalBlock() ),
    PACKED_ICE( new ItemPackedIce() ),

    LARGE_FERN( BlockType.DOUBLE_PLANT.<BlockDoublePlant>getBlock().setPlantType( PlantType.FERN ).toItem() ),
    //LARGE_FERN_UPPER( BlockType.DOUBLE_PLANT.<BlockDoublePlant>getBlock().setPlantType( PlantType.FERN ).setUpperBlock( true ).toItem() ),

    DOUBLE_TALLGRASS( BlockType.DOUBLE_PLANT.<BlockDoublePlant>getBlock().setPlantType( PlantType.GRASS ).toItem() ),
    //DOUBLE_TALLGRASS_UPPER( BlockType.DOUBLE_PLANT.<BlockDoublePlant>getBlock().setPlantType( PlantType.GRASS ).setUpperBlock( true ).toItem() ),

    SUNFLOWER( BlockType.DOUBLE_PLANT.<BlockDoublePlant>getBlock().setPlantType( PlantType.SUNFLOWER ).toItem() ),
    //SUNFLOWER_UPPER( BlockType.DOUBLE_PLANT.<BlockDoublePlant>getBlock().setPlantType( PlantType.SUNFLOWER ).setUpperBlock( true ).toItem() ),

    LILLAC_FLOWER( BlockType.DOUBLE_PLANT.<BlockDoublePlant>getBlock().setPlantType( PlantType.SYRINGA ).toItem() ),
    //LILLAC_FLOWER_UPPER( BlockType.DOUBLE_PLANT.<BlockDoublePlant>getBlock().setPlantType( PlantType.SYRINGA ).setUpperBlock( true ).toItem() ),

    ROSE_BUSH( BlockType.DOUBLE_PLANT.<BlockDoublePlant>getBlock().setPlantType( PlantType.ROSE ).toItem() ),
    //ROSE_BUSH_UPPER( BlockType.DOUBLE_PLANT.<BlockDoublePlant>getBlock().setPlantType( PlantType.ROSE ).setUpperBlock( true ).toItem() ),

    PEONY_FLOWER( BlockType.DOUBLE_PLANT.<BlockDoublePlant>getBlock().setPlantType( PlantType.PAEONIA ).toItem() ),
    //PEONY_FLOWER_UPPER( BlockType.DOUBLE_PLANT.<BlockDoublePlant>getBlock().setPlantType( PlantType.PAEONIA ).setUpperBlock( true ).toItem() ),

    STANDING_BANNER( new ItemStandingBanner() ),
    WALL_BANNER( new ItemWallBanner() ),
    DAYLIGHT_DETECTOR_INVERTED( new ItemDaylightDetectorInverted() ),

    RED_SANDSTONE( BlockType.RED_SANDSTONE.<BlockRedSandstone>getBlock().setSandStoneType( SandStoneType.DEFAULT ).toItem() ),
    CHISELED_RED_SANDSTONE( BlockType.RED_SANDSTONE.<BlockRedSandstone>getBlock().setSandStoneType( SandStoneType.HEIROGLYPHS ).toItem() ),
    CUT_RED_SANDSTONE( BlockType.RED_SANDSTONE.<BlockRedSandstone>getBlock().setSandStoneType( SandStoneType.CUT ).toItem() ),
    SMOOTH_RED_SANDSTONE( BlockType.RED_SANDSTONE.<BlockRedSandstone>getBlock().setSandStoneType( SandStoneType.SMOOTH ).toItem() ),

    RED_SANDSTONE_STAIRS( new ItemRedSandstoneStairs() ),
    REAL_DOUBLE_RED_SANDSTONE_SLAB( new ItemRealDoubleRedSandstoneSlab() ),
    SPRUCE_FENCE_GATE( new ItemSpruceFenceGate() ),
    BIRCH_FENCE_GATE( new ItemBirchFenceGate() ),
    JUNGLE_FENCE_GATE( new ItemJungleFenceGate() ),
    DARK_OAK_FENCE_GATE( new ItemDarkOakFenceGate() ),
    ACACIA_FENCE_GATE( new ItemAcaciaFenceGate() ),
    REPEATING_COMMAND_BLOCK( new ItemRepeatingCommandBlock() ),
    CHAIN_COMMAND_BLOCK( new ItemChainCommandBlock() ),
    HARD_GLASS_PANE( new ItemHardGlassPane() ),
    HARD_STAINED_GLASS_PANE( new ItemHardStainedGlassPane() ),
    CHEMICAL_HEAT( new ItemChemicalHeat() ),
    SPRUCE_DOOR_BLOCK( new ItemSpruceDoorBlock() ),
    BIRCH_DOOR_BLOCK( new ItemBirchDoorBlock() ),
    JUNGLE_DOOR_BLOCK( new ItemJungleDoorBlock() ),
    ACACIA_DOOR_BLOCK( new ItemAcaciaDoorBlock() ),
    DARK_OAK_DOOR_BLOCK( new ItemDarkOakDoorBlock() ),
    GRASS_PATH( new ItemGrassPath() ),
    FRAME_BLOCK( new ItemFrameBlock() ),
    CHORUS_FLOWER( new ItemChorusFlower() ),

    PURPUR_BLOCK( BlockType.PURPUR_BLOCK.<BlockPurpurBlock>getBlock().setPurpurType( PurpurType.DEFAULT ).toItem() ),
    PURPUR_BLOCK2( BlockType.PURPUR_BLOCK.<BlockPurpurBlock>getBlock().setPurpurType( PurpurType.LINES ).toItem() ),

    COLORED_TORCH_RG( new ItemColoredTorchRG() ),
    PURPUR_STAIRS( new ItemPurpurStairs() ),
    COLORED_TORCH_BP( new ItemColoredTorchBP() ),
    UNDYED_SHULKER_BOX( new ItemUndyedShulkerBox() ),
    END_BRICKS( new ItemEndBricks() ),
    FROSTED_ICE( new ItemFrostedIce() ),
    END_ROD( new ItemEndRod() ),
    END_GATEWAY( new ItemEndGateway() ),
    ALLOW( new ItemAllow() ),
    DENY( new ItemDeny() ),
    BORDER_BLOCK( new ItemBorderBlock() ),
    MAGMA( new ItemMagma() ),
    NETHER_WART_BLOCK( new ItemNetherWartBlock() ),
    RED_NETHER_BRICK( new ItemRedNetherBrick() ),
    BONE_BLOCK( new ItemBoneBlock() ),
    STRUCTURE_VOID( new ItemStructureVoid() ),

    WHITE_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.WHITE ).toItem() ),
    ORANGE_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.ORANGE ).toItem() ),
    MAGENTA_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.MAGENTA ).toItem() ),
    LIGHT_BLUE_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.LIGHT_BLUE ).toItem() ),
    YELLOW_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.YELLOW ).toItem() ),
    LIME_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.LIME ).toItem() ),
    PINK_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.PINK ).toItem() ),
    GRAY_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.GRAY ).toItem() ),
    SILVER_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.SILVER ).toItem() ),
    CYAN_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.CYAN ).toItem() ),
    PURPLE_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.PURPLE ).toItem() ),
    BLUE_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.BLUE ).toItem() ),
    BROWN_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.BROWN ).toItem() ),
    GREEN_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.GREEN ).toItem() ),
    RED_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.RED ).toItem() ),
    BLACK_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.BLACK ).toItem() ),

    PURPLE_GLAZED_TERRACOTTA( new ItemPurpleGlazedTerracotta() ),
    WHITE_GLAZED_TERRACOTTA( new ItemWhiteGlazedTerracotta() ),
    ORANGE_GLAZED_TERRACOTTA( new ItemOrangeGlazedTerracotta() ),
    MAGENTA_GLAZED_TERRACOTTA( new ItemMagentaGlazedTerracotta() ),
    LIGHT_BLUE_GLAZED_TERRACOTTA( new ItemLightBlueGlazedTerracotta() ),
    YELLOW_GLAZED_TERRACOTTA( new ItemYellowGlazedTerracotta() ),
    LIME_GLAZED_TERRACOTTA( new ItemLimeGlazedTerracotta() ),
    PINK_GLAZED_TERRACOTTA( new ItemPinkGlazedTerracotta() ),
    GRAY_GLAZED_TERRACOTTA( new ItemGrayGlazedTerracotta() ),
    SILVER_GLAZED_TERRACOTTA( new ItemSilverGlazedTerracotta() ),
    CYAN_GLAZED_TERRACOTTA( new ItemCyanGlazedTerracotta() ),
    BLUE_GLAZED_TERRACOTTA( new ItemBlueGlazedTerracotta() ),
    BROWN_GLAZED_TERRACOTTA( new ItemBrownGlazedTerracotta() ),
    GREEN_GLAZED_TERRACOTTA( new ItemGreenGlazedTerracotta() ),
    RED_GLAZED_TERRACOTTA( new ItemRedGlazedTerracotta() ),
    BLACK_GLAZED_TERRACOTTA( new ItemBlackGlazedTerracotta() ),

    WHITE_CONCRETE( BlockType.CONCRETE.<BlockConcrete>getBlock().setColor( BlockColor.WHITE ).toItem() ),
    SILVER_CONCRETE( BlockType.CONCRETE.<BlockConcrete>getBlock().setColor( BlockColor.SILVER ).toItem() ),
    GRAY_CONCRETE( BlockType.CONCRETE.<BlockConcrete>getBlock().setColor( BlockColor.GRAY ).toItem() ),
    BLACK_CONCRETE( BlockType.CONCRETE.<BlockConcrete>getBlock().setColor( BlockColor.BLACK ).toItem() ),
    BROWN_CONCRETE( BlockType.CONCRETE.<BlockConcrete>getBlock().setColor( BlockColor.BROWN ).toItem() ),
    RED_CONCRETE( BlockType.CONCRETE.<BlockConcrete>getBlock().setColor( BlockColor.RED ).toItem() ),
    ORANGE_CONCRETE( BlockType.CONCRETE.<BlockConcrete>getBlock().setColor( BlockColor.ORANGE ).toItem() ),
    YELLOW_CONCRETE( BlockType.CONCRETE.<BlockConcrete>getBlock().setColor( BlockColor.YELLOW ).toItem() ),
    LIME_CONCRETE( BlockType.CONCRETE.<BlockConcrete>getBlock().setColor( BlockColor.LIME ).toItem() ),
    GREEN_CONCRETE( BlockType.CONCRETE.<BlockConcrete>getBlock().setColor( BlockColor.GREEN ).toItem() ),
    CYAN_CONCRETE( BlockType.CONCRETE.<BlockConcrete>getBlock().setColor( BlockColor.CYAN ).toItem() ),
    LIGHT_BLUE_CONCRETE( BlockType.CONCRETE.<BlockConcrete>getBlock().setColor( BlockColor.LIGHT_BLUE ).toItem() ),
    BLUE_CONCRETE( BlockType.CONCRETE.<BlockConcrete>getBlock().setColor( BlockColor.BLUE ).toItem() ),
    PURPLE_CONCRETE( BlockType.CONCRETE.<BlockConcrete>getBlock().setColor( BlockColor.PURPLE ).toItem() ),
    MAGENTA_CONCRETE( BlockType.CONCRETE.<BlockConcrete>getBlock().setColor( BlockColor.MAGENTA ).toItem() ),
    PINK_CONCRETE( BlockType.CONCRETE.<BlockConcrete>getBlock().setColor( BlockColor.PINK ).toItem() ),

    WHITE_CONCRETEPOWDER( BlockType.CONCRETEPOWDER.<BlockConcretePowder>getBlock().setColor( BlockColor.WHITE ).toItem() ),
    SILVER_CONCRETEPOWDER( BlockType.CONCRETEPOWDER.<BlockConcretePowder>getBlock().setColor( BlockColor.SILVER ).toItem() ),
    GRAY_CONCRETEPOWDER( BlockType.CONCRETEPOWDER.<BlockConcretePowder>getBlock().setColor( BlockColor.GRAY ).toItem() ),
    BLACK_CONCRETEPOWDER( BlockType.CONCRETEPOWDER.<BlockConcretePowder>getBlock().setColor( BlockColor.BLACK ).toItem() ),
    BROWN_CONCRETEPOWDER( BlockType.CONCRETEPOWDER.<BlockConcretePowder>getBlock().setColor( BlockColor.BROWN ).toItem() ),
    RED_CONCRETEPOWDER( BlockType.CONCRETEPOWDER.<BlockConcretePowder>getBlock().setColor( BlockColor.RED ).toItem() ),
    ORANGE_CONCRETEPOWDER( BlockType.CONCRETEPOWDER.<BlockConcretePowder>getBlock().setColor( BlockColor.ORANGE ).toItem() ),
    YELLOW_CONCRETEPOWDER( BlockType.CONCRETEPOWDER.<BlockConcretePowder>getBlock().setColor( BlockColor.YELLOW ).toItem() ),
    LIME_CONCRETEPOWDER( BlockType.CONCRETEPOWDER.<BlockConcretePowder>getBlock().setColor( BlockColor.LIME ).toItem() ),
    GREEN_CONCRETEPOWDER( BlockType.CONCRETEPOWDER.<BlockConcretePowder>getBlock().setColor( BlockColor.GREEN ).toItem() ),
    CYAN_CONCRETEPOWDER( BlockType.CONCRETEPOWDER.<BlockConcretePowder>getBlock().setColor( BlockColor.CYAN ).toItem() ),
    LIGHT_BLUE_CONCRETEPOWDER( BlockType.CONCRETEPOWDER.<BlockConcretePowder>getBlock().setColor( BlockColor.LIGHT_BLUE ).toItem() ),
    BLUE_CONCRETEPOWDER( BlockType.CONCRETEPOWDER.<BlockConcretePowder>getBlock().setColor( BlockColor.BLUE ).toItem() ),
    PURPLE_CONCRETEPOWDER( BlockType.CONCRETEPOWDER.<BlockConcretePowder>getBlock().setColor( BlockColor.PURPLE ).toItem() ),
    MAGENTA_CONCRETEPOWDER( BlockType.CONCRETEPOWDER.<BlockConcretePowder>getBlock().setColor( BlockColor.MAGENTA ).toItem() ),
    PINK_CONCRETEPOWDER( BlockType.CONCRETEPOWDER.<BlockConcretePowder>getBlock().setColor( BlockColor.PINK ).toItem() ),

    CHEMISTRY_TABLE( new ItemChemistryTable() ),
    UNDERWATER_TORCH( new ItemUnderwaterTorch() ),
    CHORUS_PLANT( new ItemChorusPlant() ),

    WHITE_STAINED_GLASS( BlockType.STAINED_GLASS.<BlockStainedGlass>getBlock().setColor( BlockColor.WHITE ).toItem() ),
    SILVER_STAINED_GLASS( BlockType.STAINED_GLASS.<BlockStainedGlass>getBlock().setColor( BlockColor.SILVER ).toItem() ),
    GRAY_STAINED_GLASS( BlockType.STAINED_GLASS.<BlockStainedGlass>getBlock().setColor( BlockColor.GRAY ).toItem() ),
    BLACK_STAINED_GLASS( BlockType.STAINED_GLASS.<BlockStainedGlass>getBlock().setColor( BlockColor.BLACK ).toItem() ),
    BROWN_STAINED_GLASS( BlockType.STAINED_GLASS.<BlockStainedGlass>getBlock().setColor( BlockColor.BROWN ).toItem() ),
    RED_STAINED_GLASS( BlockType.STAINED_GLASS.<BlockStainedGlass>getBlock().setColor( BlockColor.RED ).toItem() ),
    ORANGE_STAINED_GLASS( BlockType.STAINED_GLASS.<BlockStainedGlass>getBlock().setColor( BlockColor.ORANGE ).toItem() ),
    YELLOW_STAINED_GLASS( BlockType.STAINED_GLASS.<BlockStainedGlass>getBlock().setColor( BlockColor.YELLOW ).toItem() ),
    LIME_STAINED_GLASS( BlockType.STAINED_GLASS.<BlockStainedGlass>getBlock().setColor( BlockColor.LIME ).toItem() ),
    GREEN_STAINED_GLASS( BlockType.STAINED_GLASS.<BlockStainedGlass>getBlock().setColor( BlockColor.GREEN ).toItem() ),
    CYAN_STAINED_GLASS( BlockType.STAINED_GLASS.<BlockStainedGlass>getBlock().setColor( BlockColor.CYAN ).toItem() ),
    LIGHT_BLUE_STAINED_GLASS( BlockType.STAINED_GLASS.<BlockStainedGlass>getBlock().setColor( BlockColor.LIGHT_BLUE ).toItem() ),
    BLUE_STAINED_GLASS( BlockType.STAINED_GLASS.<BlockStainedGlass>getBlock().setColor( BlockColor.BLUE ).toItem() ),
    PURPLE_STAINED_GLASS( BlockType.STAINED_GLASS.<BlockStainedGlass>getBlock().setColor( BlockColor.PURPLE ).toItem() ),
    MAGENTA_STAINED_GLASS( BlockType.STAINED_GLASS.<BlockStainedGlass>getBlock().setColor( BlockColor.MAGENTA ).toItem() ),
    PINK_STAINED_GLASS( BlockType.STAINED_GLASS.<BlockStainedGlass>getBlock().setColor( BlockColor.PINK ).toItem() ),

    CAMERA_BLOCK( new ItemCameraBlock() ),
    PODZOL( new ItemPodzol() ),
    BEETROOT_BLOCK( new ItemBeetrootBlock() ),
    STONECUTTER( new ItemStonecutter() ),
    GLOWING_OBSIDIAN( new ItemGlowingObsidian() ),
    NETHERREACTOR( new ItemNetherreactor() ),
    INFO_UPDATE( new ItemInfoUpdate() ),
    INFO_UPDATE2( new ItemInfoUpdate2() ),
    MOVING_BLOCK( new ItemMovingblock() ),
    OBSERVER( new ItemObserver() ),
    STRUCTURE_BLOCK( new ItemStructureBlock() ),
    HARD_GLASS( new ItemHardGlass() ),
    HARD_STAINED_GLASS( new ItemHardStainedGlass() ),
    RESERVED6( new ItemReserved6() ),
    PRISMARINE_STAIRS( new ItemPrismarineStairs() ),
    DARK_PRISMARINE_STAIRS( new ItemDarkPrismarineStairs() ),
    PRISMARINE_BRICKS_STAIRS( new ItemPrismarineBricksStairs() ),
    STRIPPED_SPRUCE_LOG( new ItemStrippedSpruceLog() ),
    STRIPPED_BIRCH_LOG( new ItemStrippedBirchLog() ),
    STRIPPED_JUNGLE_LOG( new ItemStrippedJungleLog() ),
    STRIPPED_ACACIA_LOG( new ItemStrippedAcaciaLog() ),
    STRIPPED_DARK_OAK_LOG( new ItemStrippedDarkOakLog() ),
    STRIPPED_OAK_LOG( new ItemStrippedOakLog() ),
    BLUE_ICE( new ItemBlueIce() ),
    ELEMENT_1( new ItemElement1() ),
    ELEMENT_2( new ItemElement2() ),
    ELEMENT_3( new ItemElement3() ),
    ELEMENT_4( new ItemElement4() ),
    ELEMENT_5( new ItemElement5() ),
    ELEMENT_6( new ItemElement6() ),
    ELEMENT_7( new ItemElement7() ),
    ELEMENT_8( new ItemElement8() ),
    ELEMENT_9( new ItemElement9() ),
    ELEMENT_10( new ItemElement10() ),
    ELEMENT_11( new ItemElement11() ),
    ELEMENT_12( new ItemElement12() ),
    ELEMENT_13( new ItemElement13() ),
    ELEMENT_14( new ItemElement14() ),
    ELEMENT_15( new ItemElement15() ),
    ELEMENT_16( new ItemElement16() ),
    ELEMENT_17( new ItemElement17() ),
    ELEMENT_18( new ItemElement18() ),
    ELEMENT_19( new ItemElement19() ),
    ELEMENT_20( new ItemElement20() ),
    ELEMENT_21( new ItemElement21() ),
    ELEMENT_22( new ItemElement22() ),
    ELEMENT_23( new ItemElement23() ),
    ELEMENT_24( new ItemElement24() ),
    ELEMENT_25( new ItemElement25() ),
    ELEMENT_26( new ItemElement26() ),
    ELEMENT_27( new ItemElement27() ),
    ELEMENT_28( new ItemElement28() ),
    ELEMENT_29( new ItemElement29() ),
    ELEMENT_30( new ItemElement30() ),
    ELEMENT_31( new ItemElement31() ),
    ELEMENT_32( new ItemElement32() ),
    ELEMENT_33( new ItemElement33() ),
    ELEMENT_34( new ItemElement34() ),
    ELEMENT_35( new ItemElement35() ),
    ELEMENT_36( new ItemElement36() ),
    ELEMENT_37( new ItemElement37() ),
    ELEMENT_38( new ItemElement38() ),
    ELEMENT_39( new ItemElement39() ),
    ELEMENT_40( new ItemElement40() ),
    ELEMENT_41( new ItemElement41() ),
    ELEMENT_42( new ItemElement42() ),
    ELEMENT_43( new ItemElement43() ),
    ELEMENT_44( new ItemElement44() ),
    ELEMENT_45( new ItemElement45() ),
    ELEMENT_46( new ItemElement46() ),
    ELEMENT_47( new ItemElement47() ),
    ELEMENT_48( new ItemElement48() ),
    ELEMENT_49( new ItemElement49() ),
    ELEMENT_50( new ItemElement50() ),
    ELEMENT_51( new ItemElement51() ),
    ELEMENT_52( new ItemElement52() ),
    ELEMENT_53( new ItemElement53() ),
    ELEMENT_54( new ItemElement54() ),
    ELEMENT_55( new ItemElement55() ),
    ELEMENT_56( new ItemElement56() ),
    ELEMENT_57( new ItemElement57() ),
    ELEMENT_58( new ItemElement58() ),
    ELEMENT_59( new ItemElement59() ),
    ELEMENT_60( new ItemElement60() ),
    ELEMENT_61( new ItemElement61() ),
    ELEMENT_62( new ItemElement62() ),
    ELEMENT_63( new ItemElement63() ),
    ELEMENT_64( new ItemElement64() ),
    ELEMENT_65( new ItemElement65() ),
    ELEMENT_66( new ItemElement66() ),
    ELEMENT_67( new ItemElement67() ),
    ELEMENT_68( new ItemElement68() ),
    ELEMENT_69( new ItemElement69() ),
    ELEMENT_70( new ItemElement70() ),
    ELEMENT_71( new ItemElement71() ),
    ELEMENT_72( new ItemElement72() ),
    ELEMENT_73( new ItemElement73() ),
    ELEMENT_74( new ItemElement74() ),
    ELEMENT_75( new ItemElement75() ),
    ELEMENT_76( new ItemElement76() ),
    ELEMENT_77( new ItemElement77() ),
    ELEMENT_78( new ItemElement78() ),
    ELEMENT_79( new ItemElement79() ),
    ELEMENT_80( new ItemElement80() ),
    ELEMENT_81( new ItemElement81() ),
    ELEMENT_82( new ItemElement82() ),
    ELEMENT_83( new ItemElement83() ),
    ELEMENT_84( new ItemElement84() ),
    ELEMENT_85( new ItemElement85() ),
    ELEMENT_86( new ItemElement86() ),
    ELEMENT_87( new ItemElement87() ),
    ELEMENT_88( new ItemElement88() ),
    ELEMENT_89( new ItemElement89() ),
    ELEMENT_90( new ItemElement90() ),
    ELEMENT_91( new ItemElement91() ),
    ELEMENT_92( new ItemElement92() ),
    ELEMENT_93( new ItemElement93() ),
    ELEMENT_94( new ItemElement94() ),
    ELEMENT_95( new ItemElement95() ),
    ELEMENT_96( new ItemElement96() ),
    ELEMENT_97( new ItemElement97() ),
    ELEMENT_98( new ItemElement98() ),
    ELEMENT_99( new ItemElement99() ),
    ELEMENT_100( new ItemElement100() ),
    ELEMENT_101( new ItemElement101() ),
    ELEMENT_102( new ItemElement102() ),
    ELEMENT_103( new ItemElement103() ),
    ELEMENT_104( new ItemElement104() ),
    ELEMENT_105( new ItemElement105() ),
    ELEMENT_106( new ItemElement106() ),
    ELEMENT_107( new ItemElement107() ),
    ELEMENT_108( new ItemElement108() ),
    ELEMENT_109( new ItemElement109() ),
    ELEMENT_110( new ItemElement110() ),
    ELEMENT_111( new ItemElement111() ),
    ELEMENT_112( new ItemElement112() ),
    ELEMENT_113( new ItemElement113() ),
    ELEMENT_114( new ItemElement114() ),
    ELEMENT_115( new ItemElement115() ),
    ELEMENT_116( new ItemElement116() ),
    ELEMENT_117( new ItemElement117() ),
    ELEMENT_118( new ItemElement118() ),
    SEAGRASS( new ItemSeagrass() ),

    FIRE_CORAL( BlockType.CORAL.<BlockCoral>getBlock().setCoralColor( CoralColor.RED ).toItem() ),
    BRAIN_CORAL( BlockType.CORAL.<BlockCoral>getBlock().setCoralColor( CoralColor.PINK ).toItem() ),
    BUBBLE_CORAL( BlockType.CORAL.<BlockCoral>getBlock().setCoralColor( CoralColor.PURPLE ).toItem() ),
    TUBE_CORAL( BlockType.CORAL.<BlockCoral>getBlock().setCoralColor( CoralColor.BLUE ).toItem() ),
    HORN_CORAL( BlockType.CORAL.<BlockCoral>getBlock().setCoralColor( CoralColor.YELLOW ).toItem() ),

    DEAD_FIRE_CORAL( BlockType.CORAL.<BlockCoral>getBlock().setCoralColor( CoralColor.RED ).setDead( true ).toItem() ),
    DEAD_BRAIN_CORAL( BlockType.CORAL.<BlockCoral>getBlock().setCoralColor( CoralColor.PINK ).setDead( true ).toItem() ),
    DEAD_BUBBLE_CORAL( BlockType.CORAL.<BlockCoral>getBlock().setCoralColor( CoralColor.PURPLE ).setDead( true ).toItem() ),
    DEAD_TUBE_CORAL( BlockType.CORAL.<BlockCoral>getBlock().setCoralColor( CoralColor.BLUE ).setDead( true ).toItem() ),
    DEAD_HORN_CORAL( BlockType.CORAL.<BlockCoral>getBlock().setCoralColor( CoralColor.YELLOW ).setDead( true ).toItem() ),

    FIRE_CORAL_FAN( BlockType.CORAL_FAN.<BlockCoralFan>getBlock().setCoralColor( CoralColor.RED ).toItem() ),
    BRAIN_CORAL_FAN( BlockType.CORAL_FAN.<BlockCoralFan>getBlock().setCoralColor( CoralColor.PINK ).toItem() ),
    BUBBLE_CORAL_FAN( BlockType.CORAL_FAN.<BlockCoralFan>getBlock().setCoralColor( CoralColor.PURPLE ).toItem() ),
    TUBE_CORAL_FAN( BlockType.CORAL_FAN.<BlockCoralFan>getBlock().setCoralColor( CoralColor.BLUE ).toItem() ),
    HORN_CORAL_FAN( BlockType.CORAL_FAN.<BlockCoralFan>getBlock().setCoralColor( CoralColor.YELLOW ).toItem() ),

    DEAD_FIRE_CORAL_FAN( BlockType.CORAL_FAN_DEAD.<BlockCoralFanDead>getBlock().setCoralColor( CoralColor.RED ).toItem() ),
    DEAD_BRAIN_CORAL_FAN( BlockType.CORAL_FAN_DEAD.<BlockCoralFanDead>getBlock().setCoralColor( CoralColor.PINK ).toItem() ),
    DEAD_BUBBLE_CORAL_FAN( BlockType.CORAL_FAN_DEAD.<BlockCoralFanDead>getBlock().setCoralColor( CoralColor.PURPLE ).toItem() ),
    DEAD_TUBE_CORAL_FAN( BlockType.CORAL_FAN_DEAD.<BlockCoralFanDead>getBlock().setCoralColor( CoralColor.BLUE ).toItem() ),
    DEAD_HORN_CORAL_FAN( BlockType.CORAL_FAN_DEAD.<BlockCoralFanDead>getBlock().setCoralColor( CoralColor.YELLOW ).toItem() ),

    TUBE_CORAL_BLOCK( BlockType.CORAL_BLOCK.<BlockCoralBlock>getBlock().setCoralColor( CoralColor.BLUE ).toItem() ),
    BRAIN_CORAL_BLOCK( BlockType.CORAL_BLOCK.<BlockCoralBlock>getBlock().setCoralColor( CoralColor.PINK ).toItem() ),
    BUBBLE_CORAL_BLOCK( BlockType.CORAL_BLOCK.<BlockCoralBlock>getBlock().setCoralColor( CoralColor.PURPLE ).toItem() ),
    FIRE_CORAL_BLOCK( BlockType.CORAL_BLOCK.<BlockCoralBlock>getBlock().setCoralColor( CoralColor.RED ).toItem() ),
    HORN_CORAL_BLOCK( BlockType.CORAL_BLOCK.<BlockCoralBlock>getBlock().setCoralColor( CoralColor.YELLOW ).toItem() ),

    DEAD_TUBE_CORAL_BLOCK( BlockType.CORAL_BLOCK.<BlockCoralBlock>getBlock().setCoralColor( CoralColor.BLUE ).setDead( true ).toItem() ),
    DEAD_BRAIN_CORAL_BLOCK( BlockType.CORAL_BLOCK.<BlockCoralBlock>getBlock().setCoralColor( CoralColor.PINK ).setDead( true ).toItem() ),
    DEAD_BUBBLE_CORAL_BLOCK( BlockType.CORAL_BLOCK.<BlockCoralBlock>getBlock().setCoralColor( CoralColor.PURPLE ).setDead( true ).toItem() ),
    DEAD_FIRE_CORAL_BLOCK( BlockType.CORAL_BLOCK.<BlockCoralBlock>getBlock().setCoralColor( CoralColor.RED ).setDead( true ).toItem() ),
    DEAD_HORN_CORAL_BLOCK( BlockType.CORAL_BLOCK.<BlockCoralBlock>getBlock().setCoralColor( CoralColor.YELLOW ).setDead( true ).toItem() ),

    CORAL_FAN_HANG( new ItemCoralFanHang() ),
    CORAL_FAN_HANG2( new ItemCoralFanHang2() ),
    CORAL_FAN_HANG3( new ItemCoralFanHang3() ),
    KELP_BLOCK( new ItemKelpBlock() ),
    DRIED_KELP_BLOCK( new ItemDriedKelpBlock() ),
    ACACIA_BUTTON( new ItemAcaciaButton() ),
    BIRCH_BUTTON( new ItemBirchButton() ),
    DARK_OAK_BUTTON( new ItemDarkOakButton() ),
    JUNGLE_BUTTON( new ItemJungleButton() ),
    SPRUCE_BUTTON( new ItemSpruceButton() ),
    ACACIA_TRAPDOOR( new ItemAcaciaTrapdoor() ),
    BIRCH_TRAPDOOR( new ItemBirchTrapdoor() ),
    DARK_OAK_TRAPDOOR( new ItemDarkOakTrapdoor() ),
    JUNGLE_TRAPDOOR( new ItemJungleTrapdoor() ),
    SPRUCE_TRAPDOOR( new ItemSpruceTrapdoor() ),
    ACACIA_PRESSURE_PLATE( new ItemAcaciaPressurePlate() ),
    BIRCH_PRESSURE_PLATE( new ItemBirchPressurePlate() ),
    DARK_OAK_PRESSURE_PLATE( new ItemDarkOakPressurePlate() ),
    JUNGLE_PRESSUREP_PLATE( new ItemJunglePressurePlate() ),
    SPRUCE_PRESSURE_PLATE( new ItemSprucePressurePlate() ),
    CARVED_PUMPKIN( new ItemCarvedPumpkin() ),
    SEA_PICKLE( new ItemSeaPickle() ),
    CONDUIT( new ItemConduit() ),
    TURTLE_EGG( new ItemTurtleEgg() ),
    BUBBLE_COLUMN( new ItemBubbleColumn() ),
    BARRIER( new ItemBarrier() ),
    REAL_DOUBLE_END_STONE_BRICK_SLAB( new ItemRealDoubleEndStoneBrickSlab() ),
    BAMBOO( new ItemBamboo() ),
    BAMBOO_SAPLING( new ItemBambooSapling() ),
    SCAFFOLDING( new ItemScaffolding() ),
    REAL_DOUBLE_MOSSY_STONE_BRICK_SLAB( new ItemRealDoubleMossyStoneBrickSlab() ),

    SMOOTH_STONE_SLAB( BlockType.STONE_SLAB.<BlockStoneSlab>getBlock().setStoneSlabType( StoneSlabType.SMOOTH_STONE ).toItem() ),
    SANDSTONE_SLAB( BlockType.STONE_SLAB.<BlockStoneSlab>getBlock().setStoneSlabType( StoneSlabType.SANDSTONE ).toItem() ),
    WOOD_SLAB( BlockType.STONE_SLAB.<BlockStoneSlab>getBlock().setStoneSlabType( StoneSlabType.WOOD ).toItem() ),
    COBBLESTONE_SLAB( BlockType.STONE_SLAB.<BlockStoneSlab>getBlock().setStoneSlabType( StoneSlabType.COBBLESTONE ).toItem() ),
    BRICK_SLAB( BlockType.STONE_SLAB.<BlockStoneSlab>getBlock().setStoneSlabType( StoneSlabType.BRICK ).toItem() ),
    STONE_BRICK_SLAB( BlockType.STONE_SLAB.<BlockStoneSlab>getBlock().setStoneSlabType( StoneSlabType.STONE_BRICK ).toItem() ),
    QUARTZ_SLAB( BlockType.STONE_SLAB.<BlockStoneSlab>getBlock().setStoneSlabType( StoneSlabType.QUARTZ ).toItem() ),
    NETHER_BRICK_SLAB( BlockType.STONE_SLAB.<BlockStoneSlab>getBlock().setStoneSlabType( StoneSlabType.NETHER_BRICK ).toItem() ),

    RED_SANDSTONE_SLAB( BlockType.STONE_SLAB2.<BlockStoneSlab2>getBlock().setStoneSlabType( StoneSlab2Type.RED_SANDSTONE ).toItem() ),
    PURPUR_SLAB( BlockType.STONE_SLAB2.<BlockStoneSlab2>getBlock().setStoneSlabType( StoneSlab2Type.PURPUR ).toItem() ),
    PRISMARINE_ROUGH_SLAB( BlockType.STONE_SLAB2.<BlockStoneSlab2>getBlock().setStoneSlabType( StoneSlab2Type.PRISMARINE_ROUGH ).toItem() ),
    PRISMARINE_DARK_SLAB( BlockType.STONE_SLAB2.<BlockStoneSlab2>getBlock().setStoneSlabType( StoneSlab2Type.PRISMARINE_DARK ).toItem() ),
    PRISMARINE_BRICK_SLAB( BlockType.STONE_SLAB2.<BlockStoneSlab2>getBlock().setStoneSlabType( StoneSlab2Type.PRISMARINE_BRICK ).toItem() ),
    MOSSY_COBBLESTONE_SLAB( BlockType.STONE_SLAB2.<BlockStoneSlab2>getBlock().setStoneSlabType( StoneSlab2Type.MOSSY_COBBLESTONE ).toItem() ),
    SMOOTH_SANDSTONE_SLAB( BlockType.STONE_SLAB2.<BlockStoneSlab2>getBlock().setStoneSlabType( StoneSlab2Type.SMOOTH_SANDSTONE ).toItem() ),
    RED_NETHER_BRICK_SLAB( BlockType.STONE_SLAB2.<BlockStoneSlab2>getBlock().setStoneSlabType( StoneSlab2Type.RED_NETHER_BRICK ).toItem() ),

    END_STONE_BRICK_SLAB( BlockType.STONE_SLAB3.<BlockStoneSlab3>getBlock().setStoneSlabType( StoneSlab3Type.END_STONE_BRICK ).toItem() ),
    SMOOTH_RED_SANDSTONE_SLAB( BlockType.STONE_SLAB3.<BlockStoneSlab3>getBlock().setStoneSlabType( StoneSlab3Type.SMOOTH_RED_SANDSTONE ).toItem() ),
    POLISHED_ANDESITE_SLAB( BlockType.STONE_SLAB3.<BlockStoneSlab3>getBlock().setStoneSlabType( StoneSlab3Type.POLISHED_ANDESITE ).toItem() ),
    ANDESITE_SLAB( BlockType.STONE_SLAB3.<BlockStoneSlab3>getBlock().setStoneSlabType( StoneSlab3Type.ANDESITE ).toItem() ),
    DIORITE_SLAB( BlockType.STONE_SLAB3.<BlockStoneSlab3>getBlock().setStoneSlabType( StoneSlab3Type.DIORITE ).toItem() ),
    POLISHED_DIORITE_SLAB( BlockType.STONE_SLAB3.<BlockStoneSlab3>getBlock().setStoneSlabType( StoneSlab3Type.POLISHED_DIORITE ).toItem() ),
    GRANITE_SLAB( BlockType.STONE_SLAB3.<BlockStoneSlab3>getBlock().setStoneSlabType( StoneSlab3Type.GRANITE ).toItem() ),
    POLISHED_GRANITE_SLAB( BlockType.STONE_SLAB3.<BlockStoneSlab3>getBlock().setStoneSlabType( StoneSlab3Type.POLISHED_GRANITE ).toItem() ),

    MOSSY_STONE_BRICK_SLAB( BlockType.STONE_SLAB4.<BlockStoneSlab4>getBlock().setStoneSlabType( StoneSlab4Type.MOSSY_STONE_BRICK ).toItem() ),
    SMOOTH_QUARTZ_SLAB( BlockType.STONE_SLAB4.<BlockStoneSlab4>getBlock().setStoneSlabType( StoneSlab4Type.SMOOTH_QUARTZ ).toItem() ),
    STONE_SLAB( BlockType.STONE_SLAB4.<BlockStoneSlab4>getBlock().setStoneSlabType( StoneSlab4Type.STONE ).toItem() ),
    CUT_SANDSTONE_SLAB( BlockType.STONE_SLAB4.<BlockStoneSlab4>getBlock().setStoneSlabType( StoneSlab4Type.CUT_SANDSTONE ).toItem() ),
    CUT_RED_SANDSTONE_SLAB( BlockType.STONE_SLAB4.<BlockStoneSlab4>getBlock().setStoneSlabType( StoneSlab4Type.CUT_RED_SANDSTONE ).toItem() ),

    GRANITE_STAIRS( new ItemGraniteStairs() ),
    DIORITE_STAIRS( new ItemDioriteStairs() ),
    ANDESITE_STAIRS( new ItemAndesiteStairs() ),
    POLISHED_GRANITE_STAIRS( new ItemPolishedGraniteStairs() ),
    POLISHED_DIORITE_STAIRS( new ItemPolishedDioriteStairs() ),
    POLISHED_ANDESITE_STAIRS( new ItemPolishedAndesiteStairs() ),
    MOSSY_STONE_BRICK_STAIRS( new ItemMossyStoneBrickStairs() ),
    SMOOTH_RED_SANDSTONE_STAIRS( new ItemSmoothRedSandstoneStairs() ),
    SMOOTH_SANDSTONE_STAIRS( new ItemSmoothSandstoneStairs() ),
    END_BRICK_STAIRS( new ItemEndBrickStairs() ),
    MOSSY_COBBLESTONE_STAIRS( new ItemMossyCobblestoneStairs() ),
    NORMAL_STONE_STAIRS( new ItemNormalStoneStairs() ),
    SPRUCE_STANDING_SIGN( new ItemSpruceStandingSign() ),
    SPRUCE_WALL_SIGN( new ItemSpruceWallSign() ),
    SMOOTH_STONE( new ItemSmoothStone() ),
    RED_NETHER_BRICK_STAIRS( new ItemRedNetherBrickStairs() ),
    SMOOTH_QUARTZ_STAIRS( new ItemSmoothQuartzStairs() ),
    BIRCH_STANDING_SIGN( new ItemBirchStandingSign() ),
    BIRCH_WALL_SIGN( new ItemBirchWallSign() ),
    JUNGLE_STANDING_SIGN( new ItemJungleStandingSign() ),
    JUNGLE_WALL_SIGN( new ItemJungleWallSign() ),
    ACACIA_STANDING_SIGN( new ItemAcaciaStandingSign() ),
    ACACIA_WALL_SIGN( new ItemAcaciaWallSign() ),
    DARK_OAK_STANDING_SIGN( new ItemDarkOakStandingSign() ),
    DARK_OAK_WALL_SIGN( new ItemDarkOakWallSign() ),
    LECTERN( new ItemLectern() ),
    GRINDSTONE( new ItemGrindstone() ),
    BLAST_FURNACE( new ItemBlastFurnace() ),
    STONECUTTER_BLOCK( new ItemStonecutterBlock() ),
    SMOKER( new ItemSmoker() ),
    LIT_SMOKER( new ItemLitSmoker() ),
    CARTOGRAPGHY_TABLE( new ItemCartographyTable() ),
    FLETCHING_TABLE( new ItemFletchingTable() ),
    SMITHING_TABLE( new ItemSmithingTable() ),
    BARREL( new ItemBarrel() ),
    LOOM( new ItemLoom() ),
    BELL( new ItemBell() ),
    SWEETY_BERRY_BUSH( new ItemSweetBerryBush() ),
    LANTERN( new ItemLantern() ),
    CAMPFIRE_BLOCK( new ItemCampfireBlock() ),
    LAVA_CAULDRON( new ItemLavaCauldron() ),
    JIGSAW( new ItemJigsaw() ),

    OAK_WOOD( BlockType.WOOD.<BlockWood>getBlock().setWoodType( WoodType.OAK ).toItem() ),
    SPRUCE_WOOD( BlockType.WOOD.<BlockWood>getBlock().setWoodType( WoodType.SPRUCE ).toItem() ),
    BIRCH_WOOD( BlockType.WOOD.<BlockWood>getBlock().setWoodType( WoodType.BIRCH ).toItem() ),
    JUNGLE_WOOD( BlockType.WOOD.<BlockWood>getBlock().setWoodType( WoodType.JUNGLE ).toItem() ),
    ACACIA_WOOD( BlockType.WOOD.<BlockWood>getBlock().setWoodType( WoodType.ACACIA ).toItem() ),
    DARK_OAK_WOOD( BlockType.WOOD.<BlockWood>getBlock().setWoodType( WoodType.DARK_OAK ).toItem() ),

    STRIPPED_OAK_WOOD( BlockType.WOOD.<BlockWood>getBlock().setWoodType( WoodType.OAK ).setStripped( true ).toItem() ),
    STRIPPED_SPRUCE_WOOD( BlockType.WOOD.<BlockWood>getBlock().setWoodType( WoodType.SPRUCE ).setStripped( true ).toItem() ),
    STRIPPED_BIRCH_WOOD( BlockType.WOOD.<BlockWood>getBlock().setWoodType( WoodType.BIRCH ).setStripped( true ).toItem() ),
    STRIPPED_JUNGLE_WOOD( BlockType.WOOD.<BlockWood>getBlock().setWoodType( WoodType.JUNGLE ).setStripped( true ).toItem() ),
    STRIPPED_ACACIA_WOOD( BlockType.WOOD.<BlockWood>getBlock().setWoodType( WoodType.ACACIA ).setStripped( true ).toItem() ),
    STRIPPED_DARK_OAK_WOOD( BlockType.WOOD.<BlockWood>getBlock().setWoodType( WoodType.DARK_OAK ).setStripped( true ).toItem() ),

    COMPOSTER( new ItemComposter() ),
    LIT_BLAST_FURNACE( new ItemLitBlastFurnace() ),
    LIGHT_BLOCK( new ItemLightBlock() ),
    WITHER_ROSE( new ItemWitherRose() ),
    STICKYPISTONARMCOLLISION( new ItemStickypistonarmcollision() ),
    BEE_NEST( new ItemBeeNest() ),
    BEEHIVE( new ItemBeehive() ),
    HONEY_BLOCK( new ItemHoneyBlock() ),
    HONEYCOMB_BLOCK( new ItemHoneycomBlock() ),
    LODESTONE( new ItemLodestone() ),
    CRIMSON_ROOTS( new ItemCrimsonRoots() ),
    WARPED_ROOTS( new ItemWarpedRoots() ),
    CRIMSON_STEM( new ItemCrimsonStem() ),
    WARPED_STEM( new ItemWarpedStem() ),
    WARPED_WART_BLOCK( new ItemWarpedWartBlock() ),
    CRIMSON_FUNGUS( new ItemCrimsonFungus() ),
    SHROOMLIGHT( new ItemShroomlight() ),
    WEEPING_VINES( new ItemWeepingVines() ),
    CRIMSON_NYLIUM( new ItemCrimsonNylium() ),
    WARPED_NYLIUM( new ItemWarpedNylium() ),
    BASALT( new ItemBasalt() ),
    POLISHED_BASALT( new ItemPolishedBasalt() ),
    SOUL_SOIL( new ItemSoulSoil() ),
    SOUL_FIRE( new ItemSoulFire() ),
    NETHER_SPROCUTS( new ItemNetherSproutsBlock() ),
    TARGET( new ItemTarget() ),
    STRIPPED_CRIMSON_STEM( new ItemStrippedCrimsonStem() ),
    STRIPPED_WARPED_STEM( new ItemStrippedWarpedStem() ),
    CRIMSON_PLANKS( new ItemCrimsonPlanks() ),
    WARPED_PLANKS( new ItemWarpedPlanks() ),
    CRIMSON_DOOR_DOOR( new ItemCrimsonDoorBlock() ),
    WARPED_DOOR_DOOR( new ItemWarpedDoorBlock() ),
    CRIMSON_TRAPDOOR( new ItemCrimsonTrapdoor() ),
    WARPED_TRAPDOOR( new ItemWarpedTrapdoor() ),
    CRIMSON_STANDING_SIGN( new ItemCrimsonStandingSign() ),
    WARPED_STANDING_SIGN( new ItemWarpedStandingSign() ),
    CRIMSON_WALL_SIGN( new ItemCrimsonWallSign() ),
    WARPED_WALL_SIGN( new ItemWarpedWallSign() ),
    CRIMSON_STAIRS( new ItemCrimsonStairs() ),
    WARPED_STAIRS( new ItemWarpedStairs() ),
    CRIMSON_FENCE( new ItemCrimsonFence() ),
    WARPED_FENCE( new ItemWarpedFence() ),
    CRIMSON_FENCE_GATE( new ItemCrimsonFenceGate() ),
    WARPED_FENCE_GATE( new ItemWarpedFenceGate() ),
    CRIMSON_BUTTON( new ItemCrimsonButton() ),
    WARPED_BUTTON( new ItemWarpedButton() ),
    CRIMSON_PRESSURE_PLATE( new ItemCrimsonPressurePlate() ),
    WARPED_PRESSURE_PLATE( new ItemWarpedPressurePlate() ),
    CRIMSON_SLAB( new ItemCrimsonSlab() ),
    WARPED_SLAB( new ItemWarpedSlab() ),
    CRIMSON_DOUBLE_SLAB( new ItemCrimsonDoubleSlab() ),
    WARPED_DOUBLE_SLAB( new ItemWarpedDoubleSlab() ),
    SOUL_TORCH( new ItemSoulTorch() ),
    SOUL_LANTERN( new ItemSoulLantern() ),
    NETHERITE_BLOCK( new ItemNetheriteBlock() ),
    ANCIENT_DEBRIS( new ItemAncientDebris() ),
    RESPAWN_ANCHOR( new ItemRespawnAnchor() ),
    BLACKSTONE( new ItemBlackstone() ),
    POLISHED_BLACKSTONE_BRICKS( new ItemPolishedBlackstoneBricks() ),
    POLISHED_BLACKSTONE_BRICK_STAIRS( new ItemPolishedBlackstoneBrickStairs() ),
    BLACKSTONE_STAIRS( new ItemBlackstoneStairs() ),
    BLACKSTONE_WALL( new ItemBlackstoneWall() ),
    POLISHED_BLACKSTONE_BRICK_WALL( new ItemPolishedBlackstoneBrickWall() ),
    CHISELED_POLISHED_BLACKSTONE( new ItemChiseledPolishedBlackstone() ),
    CRACKED_POLISHED_BLACKSTONE_BRICKS( new ItemCrackedPolishedBlackstoneBricks() ),
    GLIDED_BLACKSTONE( new ItemGlidedBlackstone() ),
    BLACKSTONE_SLAB( new ItemBlackstoneSlab() ),
    BLACKSTONE_DOUBLE_SLAB( new ItemBlackstoneDoubleSlab() ),
    POLISHED_BLACKSTONE_BRICK_SLAB( new ItemPolishedBlackstoneBrickSlab() ),
    POLISHED_BLACKSTONE_BRICK_DOUBLE_SLAB( new ItemPolishedBlackstoneBrickDoubleSlab() ),
    CHAIN_BLOCK( new ItemChainBlock() ),
    TWISTING_VINES( new ItemTwistingVines() ),
    NETHER_GOLD_ORE( new ItemNetherGoldOre() ),
    CRYING_OBSIDIAN( new ItemCryingObsidian() ),
    SOUL_CAMPFIRE_BLOCK( new ItemSoulCampfireBlock() ),
    POLISHED_BLACKSTONE( new ItemPolishedBlackstone() ),
    POLISHED_BLACKSTONE_STAIRS( new ItemPolishedBlackstoneStairs() ),
    POLISHED_BLACKSTONE_SLAB( new ItemPolishedBlackstoneSlab() ),
    POLISHED_BLACKSTONE_DOUBLE_SLAB( new ItemPolishedBlackstoneDoubleSlab() ),
    POLISHED_BLACKSTONE_PRESSURE_PLATE( new ItemPolishedBlackstonePressurePlate() ),
    POLISHED_BLACKSTONE_BUTTON( new ItemPolishedBlackstoneButton() ),
    POLISHED_BLACKSTONE_WALL( new ItemPolishedBlackstoneWall() ),
    WARPED_HYPHAE( new ItemWarpedHyphae() ),
    CRIMSON_HYPHAE( new ItemCrimsonHyphae() ),
    STRIPPED_CRIMSON_HYPHAE( new ItemStrippedCrimsonHyphae() ),
    STRIPPED_WARPED_HYPHAE( new ItemStrippedWarpedHyphae() ),
    CHISELED_NETHER_BRICKS( new ItemChiseledNetherBricks() ),
    CRACKED_NETHER_BRICKS( new ItemCrackedNetherBricks() ),
    QUARTZ_BRICKS( new ItemQuartzBricks() ),
    GLASS_PANE( new ItemGlassPane() ),
    IRON_SHOVEL( new ItemIronShovel() ),
    IRON_PICKAXE( new ItemIronPickaxe() ),
    IRON_AXE( new ItemIronAxe() ),
    FLINT_AND_STEEL( new ItemFlintAndSteel() ),
    APPLE( new ItemApple() ),
    BOW( new ItemBow() ),
    ARROW( new ItemArrow() ),
    COAL( new ItemCoal() ),
    DIAMOND( new ItemDiamond() ),
    IRON_INGOT( new ItemIronIngot() ),
    GOLD_INGOT( new ItemGoldIngot() ),
    IRON_SWORD( new ItemIronSword() ),
    WOODEN_SWORD( new ItemWoodenSword() ),
    WOODEN_SHOVEL( new ItemWoodenShovel() ),
    WOODEN_PICKAXE( new ItemWoodenPickaxe() ),
    WOODEN_AXE( new ItemWoodenAxe() ),
    STONE_SWORD( new ItemStoneSword() ),
    STONE_SHOVEL( new ItemStoneShovel() ),
    STONE_PICKAXE( new ItemStonePickaxe() ),
    STONE_AXE( new ItemStoneAxe() ),
    DIAMOND_SWORD( new ItemDiamondSword() ),
    DIAMOND_SHOVEL( new ItemDiamondShovel() ),
    DIAMOND_PICKAXE( new ItemDiamondPickaxe() ),
    DIAMOND_AXE( new ItemDiamondAxe() ),
    STICK( new ItemStick() ),
    BOWL( new ItemBowl() ),
    MUSHROOM_STEW( new ItemMushroomStew() ),
    GOLDEN_SWORD( new ItemGoldenSword() ),
    GOLDEN_SHOVEL( new ItemGoldenShovel() ),
    GOLDEN_PICKAXE( new ItemGoldenPickaxe() ),
    GOLDEN_AXE( new ItemGoldenAxe() ),
    STRING( new ItemString() ),
    FEATHER( new ItemFeather() ),
    GUNPOWDER( new ItemGunpowder() ),
    WOODEN_HOE( new ItemWoodenHoe() ),
    STONE_HOE( new ItemStoneHoe() ),
    IRON_HOE( new ItemIronHoe() ),
    DIAMOND_HOE( new ItemDiamondHoe() ),
    GOLDEN_HOE( new ItemGoldenHoe() ),
    WHEAT_SEEDS( new ItemWheatSeeds() ),
    WHEAT( new ItemWheat() ),
    BREAD( new ItemBread() ),
    LEATHER_HELMENT( new ItemLeatherHelmet() ),
    LEATHER_CHESTPLATE( new ItemLeatherChestplate() ),
    LEATHER_LEGGINGS( new ItemLeatherLeggings() ),
    LEATHER_BOOTS( new ItemLeatherBoots() ),
    CHAIN_HELMET( new ItemChainHelmet() ),
    CHAIN_CHESTPLATE( new ItemChainChestplate() ),
    CHAIN_LEGGINGS( new ItemChainLeggings() ),
    CHAIN_BOOTS( new ItemChainBoots() ),
    IRON_HELMET( new ItemIronHelmet() ),
    IRON_CHESTPLATE( new ItemIronChestplate() ),
    IRON_LEGGINGS( new ItemIronLeggings() ),
    IRON_BOOTS( new ItemIronBoots() ),
    DIAMOND_HELMET( new ItemDiamondHelmet() ),
    DIAMOND_CHESTPLATE( new ItemDiamondChestplate() ),
    DIAMOND_LEGGINGS( new ItemDiamondLeggings() ),
    DIAMOND_BOOTS( new ItemDiamondBoots() ),
    GOLDEN_HELMET( new ItemGoldenHelmet() ),
    GOLDEN_CHESTPLATE( new ItemGoldenChestplate() ),
    GOLDEN_LEGGINGS( new ItemGoldenLeggings() ),
    GOLDEN_BOOTS( new ItemGoldenBoots() ),
    FLINT( new ItemFlint() ),
    PROKCHOP( new ItemPorkchop() ),
    COOKED_PORKCHOP( new ItemCookedPorkchop() ),
    PAINTING( new ItemPainting() ),
    GOLDEN_APPLE( new ItemGoldenApple() ),
    SIGN( new ItemOakSign() ),
    WOODEN_DOOR( new ItemOakDoor() ),
    BUCKET( new ItemBucket() ),
    MINECART( new ItemMinecart() ),
    SADDLE( new ItemSaddle() ),
    IRON_DOOR( new ItemIronDoor() ),
    REDSTONE( new ItemRedstone() ),
    SNOWBALL( new ItemSnowball() ),
    BOAT( new ItemBoat() ),
    LEATHER( new ItemLeather() ),
    KELP( new ItemKelp() ),
    BRICK( new ItemBrick() ),
    CLAY_BALL( new ItemClayBall() ),
    REEDS( new ItemReeds() ),
    PAPER( new ItemPaper() ),
    BOOK( new ItemBook() ),
    SLIME_BALL( new ItemSlimeBall() ),
    CHEST_MINECART( new ItemChestMinecart() ),
    EGG( new ItemEgg() ),
    COMPASS( new ItemCompass() ),
    FISHING_ROD( new ItemFishingRod() ),
    CLOCK( new ItemClock() ),
    GLOWSTONE_DUST( new ItemGlowstoneDust() ),
    RAW_COD( new ItemCod() ),
    COOKED_COD( new ItemCookedCod() ),
    DYE( new ItemDye() ),
    BONE( new ItemBone() ),
    SUGAR( new ItemSugar() ),
    CAKE( new ItemCake() ),
    BED( new ItemBed() ),
    REPEATER( new ItemRepeater() ),
    COOKIE( new ItemCookie() ),
    MAP( new ItemFilledMap() ),
    SHEARS( new ItemShears() ),
    MELON( new ItemMelonSlice() ),
    PUMPKIN_SEEDS( new ItemPumpkinSeeds() ),
    MELON_SEEDS( new ItemMelonSeeds() ),
    BEEF( new ItemBeef() ),
    COOKED_BEEF( new ItemCookedBeef() ),
    CHICKEN( new ItemChicken() ),
    COOKED_CHICKEN( new ItemCookedChicken() ),
    ROTTEN_FLESH( new ItemRottenFlesh() ),
    ENDER_PEARL( new ItemEnderPearl() ),
    BLAZE_ROD( new ItemBlazeRod() ),
    GHAST_TEAR( new ItemGhastTear() ),
    GOLD_NUGGET( new ItemGoldNugget() ),
    NETHER_WART( new ItemNetherWart() ),
    POTION( new ItemPotion() ),
    GLASS_BOTTLE( new ItemGlassBottle() ),
    SPIDER_EYE( new ItemSpiderEye() ),
    FERMENTED_SPIDER_EYE( new ItemFermentedSpiderEye() ),
    BLAZE_POWDER( new ItemBlazePowder() ),
    MAGMA_CREAM( new ItemMagmaCream() ),
    BREWING_STAND( new ItemBrewingStand() ),
    CAULDRON( new ItemCauldron() ),
    ENDER_EYE( new ItemEnderEye() ),
    SPECKLED_MELON( new ItemGlisteringMelonSlice() ),
    SPAWN_EGG( new ItemSpawnEgg() ),
    EXPERIENCE_BOTTLE( new ItemExperienceBottle() ),
    FIREBALL( new ItemFireCharge() ),
    WRITEABLE_BOOK( new ItemWriteableBook() ),
    WRITTEN_BOOK( new ItemWrittenBook() ),
    EMERALD( new ItemEmerald() ),
    FRAME( new ItemFrame() ),
    FLOWER_POT( new ItemFlowerPot() ),
    CARROT( new ItemCarrot() ),
    POTATO( new ItemPotato() ),
    BAKED_POTATO( new ItemBakedPotato() ),
    POISONOUS_POTATO( new ItemPoisonousPotato() ),
    EMPTY_MAP( new ItemEmptyMap() ),
    GOLDEN_CARROT( new ItemGoldenCarrot() ),
    SKULL( new ItemSkull() ),
    CARROT_ON_STICK( new ItemCarrotOnAStick() ),
    NETHER_START( new ItemNetherStar() ),
    PUMPKIN_PIE( new ItemPumpkinPie() ),
    FIREWORK_ROCKET( new ItemFireworkRocket() ),
    FIREWORK_SCHARGE( new ItemFireworkStar() ),
    ENCHANTED_BOOK( new ItemEnchantedBook() ),
    COMPARATOR( new ItemComparator() ),
    NETHERBRICK( new ItemNetherbrick() ),
    QUARTZ( new ItemQuartz() ),
    TNT_MINECART( new ItemTntMinecart() ),
    HOPPER_MINECART( new ItemHopperMinecart() ),
    PRISMARINE_SHARD( new ItemPrismarineShard() ),
    HOPPER( new ItemHopper() ),
    RABBIT( new ItemRabbit() ),
    COOKED_RABBIT( new ItemCookedRabbit() ),
    RABBIT_STEW( new ItemRabbitStew() ),
    RABBIT_FOOT( new ItemRabbitFoot() ),
    RABBIT_HIDE( new ItemRabbitHide() ),
    HORSE_ARMOR_LEATHER( new ItemLeatherHorseArmor() ),
    HORSE_ARMOR_IRON( new ItemIronHorseArmor() ),
    HORSE_ARMOR_GOLD( new ItemGoldenHorseArmor() ),
    HORSE_ARMOR_DIAMOND( new ItemDiamondHorseArmor() ),
    LEAD( new ItemLead() ),
    NAMETAG( new ItemNameTag() ),
    PRISMARINE_CRYSTALS( new ItemPrismarineCrystals() ),
    RAW_MUTTON( new ItemMutton() ),
    COOKED_MUTTON( new ItemCookedMutton() ),
    ARMOR_STAND( new ItemArmorStand() ),
    END_CRYSTAL( new ItemEndCrystal() ),
    SPRUCE_DOOR( new ItemSpruceDoor() ),
    BIRCH_DOOR( new ItemBirchDoor() ),
    JUNGLE_DOOR( new ItemJungleDoor() ),
    ACACIA_DOOR( new ItemAcaciaDoor() ),
    DARK_OAK_DOOR( new ItemDarkOakDoor() ),
    CHORUS_FRUIT( new ItemChorusFruit() ),
    CHORUS_FRUIT_POPPED( new ItemPoppedChorusFruit() ),
    BANNER_PATTERN( new ItemBannerPattern() ),
    DRAGON_BREATH( new ItemDragonBreath() ),
    SPLASH_POTION( new ItemSplashPotion() ),
    LINGERING_POTION( new ItemLingeringPotion() ),
    SPARKLER( new ItemSparkler() ),
    COMMAND_BLOCK_MINECART( new ItemCommandBlockMinecart() ),
    ELYTRA( new ItemElytra() ),
    SHULKER_SHELL( new ItemShulkerShell() ),
    BANNER( new ItemBanner() ),
    MEDICINE( new ItemMedicine() ),
    BALLON( new ItemBalloon() ),
    SUPER_FERTILIZER( new ItemRapidFertilizer() ),
    TOTEM( new ItemTotemOfUndying() ),
    BLEACH( new ItemBleach() ),
    IRON_NUGGET( new ItemIronNugget() ),
    ICE_BOMB( new ItemIceBomb() ),
    TRIDENT( new ItemTrident() ),
    BEETROOT( new ItemBeetroot() ),
    BEETROOT_SEEDS( new ItemBeetrootSeeds() ),
    BEETROOT_SOUP( new ItemBeetrootSoup() ),
    SALMON( new ItemSalmon() ),
    CLOWNFISH( new ItemTropicalFish() ),
    PUFFERFISH( new ItemPufferfish() ),
    COOKED_SALMON( new ItemCookedSalmon() ),
    DRIED_KELP( new ItemDriedKelp() ),
    NAUTILUS_SHELL( new ItemNautilusShell() ),
    ENCHANTED_APPLE( new ItemEnchantedGoldenApple() ),
    HEART_OF_THE_SEA( new ItemHeartOfTheSea() ),
    TURTLE_SHELL_PIECE( new ItemScute() ),
    TURTLE_HELMET( new ItemTurtleHelmet() ),
    PHANTOM_MEMBRANE( new ItemPhantomMembrane() ),
    CROSSBOW( new ItemCrossbow() ),
    SPRUCE_SIGN( new ItemSpruceSign() ),
    BIRCH_SIGN( new ItemBirchSign() ),
    JUNGLE_SIGN( new ItemJungleSign() ),
    ACACIA_SIGN( new ItemAcaciaSign() ),
    DARK_OAK_SIGN( new ItemDarkOakSign() ),
    SWEET_BERRIES( new ItemSweetBerries() ),
    CAMERA( new ItemCamera() ),
    COMPOUND( new ItemCompund() ),
    RECORD_13( new ItemMusicDisc13() ),
    RECORD_CAT( new ItemMusicDiscCat() ),
    RECORD_BLOCKS( new ItemMusicDiscBlocks() ),
    RECORD_CHIRP( new ItemMusicDiscChirp() ),
    RECORD_FAR( new ItemMusicDiscFar() ),
    RECORD_MALL( new ItemMusicDiscMall() ),
    RECORD_MELLOHI( new ItemMusicDiscMellohi() ),
    RECORD_STAL( new ItemMusicDiscStal() ),
    RECORD_STARD( new ItemMusicDiscStrad() ),
    RECORD_WARD( new ItemMusicDiscWard() ),
    RECORD_11( new ItemMusicDisc11() ),
    RECORD_WAIT( new ItemMusicDiscWait() ),
    SHIELD( new ItemShield() ),
    CAMPFIRE( new ItemCampfire() ),
    SUSPICIOUS_STEW( new ItemSuspiciousStew() ),
    HONEYCOMB( new ItemHoneycomb() ),
    HONEY_BOTTLE( new ItemHoneyBottle() ),
    LODESTONECOMPASS( new ItemLodestoneCompass() ),
    NETHERITE_INGOT( new ItemNetheriteIngot() ),
    NETHERITE_SWORD( new ItemNetheriteSword() ),
    NETHERITE_SHOVEL( new ItemNetheriteShovel() ),
    NETHERITE_PICKAXE( new ItemNetheritePickaxe() ),
    NETHERITE_AXE( new ItemNetheriteAxe() ),
    NETHERITE_HOE( new ItemNetheriteHoe() ),
    NETHERITE_HELMET( new ItemNetheriteHelmet() ),
    NETHERITE_CHESTPLATE( new ItemNetheriteChestplate() ),
    NETHERITE_LEGGINGS( new ItemNetheriteLeggings() ),
    NETHERITE_BOOTS( new ItemNetheriteBoots() ),
    NETHERITE_SCRAP( new ItemNetheriteScrap() ),
    CRIMSON_SIGN( new ItemCrimsonSign() ),
    WARPED_SIGN( new ItemWarpedSign() ),
    CRIMSON_DOOR( new ItemCrimsonDoor() ),
    WARPED_DOOR( new ItemWarpedDoor() ),
    WARPED_FUNGUS_ON_A_STICK( new ItemWarpedFungusOnAStick() ),
    CHAIN( new ItemChain() ),
    RECORD_PIGSTEP( new ItemMusicDiscPigstep() ),
    NETHER_SPROUTS( new ItemNetherSproutsBlock() ),
    SOUL_CAMPFIRE( new ItemSoulCampfire() ),
    WARPED_FUNGUS( new ItemWarpedFungus() ),
    NETHER_SQROUTS( new ItemNetherSprouts() ),
    BORDURER_INDENTED_BANNER_PATTERN( new ItemBordureIndentedBannerPattern() ),
    PUFFERFISH_SPAWN_EGG( new ItemPufferfishSpawnEgg() ),
    BAT_SPAWN_EGG( new ItemBatSpawnEgg() ),
    DONKEY_SPAWN_EGG( new ItemDonkeySpawnEgg() ),
    CAVE_SPIDER_SPAWN_EGG( new ItemCaveSpiderSpawnEgg() ),
    PIGLIN_BRUTE_SPAWN_EGG( new ItemPiglinBruteSpawnEgg() ),
    ZOGLIN_SPAWN_EGG( new ItemZoglinSpawnEgg() ),
    PIGLIN_SPAWN_EGG( new ItemPiglinSpawnEgg() ),
    HOGLIN_SPAWN_EGG( new ItemHoglinSpawnEgg() ),
    WANDERING_TRADER_SPAWN_EGG( new ItemWanderingTraderSpawnEgg() ),
    PILLAGER_SPAWN_EGG( new ItemPillagerSpawnEgg() ),
    PHANTOM_SPAWN_EGG( new ItemPhantomSpawnEgg() ),
    DROWNED_SPAWN_EGG( new ItemDrownedSpawnEgg() ),
    TROPICAL_FISH_SPAWN_EGG( new ItemTropicalFishSpawnEgg() ),
    VINDICATOR_SPAWN_EGG( new ItemVindicatorSpawnEgg() ),
    LLAMA_SPAWN_EGG( new ItemLlamaSpawnEgg() ),
    SKELETON_HORSE_SPAWN_EGG( new ItemSkeletonHorseSpawnEgg() ),
    BLAZE_SPAWN_EGG( new ItemBlazeSpawnEgg() ),
    VEX_SPAWN_EGG( new ItemVexSpawnEgg() ),
    SQUID_SPAWN_EGG( new ItemSquidSpawnEgg() ),
    ORANGE_DYE( new ItemOrangeDye() ),
    VILLAGER_SPAWN_EGG( new ItemVillagerSpawnEgg() ),
    ZOMBIE_SPAWN_EGG( new ItemZombieSpawnEgg() ),
    TURTLE_SPAWN_EGG( new ItemTurtleSpawnEgg() ),
    SLIME_SPAWN_EGG( new ItemSlimeSpawnEgg() ),
    SILVERFISH_SPAWN_EGG( new ItemSilverfishSpawnEgg() ),
    GHAST_SPAWN_EGG( new ItemGhastSpawnEgg() ),
    MOOSHROOM_SPAWN_EGG( new ItemMooshroomSpawnEgg() ),
    WOLF_SPAWN_EGG( new ItemWolfSpawnEgg() ),
    CHICKEN_SPAWN_EGG( new ItemChickenSpawnEgg() ),
    DARK_OAK_BOAT( new ItemDarkOakBoat() ),
    WITHER_SKELETON_SPAWN_EGG( new ItemWitherSkeletonSpawnEgg() ),
    STRAY_SPAWN_EGG( new ItemStraySpawnEgg() ),
    FIELD_MASONED_BANNER_PATTERN( new ItemFieldMasonedBannerPattern() ),
    PIGLIN_BANNER_PATTERN( new ItemPiglinBannerPattern() ),
    COD_BUCKET( new ItemCodBucket() ),
    ENDERMITE_SPAWN_EGG( new ItemEndermiteSpawnEgg() ),
    PARROT_SPAWN_EGG( new ItemParrotSpawnEgg() ),
    COCOA_BEANS( new ItemCocoaBeans() ),
    BLUE_DYE( new ItemBlueDye() ),
    CREEPER_BANNER_PATTERN( new ItemCreeperBannerPattern() ),
    EVOKER_SPAWN_EGG( new ItemEvokerSpawnEgg() ),
    RED_DYE( new ItemRedDye() ),
    CREEPER_SPAWN_EGG( new ItemCreeperSpawnEgg() ),
    GRAY_DYE( new ItemGrayDye() ),
    CHARCOAL( new ItemCharcoal() ),
    WHITE_DYE( new ItemWhiteDye() ),
    SHULKER_SPAWN_EGG( new ItemShulkerSpawnEgg() ),
    PUFFERFISH_BUCKET( new ItemPufferfishBucket() ),
    ELDER_GUARDIAN_SPAWN_EGG( new ItemElderGuardianSpawnEgg() ),
    WATER_BUCKET( new ItemWaterBucket() ),
    ZOMBIE_VILLAGER_SPAWN_EGG( new ItemZombieVillagerSpawnEgg() ),
    SKULL_BANNER_PATTERN( new ItemSkullBannerPattern() ),
    WITCH_SPAWN_EGG( new ItemWitchSpawnEgg() ),
    PANDA_SPAWN_EGG( new ItemPandaSpawnEgg() ),
    OCELOT_SPAWN_EGG( new ItemOcelotSpawnEgg() ),
    POLAR_BEAR_SPAWN_EGG( new ItemPolarBearSpawnEgg() ),
    SALMON_BUCKET( new ItemSalmonBucket() ),
    COW_SPAWN_EGG( new ItemCowSpawnEgg() ),
    LIGHT_BLUE_DYE( new ItemLightBlueDye() ),
    ENDERMAN_SPAWN_EGG( new ItemEndermanSpawnEgg() ),
    CAT_SPAWN_EGG( new ItemCatSpawnEgg() ),
    LIME_DYE( new ItemLimeDye() ),
    LAVA_BUCKET( new ItemLavaBucket() ),
    HUSK_SPAWN_SPAWN_EGG( new ItemHuskSpawnEgg() ),
    OAK_BOAT( new ItemOakBoat() ),
    DOLPHIN_SPAWN_EGG( new ItemDolphinSpawnEgg() ),
    HORSE_SPAWN_EGG( new ItemHorseSpawnEgg() ),
    MILK_BUCKET( new ItemMilkBucket() ),
    JUNGLE_BOAT( new ItemJungleBoat() ),
    MAGMA_CUBE_SPAWN_EGG( new ItemMagmaCubeSpawnEgg() ),
    BEE_SPAWN_EGG( new ItemBeeSpawnEgg() ),
    ACACIA_BOAT( new ItemAcaciaBoat() ),
    SPIDER_SPAWN_EGG( new ItemSpiderSpawnEgg() ),
    ZOMBIE_PIGMAN_SPAWN_EGG( new ItemZombiePigmanSpawnEgg() ),
    SHEEP_SPAWN_EGG( new ItemSheepSpawnEgg() ),
    SKELETON_SPAWN_EGG( new ItemSkeletonSpawnEgg() ),
    BLACK_DYE( new ItemBlackDye() ),
    FOX_SPAWN_EGG( new ItemFoxSpawnEgg() ),
    SALMON_SPAWN_EGG( new ItemSalmonSpawnEgg() ),
    MAGENTA_DYE( new ItemMagentaDye() ),
    MULE_SPAWN_EGG( new ItemMuleSpawnEgg() ),
    GREEN_DYE( new ItemGreenDye() ),
    BROWN_DYE( new ItemBrownDye() ),
    PINK_DYE( new ItemPinkDye() ),
    INC_SAC( new ItemIncSac() ),
    YELLOW_DYE( new ItemYellowDye() ),
    LAPIS_LAZULI( new ItemLapisLazuli() ),
    RAVAGER_SPAWN_EGG( new ItemRavagerSpawnEgg() ),
    TROPICAL_FISH_BUCKET( new ItemTropicalFishBucket() ),
    FLOWER_BANNER_PATTERN( new ItemFlowerBannerPattern() ),
    NPC_SPAWN_EGG( new ItemNPCSpawnEgg() ),
    BONE_MEAL( new ItemBoneMeal() ),
    BIRCH_BOAT( new ItemBirchBoat() ),
    UNKNOWN( new ItemUnknown() ),
    AGENT_SPAWN_EGG( new ItemAgentSpawnEgg() ),
    LIGHT_GRAY_DYE( new ItemLightGrayDye() ),
    SPRUCE_BOAT( new ItemSpruceBoat() ),
    COD_SPAWN_EGG( new ItemCodSpawnEgg() ),
    GUARDIAN_SPAWN_EGG( new ItemGuardianSpawnEgg() ),
    PIG_SPAWN_EGG( new ItemPigSpawnEgg() ),
    ZOMBIE_HORSE_SPAWN_EGG( new ItemZombieHorseSpawnEgg() ),
    RABBIT_SPAWN_EGG( new ItemRabbitSpawnEgg() ),
    STRIDER_SPAWN_EGG( new ItemStriderSpawnEgg() ),
    ITEM_WOODEN_DOOR( new ItemWoodenDoorBlock() ),
    CYAN_DYE( new ItemCyanDye() ),
    PURPLE_DYE( new ItemPurpleDye() ),
    MOJANG_BANNER_PATTERN( new ItemMojangBannerPattern() ),

    DEEPSLATE_BRICK_WALL( new ItemDeepslateBrickWall() ),
    WEATHERED_CUT_COPPER_SLAB( new ItemWeatheredCutCopperSlab() ),
    GLOW_FRAME( new ItemGlowFrame() ),
    HANGING_ROOTS( new ItemHangingRoots() ),
    WAXED_EXPOSED_CUT_COPPER_STAIRS( new ItemWaxedExposedCutCopperStairs() ),
    POLISHED_DEEPSLATE_SLAB( new ItemPolishedDeepslateSlab() ),
    COBBLED_DEEPSLATE( new ItemCobbledDeepslate() ),
    DEEPSLATE_BRICK_DOUBLE_SLAB( new ItemDeepslateBrickDoubleSlab() ),
    DRIPSTONE_BLOCK( new ItemDripstoneBlock() ),
    CALCITE( new ItemCalcite() ),
    RAW_GOLD_BLOCK( new ItemRawGoldBlock() ),
    POWDER_SNOW_BUCKET( new ItemPowderSnowBucket() ),
    WAXED_CUT_COPPER_SLAB( new ItemWaxedCutCopperSlab() ),
    LIT_DEEPSLATE_REDSTONE_ORE( new ItemLitDeepslateRedstoneOre() ),
    CUT_COPPER_SLAB( new ItemCutCopperSlab() ),
    MOSS_BLOCK( new ItemMossBlock() ),
    RAW_GOLD( new ItemRawGold() ),
    DEEPSLATE_TILES( new ItemDeepslateTiles() ),
    DEEPSLATE_TILE_STAIRS( new ItemDeepslateTileStairs() ),
    WAXED_EXPOSED_CUT_COPPER( new ItemWaxedExposedCutCopper() ),
    WAXED_CUT_COPPER( new ItemWaxedCutCopper() ),
    EXPOSED_CUT_COPPER( new ItemExposedCutCopper() ),
    CAVE_VINES( new ItemCaveVines() ),
    WAXED_WEATHERED_DOUBLE_CUT_COPPER_SLAB( new ItemWaxedWeatheredDoubleCutCopperSlab() ),
    CUT_COPPER( new ItemCutCopper() ),
    AMETHYST_BLOCK( new ItemAmethystBlock() ),
    SCULK_SENSOR( new ItemSculkSensor() ),
    BIG_DRIPLEAF( new ItemBigDripleaf() ),
    WAXED_WEATHERED_CUT_COPPER( new ItemWaxedWeatheredCutCopper() ),
    COBBLED_DEEPSLATE_WALL( new ItemCobbledDeepslateWall() ),
    SMALL_DRIPLEAF_BLOCK( new ItemSmallDripleafBlock() ),
    GLOW_SQUID_SPAWN_EGG( new ItemGlowSquidSpawnEgg() ),
    GLOW_INK_SAC( new ItemGlowInkSac() ),
    AZALEA_LEAVES_FLOWERED( new ItemAzaleaLeavesFlowered() ),
    OXIDIZED_CUT_COPPER_STAIRS( new ItemOxidizedCutCopperStairs() ),
    WAXED_WEATHERED_COPPER( new ItemWaxedWeatheredCopper() ),
    CAVE_VINES_HEAD_WITH_BERRIES( new ItemCaveVinesHeadWithBerries() ),
    CAVE_VINES_BODY_WITH_BERRIES( new ItemCaveVinesBodyWithBerries() ),
    DEEPSLATE_GOLD_ORE( new ItemDeepslateGoldOre() ),
    FLOWERING_AZALEA( new ItemFloweringAzalea() ),
    DEEPSLATE_TILE_WALL( new ItemDeepslateTileWall() ),
    GLOW_LICHEN( new ItemGlowLichen() ),
    OXIDIZED_CUT_COPPER_SLAB( new ItemOxidizedCutCopperSlab() ),
    WAXED_DOUBLE_CUT_COPPER_SLAB( new ItemWaxedDoubleCutCopperSlab() ),
    CRACKED_DEEPSLATE_TILES( new ItemCrackedDeepslateTiles() ),
    WEATHERED_CUT_COPPER( new ItemWeatheredCutCopper() ),
    DEEPSLATE_EMERALD_ORE( new ItemDeepslateEmeraldOre() ),
    AXOLOTL_SPAWN_EGG( new ItemAxolotlSpawnEgg() ),
    SMALL_AMETHYST_BUD( new ItemSmallAmethystBud() ),
    WAXED_EXPOSED_COPPER( new ItemWaxedExposedCopper() ),
    SPORE_BLOSSOM( new ItemSporeBlossom() ),
    DEEPSLATE_BRICK_SLAB( new ItemDeepslateBrickSlab() ),
    BUDDING_AMETHYST( new ItemBuddingAmethyst() ),
    OXIDIZED_COPPER( new ItemOxidizedCopper() ),
    SMOOTH_BASALT( new ItemSmoothBasalt() ),
    TINTED_GLASS( new ItemTintedGlass() ),
    WAXED_OXIDIZED_CUT_COPPER_SLAB( new ItemWaxedOxidizedCutCopperSlab() ),
    POWDER_SNOW( new ItemPowderSnow() ),
    AZALEA( new ItemAzalea() ),
    EXPOSED_CUT_COPPER_SLAB( new ItemExposedCutCopperSlab() ),
    DEEPSLATE_BRICKS( new ItemDeepslateBricks() ),
    WEATHERED_DOUBLE_CUT_COPPER_SLAB( new ItemWeatheredDoubleCutCopperSlab() ),
    OXIDIZED_CUT_COPPER( new ItemOxidizedCutCopper() ),
    OXIDIZED_DOUBLE_CUT_COPPER_SLAB( new ItemOxidizedDoubleCutCopperSlab() ),
    POLISHED_DEEPSLATE_DOUBLE_SLAB( new ItemPolishedDeepslateDoubleSlab() ),
    DEEPSLATE_TILE_DOUBLE_SLAB( new ItemDeepslateTileDoubleSlab() ),
    CUT_COPPER_STAIRS( new ItemCutCopperStairs() ),
    COPPER_INGOT( new ItemCopperIngot() ),
    LIGHTNING_ROD( new ItemLightningRod() ),
    WAXED_OXIDIZED_CUT_COPPER( new ItemWaxedOxidizedCutCopper() ),
    POLISHED_DEEPSLATE( new ItemPolishedDeepslate() ),
    DOUBLE_CUT_COPPER_SLAB( new ItemDoubleCutCopperSlab() ),
    DEEPSLATE_REDSTONE_ORE( new ItemDeepslateRedstoneOre() ),
    WAXED_COPPER( new ItemWaxedCopper() ),
    POLISHED_DEEPSLATE_WALL( new ItemPolishedDeepslateWall() ),
    GOAT_SPAWN_EGG( new ItemGoatSpawnEgg() ),
    COBBLED_DEEPSLATE_DOUBLE_SLAB( new ItemCobbledDeepslateDoubleSlab() ),
    DEEPSLATE_IRON_ORE( new ItemDeepslateIronOre() ),
    DEEPSLATE_DIAMOND_ORE( new ItemDeepslateDiamondOre() ),
    WAXED_EXPOSED_CUT_COPPER_SLAB( new ItemWaxedExposedCutCopperSlab() ),
    WAXED_OXIDIZED_CUT_COPPER_STAIRS( new ItemWaxedOxidizedCutCopperStairs() ),
    DEEPSLATE_COPPER_ORE( new ItemDeepslateCopperOre() ),
    AZALEA_LEAVES( new ItemAzaleaLeaves() ),
    POLISHED_DEEPSLATE_STAIRS( new ItemPolishedDeepslateStairs() ),
    GLOW_BERRIES( new ItemGlowBerries() ),
    TUFF( new ItemTuff() ),
    WAXED_WEATHERED_CUT_COPPER_SLAB( new ItemWaxedWeatheredCutCopperSlab() ),
    WAXED_OXIDIZED_COPPER( new ItemWaxedOxidizedCopper() ),
    EXPOSED_CUT_COPPER_STAIRS( new ItemExposedCutCopperStairs() ),
    WAXED_CUT_COPPER_STAIRS( new ItemWaxedCutCopperStairs() ),
    DEEPSLATE_BRICK_STAIRS( new ItemDeepslateBrickStairs() ),
    WAXED_OXIDIZED_DOUBLE_CUT_COPPER_SLAB( new ItemWaxedOxidizedDoubleCutCopperSlab() ),
    CRACKED_DEEPSLATE_BRICKS( new ItemCrackedDeepslateBricks() ),
    POINTED_DRIPSTONE( new ItemPointedDripstone() ),
    DEEPSLATE_LAPIS_ORE( new ItemDeepslateLapisOre() ),
    AMETHYST_SHARD( new ItemAmethystShard() ),
    DEEPSLATE_COAL_ORE( new ItemDeepslateCoalOre() ),
    LARGE_AMETHYST_BUD( new ItemLargeAmethystBud() ),
    COPPER_BLOCK( new ItemCopperBlock() ),
    RAW_COPPER_BLOCK( new ItemRawCopperBlock() ),
    WEATHERED_COPPER( new ItemWeatheredCopper() ),
    MOSS_CARPET( new ItemMossCarpet() ),
    WAXED_EXPOSED_DOUBLE_CUT_COPPER_SLAB( new ItemWaxedExposedDoubleCutCopperSlab() ),
    INFESTED_DEEPSLATE( new ItemInfestedDeepslate() ),
    RAW_COPPER( new ItemRawCopper() ),
    MEDIUM_AMETHYST_BUD( new ItemMediumAmethystBud() ),
    AMETHYST_CLUSTER( new ItemAmethystCluster() ),
    WAXED_WEATHERED_CUT_COPPER_STAIRS( new ItemWaxedWeatheredCutCopperStairs() ),
    COBBLED_DEEPSLATE_STAIRS( new ItemCobbledDeepslateStairs() ),
    AXOLOTL_BUCKET( new ItemAxolotlBucket() ),
    DEEPSLATE( new ItemDeepslate() ),
    EXPOSED_DOUBLE_CUT_COPPER_SLAB( new ItemExposedDoubleCutCopperSlab() ),
    COPPER_ORE( new ItemCopperOre() ),
    CHISELED_DEEPSLATE( new ItemChiseledDeepslate() ),
    DEEPSLATE_TILE_SLAB( new ItemDeepslateTileSlab() ),
    DIRT_WITH_ROOTS( new ItemDirtWithRoots() ),
    RAW_IRON( new ItemRawIron() ),
    RAW_IRON_BLOCK( new ItemRawIronBlock() ),
    SPYGLASS( new ItemSpyglass() ),
    WEATHERED_CUT_COPPER_STAIRS( new ItemWeatheredCutCopperStairs() ),
    EXPOSED_COPPER( new ItemExposedCopper() ),
    COBBLED_DEEPSLATE_SLAB( new ItemCobbledDeepslateSlab() ),

    CANDLE( new ItemCandle() ),
    WHITE_CANDLE( new ItemWhiteCandle() ),
    ORANGE_CANDLE( new ItemOrangeCandle() ),
    MAGENTA_CANDLE( new ItemMagentaCandle() ),
    LIGHT_BLUE_CANDLE( new ItemLightBlueCandle() ),
    YELLOW_CANDLE( new ItemYellowCandle() ),
    LIME_CANDLE( new ItemLimeCandle() ),
    PINK_CANDLE( new ItemPinkCandle() ),
    LIGHT_GRAY( new ItemLightGrayCandle() ),
    GRAY_CANDLE( new ItemGrayCandle() ),
    CYAN_CANDLE( new ItemCyanCandle() ),
    PURPLE_CANDLE( new ItemPurpleCandle() ),
    BLUE_CANDLE( new ItemLightBlueCandle() ),
    BROWN_CANDLE( new ItemBrownCandle() ),
    GREEN_CANDLE( new ItemGreenCandle() ),
    RED_CANDLE( new ItemRedCandle() ),
    BLACK_CANDLE( new ItemBlackCandle() ),

    //NOTE: Only in item and block palette but the item/block is not in the game yet
    SCULK_SHRIEKER( new ItemSculkShrieker() ),
    SCULK( new ItemSculk() ),
    SCULK_CATALYST( new ItemSculkCatalyst() ),
    SCULK_VEIN( new ItemSculkVein() ),
    ACACIA_CHEST_BOAT(new ItemAcaciaChestBoat()),
    ALLAY_SPAWN_EGG(new ItemAllaySpawnEgg()),
    BIRCH_CHEST_BOAT(new ItemBirchChestBoat()),
    BLACK_CANDLE_CAKE(new ItemBlackCandleCake()),
    BLUE_CANDLE_CAKE(new ItemBlueCandleCake()),
    BROWN_CANDLE_CAKE(new ItemBrownCandleCake()),
    CANDLE_CAKE(new ItemCandleCake()),
    CHEST_BOAT(new ItemChestBoat()),
    CLIENT_REQUEST_PLACEHOLDER_BLOCK(new ItemClientRequestPlaceholderBlock()),
    CYAN_CANDLE_CAKE(new ItemCyanCandleCake()),
    DARK_OAK_CHEST_BOAT(new ItemDarkOakChestBoat()),
    FIREFLY_SPAWN_EGG(new ItemFireflySpawnEgg()),
    FROG_SPAWN(new ItemFrogSpawn()),
    FROG_SPAWN_EGG(new ItemFrogSpawnEgg()),
    GLOBE_BANNER_PATTERN(new ItemGlobeBannerPattern()),
    GRAY_CANDLE_CAKE(new ItemGrayCandleCake()),
    GREEN_CANDLE_CAKE(new ItemGreenCandleCake()),
    JUNGLE_CHEST_BOAT(new ItemJungleChestBoat()),
    LIGHT_BLUE_CANDLE_CAKE(new ItemLightBlueCandleCake()),
    LIGHT_GRAY_CANDLE_CAKE(new ItemLightGrayCandleCake()),
    LIME_CANDLE_CAKE(new ItemLimeCandleCake()),
    LIT_FURNACE(new ItemLitFurnace()),
    MAGENTA_CANDLE_CAKE(new ItemMagentaCandleCake()),
    MANGROVE_LEAVES(new ItemMangroveLeaves()),
    MANGROVE_PROPAGULE(new ItemMangrovePropagule()),
    MUD(new ItemMud()),
    MUD_BRICK_DOUBLE_SLAB(new ItemMudBrickDoubleSlab()),
    MUD_BRICK_SLAB(new ItemMudBrickSlab()),
    MUD_BRICK_STAIRS(new ItemMudBrickStairs()),
    MUD_BRICK_WALL(new ItemMudBrickWall()),
    MUD_BRICKS(new ItemMudBricks()),
    MUSIC_DISC_OTHERSIDE(new ItemMusicDiscOtherside()),
    OAK_CHEST_BOAT(new ItemOakChestBoat()),
    OCHRE_FROGLIGHT(new ItemOchreFroglight()),
    ORANGE_CANDLE_CAKE(new ItemOrangeCandleCake()),
    PACKED_MUD(new ItemPackedMud()),
    PEARLESCENT_FROGLIGHT(new ItemPearlescentFroglight()),
    PINK_CANDLE_CAKE(new ItemPinkCandleCake()),
    PURPLE_CANDLE_CAKE(new ItemPurpleCandleCake()),
    RED_CANDLE_CAKE(new ItemRedCandleCake()),
    REINFORCED_DEEPSLATE(new ItemReinforcedDeepslate()),
    SPRUCE_CHEST_BOAT(new ItemSpruceChestBoat()),
    TADPOLE_BUCKET(new ItemTadpoleBucket()),
    TADPOLE_SPAWN_EGG(new ItemTadpoleSpawnEgg()),
    VERDANT_FROGLIGHT(new ItemVerdantFroglight()),
    WARDEN_SPAWN_EGG(new ItemWardenSpawnEgg()),
    WHITE_CANDLE_CAKE(new ItemWhiteCandleCake()),
    YELLOW_CANDLE_CAKE(new ItemYellowCandleCake());


    private static final Map<ItemType, Item> cachedItems = new HashMap<>();

    public static void init() {
        for ( ItemType itemType : values() ) {
            cachedItems.put( itemType, itemType.getItem() );
        }
    }

    private final Item item;

    ItemType( Item item ) {
        this.item = item;
    }

    @SneakyThrows
    public <B extends Item> B getItem() {
        return (B) this.item.clone();
    }

    public static Item getItemFormNetwork( int networkId, int meta ) {
        if ( networkId == 0 || networkId == -158 ) {
            return new ItemAir();
        }
        for ( Item item : cachedItems.values() ) {
            if ( item.getRuntimeId() == networkId && item.getMeta() == meta ) {
                return item.clone();
            } else if ( item.getRuntimeId() == networkId ) {
                return item.clone();
            }
        }
        return new ItemAir();
    }

    public static Item get( String identifier ) {
        for ( Item item : cachedItems.values() ) {
            if ( identifier.equals( item.getIdentifier() ) ) {
                return item.clone();
            }
        }
        return ItemType.AIR.getItem();
    }

    public static Map<ItemType, Item> getCachedItems() {
        return cachedItems;
    }
}
