package org.jukeboxmc.item;

import com.google.gson.*;
import lombok.AllArgsConstructor;
import lombok.SneakyThrows;
import org.jukeboxmc.JukeboxMC;
import org.jukeboxmc.block.BlockColor;
import org.jukeboxmc.block.BlockShulkerBox;
import org.jukeboxmc.block.BlockType;
import org.jukeboxmc.block.type.WallType;
import org.jukeboxmc.block.type.WoodType;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * @author LucGamesYT
 * @version 1.0
 */
@AllArgsConstructor
public enum ItemType {

    AIR( new ItemAir() ),
    STONE( new ItemStone() ),
    GRASS( new ItemGrass() ),
    DIRT( new ItemDirt() ),
    COBBLESTONE( new ItemCobblestone() ),

    OAK_PLANKS( new ItemPlanks().setWoodType( WoodType.OAK ) ),
    SPRUCE_PLANKS( new ItemPlanks().setWoodType( WoodType.SPRUCE ) ),
    BIRCH_PLANKS( new ItemPlanks().setWoodType( WoodType.BIRCH ) ),
    JUNGLE_PLANKS( new ItemPlanks().setWoodType( WoodType.JUNGLE ) ),
    ACACIA_PLANKS( new ItemPlanks().setWoodType( WoodType.ACACIA ) ),
    DARK_OAK_PLANKS( new ItemPlanks().setWoodType( WoodType.DARK_OAK ) ),

    SAPLING( new ItemSapling() ),
    BEDROCK( new ItemBedrock() ),
    FLOWING_WATER( new ItemFlowingWater() ),
    WATER( new ItemWater() ),
    FLOWING_LAVA( new ItemFlowingLava() ),
    LAVA( new ItemLava() ),
    SAND( new ItemSand() ),
    GRAVEL( new ItemGravel() ),
    GOLD_ORE( new ItemGoldOre() ),
    IRON_ORE( new ItemIronOre() ),
    COAL_ORE( new ItemCoalOre() ),
    LOG( new ItemLog() ),
    LEAVES( new ItemLeaves() ),
    SPONGE( new ItemSponge() ),
    GLASS( new ItemGlass() ),
    LAPIS_ORE( new ItemLapisOre() ),
    LAPIS_BLOCK( new ItemLapisBlock() ),
    DISPENSER( new ItemDispenser() ),
    SANDSTONE( new ItemSandstone() ),
    NOTEBLOCK( new ItemNoteblock() ),
    BED_BLOCK( new ItemBedBlock() ),
    GOLDEN_RAIL( new ItemGoldenRail() ),
    DETECTOR_RAIL( new ItemDetectorRail() ),
    STICKY_PISTON( new ItemStickyPiston() ),
    WEB( new ItemWeb() ),
    TALLGRASS( new ItemTallgrass() ),
    DEADBUSH( new ItemDeadbush() ),
    PISTON( new ItemPiston() ),
    PISTONARMCOLLISION( new ItemPistonarmcollision() ),
    WOOL( new ItemWool() ),
    ELEMENT_0( new ItemElement0() ),
    YELLOW_FLOWER( new ItemYellowFlower() ),
    RED_FLOWER( new ItemRedFlower() ),
    BROWN_MUSHROOM( new ItemBrownMushroom() ),
    RED_MUSHROOM( new ItemRedMushroom() ),
    GOLD_BLOCK( new ItemGoldBlock() ),
    IRON_BLOCK( new ItemIronBlock() ),
    DOUBLE_STONE_SLAB( new ItemRealDoubleStoneSlab() ),
    STONE_SLAB( new ItemStoneSlab() ),
    BRICK_BLOCK( new ItemBrickBlock() ),
    TNT( new ItemTnt() ),
    BOOKSHELF( new ItemBookshelf() ),
    MOSSY_COBBLESTONE( new ItemMossyCobblestone() ),
    OBSIDIAN( new ItemObsidian() ),
    TORCH( new ItemTorch() ),
    FIRE( new ItemFire() ),
    MOB_SPAWNER( new ItemMobSpawner() ),
    OAK_STAIRS( new ItemOakStairs() ),
    CHEST( new ItemChest() ),
    REDSTONE_WIRE( new ItemRedstoneWire() ),
    DIAMOND_ORE( new ItemDiamondOre() ),
    DIAMOND_BLOCK( new ItemDiamondBlock() ),
    CRAFTING_BLOCK( new ItemCraftingTable() ),
    WHEAT_BLOCK( new ItemWheatBlock() ), //Maybe WHEAT
    FARMLAND( new ItemFarmland() ),
    FURNACE( new ItemFurnace() ),
    BURNING_FURNACE( new ItemBurningFurnace() ),
    STANDING_SIGN( new ItemStandingSign() ),
    OAK_DOOR( new ItemOakDoor() ),
    LADDER( new ItemLadder() ),
    RAIL( new ItemRail() ),
    STONE_STAIRS( new ItemCobblestoneStairs() ),
    WALL_SIGN( new ItemWallSign() ),
    LEVER( new ItemLever() ),
    STONE_PRESSURE_PLATE( new ItemStonePressurePlate() ),
    IRON_DOOR_BLOCK( new ItemIronDoorBlock() ),
    WOODEN_PRESSURE_PLATE( new ItemWoodenPressurePlate() ),
    REDSTONE_ORE( new ItemRedstoneOre() ),
    GLOWING_REDSTONE_ORE( new ItemGlowingRedstoneOre() ),
    UNLIT_REDSTONE_TORCH( new ItemUnlitRedstoneTorch() ),
    REDSTONE_TORCH( new ItemRedstoneTorch() ),
    STONE_BUTTON( new ItemStoneButton() ),
    SNOW_LAYER( new ItemSnowLayer() ),
    ICE( new ItemIce() ),
    SNOW( new ItemSnow() ),
    CACTUS( new ItemCactus() ),
    CLAY( new ItemClay() ),
    SUGAR_CANE( new ItemSugarCane() ),
    JUKEBOX( new ItemJukebox() ),

    OAK_FENCE( new ItemFence().setWoodType( WoodType.OAK ) ),
    SPRUCE_FENCE( new ItemFence().setWoodType( WoodType.SPRUCE ) ),
    BIRCH_FENCE( new ItemFence().setWoodType( WoodType.BIRCH ) ),
    JUNGLE_FENCE( new ItemFence().setWoodType( WoodType.JUNGLE ) ),
    ACACIA_FENCE( new ItemFence().setWoodType( WoodType.ACACIA ) ),
    DARK_OAK_FENCE( new ItemFence().setWoodType( WoodType.DARK_OAK ) ),

    PUMPKIN( new ItemPumpkin() ),
    NETHERRACK( new ItemNetherrack() ),
    SOUL_SAND( new ItemSoulSand() ),
    GLOWSTONE( new ItemGlowstone() ),
    PORTAL( new ItemPortal() ),
    JACK_O_LANTERN( new ItemJackOLantern() ),
    CAKE_BLOCK( new ItemCakeBlock() ), //Maybe ItemCakeBlock
    UNPOWERED_REPEATER( new ItemUnpoweredRepeater() ),
    POWERED_REPEATER( new ItemPoweredRepeater() ),
    INVISIBLE_BEDROCK( new ItemInvisibleBedrock() ),
    WOODEN_TRAPDOOR( new ItemTrapdoor() ),
    MONSTER_EGG( new ItemMonsterEgg() ),
    STONE_BRICK( new ItemStonebrick() ),
    BROWN_MUSHROOM_BLOCK( new ItemBrownMushroomBlock() ),
    RED_MUSHROOM_BLOCK( new ItemRedMushroomBlock() ),
    IRON_BARS( new ItemIronBars() ),
    WHITE_STAINED_GLASS_PANE( new ItemStainedGlassPane().setColor(BlockColor.WHITE) ),
    SILVER_STAINED_GLASS_PANE( new ItemStainedGlassPane().setColor(BlockColor.SILVER) ),
    GRAY_STAINED_GLASS_PANE( new ItemStainedGlassPane().setColor(BlockColor.GRAY) ),
    BLACK_STAINED_GLASS_PANE( new ItemStainedGlassPane().setColor(BlockColor.BLACK) ),
    BROWN_STAINED_GLASS_PANE( new ItemStainedGlassPane().setColor(BlockColor.BROWN) ),
    RED_STAINED_GLASS_PANE( new ItemStainedGlassPane().setColor(BlockColor.RED) ),
    ORANGE_STAINED_GLASS_PANE( new ItemStainedGlassPane().setColor(BlockColor.ORANGE) ),
    YELLOW_STAINED_GLASS_PANE( new ItemStainedGlassPane().setColor(BlockColor.YELLOW) ),
    LIME_STAINED_GLASS_PANE( new ItemStainedGlassPane().setColor(BlockColor.LIME) ),
    GREEN_STAINED_GLASS_PANE( new ItemStainedGlassPane().setColor(BlockColor.GREEN) ),
    CYAN_STAINED_GLASS_PANE( new ItemStainedGlassPane().setColor(BlockColor.CYAN) ),
    LIGHT_BLUE_STAINED_GLASS_PANE( new ItemStainedGlassPane().setColor(BlockColor.LIGHT_BLUE) ),
    BLUE_STAINED_GLASS_PANE( new ItemStainedGlassPane().setColor(BlockColor.BLUE) ),
    PURPLE_STAINED_GLASS_PANE( new ItemStainedGlassPane().setColor(BlockColor.PURPLE) ),
    MAGENTA_STAINED_GLASS_PANE( new ItemStainedGlassPane().setColor(BlockColor.MAGENTA) ),
    PINK_STAINED_GLASS_PANE( new ItemStainedGlassPane().setColor(BlockColor.PINK) ),
    MELON_BLOCK( new ItemMelonBlock() ),
    PUMPKIN_STEM( new ItemPumpkinStem() ),
    MELON_STEM( new ItemMelonStem() ),
    VINE( new ItemVine() ),
    FENCE_GATE( new ItemFenceGate() ),
    BRICK_STAIRS( new ItemBrickStairs() ),
    STONE_BRICK_STAIRS( new ItemStoneBrickStairs() ),
    MYCELIUM( new ItemMycelium() ),
    WATERLILY( new ItemWaterlily() ),
    NETHER_BRICK_BLOCK( new ItemNetherBrickBlock() ),
    NETHER_BRICK_FENCE( new ItemNetherBrickFence() ),
    NETHER_BRICK_STAIRS( new ItemNetherBrickStairs() ),
    NETHER_WART_ITEM_BLOCK( new ItemNetherWartItemBlock() ),
    ENCHANTING_TABLE( new ItemEnchantingTable() ),
    BREWING_STAND_BLOCK( new ItemBrewingstandblock() ),
    CAULDRON_BLOCK( new ItemCauldronBlock() ),
    END_PORTAL( new ItemEndPortal() ),
    END_PORTAL_FRAME( new ItemEndPortalFrame() ),
    END_STONE( new ItemEndStone() ),
    DRAGON_EGG( new ItemDragonEgg() ),
    REDSTONE_LAMP( new ItemRedstoneLamp() ),
    GLOWING_REDSTONE_LAMP( new ItemLitRedstoneLamp() ),
    DROPPER( new ItemDropper() ),
    ACTIVATOR_RAIL( new ItemActivatorRail() ),
    COCOA( new ItemCocoa() ),
    SANDSTONE_STAIRS( new ItemSandstoneStairs() ),
    EMERALD_ORE( new ItemEmeraldOre() ),
    ENDER_CHEST( new ItemEnderChest() ),
    TRIPWIRE_HOOK( new ItemTripwireHook() ),
    TRIPWIRE( new ItemTripwire() ),
    EMERALD_BLOCK( new ItemEmeraldBlock() ),
    SPRUCE_STAIRS( new ItemSpruceStairs() ),
    BIRCH_STAIRS( new ItemBirchStairs() ),
    JUNGLE_STAIRS( new ItemJungleStairs() ),
    COMMAND_BLOCK( new ItemCommandBlock() ),
    BEACON( new ItemBeacon() ),

    COBBLESTONE_WALL( new ItemCobblestoneWall().setWallType( WallType.COBBLESTONE ) ),
    MOSSY_COBBLESTONE_WALL( new ItemCobblestoneWall().setWallType( WallType.MOSSY_COBBLESTONE ) ),
    GRANITE_WALL( new ItemCobblestoneWall().setWallType( WallType.GRANITE ) ),
    DIORITE_WALL( new ItemCobblestoneWall().setWallType( WallType.DIORITE ) ),
    ANDESITE_WALL( new ItemCobblestoneWall().setWallType( WallType.ANDESITE ) ),
    SANDSTONE_WALL( new ItemCobblestoneWall().setWallType( WallType.SANDSTONE ) ),
    RED_SANDSTONE_WALL( new ItemCobblestoneWall().setWallType( WallType.RED_SANDSTONE ) ),
    STONE_BRICK_WALL( new ItemCobblestoneWall().setWallType( WallType.STONE_BRICK ) ),
    MOSSY_STONE_BRICK_WALL( new ItemCobblestoneWall().setWallType( WallType.MOSSY_STONE_BRICK ) ),
    BRICK_WALL( new ItemCobblestoneWall().setWallType( WallType.BRICK ) ),
    NETHER_BRICK_WALL( new ItemCobblestoneWall().setWallType( WallType.NETHER_BRICK ) ),
    RED_NETHER_BRICK_WALL( new ItemCobblestoneWall().setWallType( WallType.RED_NETHER_BRICK ) ),
    ENDSTONE_WALL( new ItemCobblestoneWall().setWallType( WallType.END_BRICK ) ),
    PRISMARINE_WALL( new ItemCobblestoneWall().setWallType( WallType.PRISMARINE ) ),

    FLOWER_POT_BLOCK( new ItemFlowerPotBlock() ),
    CARROTS( new ItemCarrots() ),
    POTATOES( new ItemPotatoes() ),
    WOODEN_BUTTON( new ItemWoodenButton() ),
    SKULL_BLOCK( new ItemSkullBlock() ),
    ANVIL( new ItemAnvil() ),
    TRAPPED_CHEST( new ItemTrappedChest() ),
    LIGHT_WEIGHTED_PRESSURE_PLATE( new ItemLightWeightedPressurePlate() ),
    HEAVY_WEIGHTED_PRESSURE_PLATE( new ItemHeavyWeightedPressurePlate() ),
    UNPOWERED_COMPARATOR( new ItemUnpoweredComparator() ),
    POWERED_COMPARATOR( new ItemPoweredComparator() ),
    DAYLIGHT_DETECTOR( new ItemDaylightDetector() ),
    REDSTONE_BLOCK( new ItemRedstoneBlock() ),
    QUARTZ_ORE( new ItemQuartzOre() ),
    HOPPER_BLOCK( new ItemHopperBlock() ),
    QUARTZ_BLOCK( new ItemQuartzBlock() ),
    QUARTZ_STAIRS( new ItemQuartzStairs() ),
    DOUBLE_WOODEN_SLAB( new ItemDoubleWoodenSlab() ),
    WOODEN_SLAB( new ItemWoodenSlab() ),
    STAINED_HARDENED_CLAY( new ItemStainedHardenedClay() ),
    STAINED_GLASS_PANE( new ItemStainedGlassPane() ),
    ACACIA_LEAVES( new ItemAcaciaLeaves() ),
    ACACIA_LOG( new ItemAcaciaLog() ),
    ACACIA_STAIRS( new ItemAcaciaStairs() ),
    DARK_OAK_STAIRS( new ItemDarkOakStairs() ),
    SLIME( new ItemSlime() ),
    GLOW_STICK( new ItemGlowStick() ),
    IRON_TRAPDOOR( new ItemIronTrapdoor() ),
    PRISMARINE( new ItemPrismarine() ),
    SEALANTERN( new ItemSealantern() ),
    HAY_BLOCK( new ItemHayBlock() ),
    CARPET( new ItemCarpet() ),
    HARDENED_CLAY( new ItemHardenedClay() ),
    COAL_BLOCK( new ItemCoalBlock() ),
    PACKED_ICE( new ItemPackedIce() ),
    DOUBLE_PLANT( new ItemDoublePlant() ),
    STANDING_BANNER( new ItemStandingBanner() ),
    WALL_BANNER( new ItemWallBanner() ),
    DAYLIGHT_DETECTOR_INVERTED( new ItemDaylightDetectorInverted() ),
    RED_SANDSTONE( new ItemRedSandstone() ),
    RED_SANDSTONE_STAIRS( new ItemRedSandstoneStairs() ),
    DOUBLE_RED_SANDSTONE_SLAB( new ItemStoneSlab2() ),
    REAL_DOUBLE_RED_SANDSTONE_SLAB( new ItemRealDoubleRedSandstoneSlab() ),
    SPRUCE_FENCE_GATE( new ItemSpruceFenceGate() ),
    BIRCH_FENCE_GATE( new ItemBirchFenceGate() ),
    JUNGLE_FENCE_GATE( new ItemJungleFenceGate() ),
    DARK_OAK_FENCE_GATE( new ItemDarkOakFenceGate() ),
    ACACIA_FENCE_GATE( new ItemAcaciaFenceGate() ),
    REPEATING_COMMAND_BLOCK( new ItemRepeatingCommandBlock() ),
    CHAIN_COMMAND_BLOCK( new ItemChainCommandBlock() ),
    HARD_GLASS_PANE( new ItemHardGlassPane() ),
    HARD_STAINED_GLASS_PANE( new ItemHardStainedGlassPane() ),
    CHEMICAL_HEAT( new ItemChemicalHeat() ),
    SPRUCE_DOOR_BLOCK( new ItemSpruceDoorBlock() ),
    BIRCH_DOOR_BLOCK( new ItemBirchDoorBlock() ),
    JUNGLE_DOOR_BLOCK( new ItemJungleDoorBlock() ),
    ACACIA_DOOR_BLOCK( new ItemAcaciaDoorBlock() ),
    DARK_OAK_DOOR_BLOCK( new ItemDarkOakDoorBlock() ),
    GRASS_PATH( new ItemGrassPath() ),
    FRAME_BLOCK( new ItemFrameBlock() ), //
    CHORUS_FLOWER( new ItemChorusFlower() ),
    PURPUR_BLOCK( new ItemPurpurBlock() ),
    COLORED_TORCH_RG( new ItemColoredTorchRG() ),
    PURPUR_STAIRS( new ItemPurpurStairs() ),
    COLORED_TORCH_BP( new ItemColoredTorchBP() ),
    UNDYED_SHULKER_BOX( new ItemUndyedShulkerBox() ),
    END_BRICKS( new ItemEndBricks() ),
    FROSTED_ICE( new ItemFrostedIce() ),
    END_ROD( new ItemEndRod() ),
    END_GATEWAY( new ItemEndGateway() ),
    ALLOW( new ItemAllow() ),
    DENY( new ItemDeny() ),
    BORDER_BLOCK( new ItemBorderBlock() ),
    MAGMA( new ItemMagma() ),
    NETHER_WART_BLOCK( new ItemNetherWartBlock() ),
    RED_NETHER_BRICK( new ItemRedNetherBrick() ),
    BONE_BLOCK( new ItemBoneBlock() ),
    STRUCTURE_VOID( new ItemStructureVoid() ),

    WHITE_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.WHITE ).toItem() ),
    ORANGE_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.ORANGE ).toItem() ),
    MAGENTA_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.MAGENTA ).toItem() ),
    LIGHT_BLUE_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.LIGHT_BLUE ).toItem() ),
    YELLOW_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.YELLOW ).toItem() ),
    LIME_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.LIME ).toItem() ),
    PINK_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.PINK ).toItem() ),
    GRAY_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.GRAY ).toItem() ),
    SILVER_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.SILVER ).toItem() ),
    CYAN_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.CYAN ).toItem() ),
    PURPLE_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.PURPLE ).toItem()),
    BLUE_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.BLUE ).toItem()),
    BROWN_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.BROWN ).toItem() ),
    GREEN_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.GREEN ).toItem() ),
    RED_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.RED ).toItem() ),
    BLACK_SHULKER_BOX( BlockType.SHULKER_BOX.<BlockShulkerBox>getBlock().setColor( BlockColor.BLACK ).toItem() ),

    PURPLE_GLAZED_TERRACOTTA( new ItemPurpleGlazedTerracotta() ),
    WHITE_GLAZED_TERRACOTTA( new ItemWhiteGlazedTerracotta() ),
    ORANGE_GLAZED_TERRACOTTA( new ItemOrangeGlazedTerracotta() ),
    MAGENTA_GLAZED_TERRACOTTA( new ItemMagentaGlazedTerracotta() ),
    LIGHT_BLUE_GLAZED_TERRACOTTA( new ItemLightBlueGlazedTerracotta() ),
    YELLOW_GLAZED_TERRACOTTA( new ItemYellowGlazedTerracotta() ),
    LIME_GLAZED_TERRACOTTA( new ItemLimeGlazedTerracotta() ),
    PINK_GLAZED_TERRACOTTA( new ItemPinkGlazedTerracotta() ),
    GRAY_GLAZED_TERRACOTTA( new ItemGrayGlazedTerracotta() ),
    SILVER_GLAZED_TERRACOTTA( new ItemSilverGlazedTerracotta() ),
    CYAN_GLAZED_TERRACOTTA( new ItemCyanGlazedTerracotta() ),
    BLUE_GLAZED_TERRACOTTA( new ItemBlueGlazedTerracotta() ),
    BROWN_GLAZED_TERRACOTTA( new ItemBrownGlazedTerracotta() ),
    GREEN_GLAZED_TERRACOTTA( new ItemGreenGlazedTerracotta() ),
    RED_GLAZED_TERRACOTTA( new ItemRedGlazedTerracotta() ),
    BLACK_GLAZED_TERRACOTTA( new ItemBlackGlazedTerracotta() ),
    CONCRETE( new ItemConcrete() ),
    CONCRETEPOWDER( new ItemConcretePowder() ),
    CHEMISTRY_TABLE( new ItemChemistryTable() ),
    UNDERWATER_TORCH( new ItemUnderwaterTorch() ),
    CHORUS_PLANT( new ItemChorusPlant() ),
    WHITE_STAINED_GLASS( new ItemStainedGlass().setColor(BlockColor.WHITE) ),
    SILVER_STAINED_GLASS( new ItemStainedGlass().setColor(BlockColor.SILVER) ),
    GRAY_STAINED_GLASS( new ItemStainedGlass().setColor(BlockColor.GRAY) ),
    BLACK_STAINED_GLASS( new ItemStainedGlass().setColor(BlockColor.BLACK) ),
    BROWN_STAINED_GLASS( new ItemStainedGlass().setColor(BlockColor.BROWN) ),
    RED_STAINED_GLASS( new ItemStainedGlass().setColor(BlockColor.RED) ),
    ORANGE_STAINED_GLASS( new ItemStainedGlass().setColor(BlockColor.ORANGE) ),
    YELLOW_STAINED_GLASS( new ItemStainedGlass().setColor(BlockColor.YELLOW) ),
    LIME_STAINED_GLASS( new ItemStainedGlass().setColor(BlockColor.LIME) ),
    GREEN_STAINED_GLASS( new ItemStainedGlass().setColor(BlockColor.GREEN) ),
    CYAN_STAINED_GLASS( new ItemStainedGlass().setColor(BlockColor.CYAN) ),
    LIGHT_BLUE_STAINED_GLASS( new ItemStainedGlass().setColor(BlockColor.LIGHT_BLUE) ),
    BLUE_STAINED_GLASS( new ItemStainedGlass().setColor(BlockColor.BLUE) ),
    PURPLE_STAINED_GLASS( new ItemStainedGlass().setColor(BlockColor.PURPLE) ),
    MAGENTA_STAINED_GLASS( new ItemStainedGlass().setColor(BlockColor.MAGENTA) ),
    PINK_STAINED_GLASS( new ItemStainedGlass().setColor(BlockColor.PINK) ),
    CAMERA_BLOCK( new ItemCameraBlock() ),
    PODZOL( new ItemPodzol() ),
    BEETROOT_BLOCK( new ItemBeetrootBlock() ),
    STONECUTTER( new ItemStonecutter() ),
    GLOWING_OBSIDIAN( new ItemGlowingObsidian() ),
    NETHERREACTOR( new ItemNetherreactor() ),
    INFO_UPDATE( new ItemInfoUpdate() ),
    INFO_UPDATE2( new ItemInfoUpdate2() ),
    MOVING_BLOCK( new ItemMovingblock() ),
    OBSERVER( new ItemObserver() ),
    STRUCTURE_BLOCK( new ItemStructureBlock() ),
    HARD_GLASS( new ItemHardGlass() ),
    HARD_STAINED_GLASS( new ItemHardStainedGlass() ),
    RESERVED6( new ItemReserved6() ),
    PRISMARINE_STAIRS( new ItemPrismarineStairs() ),
    DARK_PRISMARINE_STAIRS( new ItemDarkPrismarineStairs() ),
    PRISMARINE_BRICKS_STAIRS( new ItemPrismarineBricksStairs() ),
    STRIPPED_SPRUCE_LOG( new ItemStrippedSpruceLog() ),
    STRIPPED_BIRCH_LOG( new ItemStrippedBirchLog() ),
    STRIPPED_JUNGLE_LOG( new ItemStrippedJungleLog() ),
    STRIPPED_ACACIA_LOG( new ItemStrippedAcaciaLog() ),
    STRIPPED_DARK_OAK_LOG( new ItemStrippedDarkOakLog() ),
    STRIPPED_OAK_LOG( new ItemStrippedOakLog() ),
    BLUE_ICE( new ItemBlueIce() ),
    ELEMENT_1( new ItemElement1() ),
    ELEMENT_2( new ItemElement2() ),
    ELEMENT_3( new ItemElement3() ),
    ELEMENT_4( new ItemElement4() ),
    ELEMENT_5( new ItemElement5() ),
    ELEMENT_6( new ItemElement6() ),
    ELEMENT_7( new ItemElement7() ),
    ELEMENT_8( new ItemElement8() ),
    ELEMENT_9( new ItemElement9() ),
    ELEMENT_10( new ItemElement10() ),
    ELEMENT_11( new ItemElement11() ),
    ELEMENT_12( new ItemElement12() ),
    ELEMENT_13( new ItemElement13() ),
    ELEMENT_14( new ItemElement14() ),
    ELEMENT_15( new ItemElement15() ),
    ELEMENT_16( new ItemElement16() ),
    ELEMENT_17( new ItemElement17() ),
    ELEMENT_18( new ItemElement18() ),
    ELEMENT_19( new ItemElement19() ),
    ELEMENT_20( new ItemElement20() ),
    ELEMENT_21( new ItemElement21() ),
    ELEMENT_22( new ItemElement22() ),
    ELEMENT_23( new ItemElement23() ),
    ELEMENT_24( new ItemElement24() ),
    ELEMENT_25( new ItemElement25() ),
    ELEMENT_26( new ItemElement26() ),
    ELEMENT_27( new ItemElement27() ),
    ELEMENT_28( new ItemElement28() ),
    ELEMENT_29( new ItemElement29() ),
    ELEMENT_30( new ItemElement30() ),
    ELEMENT_31( new ItemElement31() ),
    ELEMENT_32( new ItemElement32() ),
    ELEMENT_33( new ItemElement33() ),
    ELEMENT_34( new ItemElement34() ),
    ELEMENT_35( new ItemElement35() ),
    ELEMENT_36( new ItemElement36() ),
    ELEMENT_37( new ItemElement37() ),
    ELEMENT_38( new ItemElement38() ),
    ELEMENT_39( new ItemElement39() ),
    ELEMENT_40( new ItemElement40() ),
    ELEMENT_41( new ItemElement41() ),
    ELEMENT_42( new ItemElement42() ),
    ELEMENT_43( new ItemElement43() ),
    ELEMENT_44( new ItemElement44() ),
    ELEMENT_45( new ItemElement45() ),
    ELEMENT_46( new ItemElement46() ),
    ELEMENT_47( new ItemElement47() ),
    ELEMENT_48( new ItemElement48() ),
    ELEMENT_49( new ItemElement49() ),
    ELEMENT_50( new ItemElement50() ),
    ELEMENT_51( new ItemElement51() ),
    ELEMENT_52( new ItemElement52() ),
    ELEMENT_53( new ItemElement53() ),
    ELEMENT_54( new ItemElement54() ),
    ELEMENT_55( new ItemElement55() ),
    ELEMENT_56( new ItemElement56() ),
    ELEMENT_57( new ItemElement57() ),
    ELEMENT_58( new ItemElement58() ),
    ELEMENT_59( new ItemElement59() ),
    ELEMENT_60( new ItemElement60() ),
    ELEMENT_61( new ItemElement61() ),
    ELEMENT_62( new ItemElement62() ),
    ELEMENT_63( new ItemElement63() ),
    ELEMENT_64( new ItemElement64() ),
    ELEMENT_65( new ItemElement65() ),
    ELEMENT_66( new ItemElement66() ),
    ELEMENT_67( new ItemElement67() ),
    ELEMENT_68( new ItemElement68() ),
    ELEMENT_69( new ItemElement69() ),
    ELEMENT_70( new ItemElement70() ),
    ELEMENT_71( new ItemElement71() ),
    ELEMENT_72( new ItemElement72() ),
    ELEMENT_73( new ItemElement73() ),
    ELEMENT_74( new ItemElement74() ),
    ELEMENT_75( new ItemElement75() ),
    ELEMENT_76( new ItemElement76() ),
    ELEMENT_77( new ItemElement77() ),
    ELEMENT_78( new ItemElement78() ),
    ELEMENT_79( new ItemElement79() ),
    ELEMENT_80( new ItemElement80() ),
    ELEMENT_81( new ItemElement81() ),
    ELEMENT_82( new ItemElement82() ),
    ELEMENT_83( new ItemElement83() ),
    ELEMENT_84( new ItemElement84() ),
    ELEMENT_85( new ItemElement85() ),
    ELEMENT_86( new ItemElement86() ),
    ELEMENT_87( new ItemElement87() ),
    ELEMENT_88( new ItemElement88() ),
    ELEMENT_89( new ItemElement89() ),
    ELEMENT_90( new ItemElement90() ),
    ELEMENT_91( new ItemElement91() ),
    ELEMENT_92( new ItemElement92() ),
    ELEMENT_93( new ItemElement93() ),
    ELEMENT_94( new ItemElement94() ),
    ELEMENT_95( new ItemElement95() ),
    ELEMENT_96( new ItemElement96() ),
    ELEMENT_97( new ItemElement97() ),
    ELEMENT_98( new ItemElement98() ),
    ELEMENT_99( new ItemElement99() ),
    ELEMENT_100( new ItemElement100() ),
    ELEMENT_101( new ItemElement101() ),
    ELEMENT_102( new ItemElement102() ),
    ELEMENT_103( new ItemElement103() ),
    ELEMENT_104( new ItemElement104() ),
    ELEMENT_105( new ItemElement105() ),
    ELEMENT_106( new ItemElement106() ),
    ELEMENT_107( new ItemElement107() ),
    ELEMENT_108( new ItemElement108() ),
    ELEMENT_109( new ItemElement109() ),
    ELEMENT_110( new ItemElement110() ),
    ELEMENT_111( new ItemElement111() ),
    ELEMENT_112( new ItemElement112() ),
    ELEMENT_113( new ItemElement113() ),
    ELEMENT_114( new ItemElement114() ),
    ELEMENT_115( new ItemElement115() ),
    ELEMENT_116( new ItemElement116() ),
    ELEMENT_117( new ItemElement117() ),
    ELEMENT_118( new ItemElement118() ),
    SEAGRASS( new ItemSeagrass() ),
    CORAL( new ItemCoral() ),
    CORAL_BLOCK( new ItemCoralBlock() ),
    CORAL_FAN( new ItemCoralFan() ),
    CORAL_FAN_DEAD( new ItemCoralFanDead() ),
    CORAL_FAN_HANG( new ItemCoralFanHang() ),
    CORAL_FAN_HANG2( new ItemCoralFanHang2() ),
    CORAL_FAN_HANG3( new ItemCoralFanHang3() ),
    KELP_BLOCK( new ItemKelpBlock() ),
    DRIED_KELP_BLOCK( new ItemDriedKelpBlock() ),
    ACACIA_BUTTON( new ItemAcaciaButton() ),
    BIRCH_BUTTON( new ItemBirchButton() ),
    DARK_OAK_BUTTON( new ItemDarkOakButton() ),
    JUNGLE_BUTTON( new ItemJungleButton() ),
    SPRUCE_BUTTON( new ItemSpruceButton() ),
    ACACIA_TRAPDOOR( new ItemAcaciaTrapdoor() ),
    BIRCH_TRAPDOOR( new ItemBirchTrapdoor() ),
    DARK_OAK_TRAPDOOR( new ItemDarkOakTrapdoor() ),
    JUNGLE_TRAPDOOR( new ItemJungleTrapdoor() ),
    SPRUCE_TRAPDOOR( new ItemSpruceTrapdoor() ),
    ACACIA_PRESSURE_PLATE( new ItemAcaciaPressurePlate() ),
    BIRCH_PRESSURE_PLATE( new ItemBirchPressurePlate() ),
    DARK_OAK_PRESSURE_PLATE( new ItemDarkOakPressurePlate() ),
    JUNGLE_PRESSUREP_PLATE( new ItemJunglePressurePlate() ),
    SPRUCE_PRESSURE_PLATE( new ItemSprucePressurePlate() ),
    CARVED_PUMPKIN( new ItemCarvedPumpkin() ),
    SEA_PICKLE( new ItemSeaPickle() ),
    CONDUIT( new ItemConduit() ),
    TURTLE_EGG( new ItemTurtleEgg() ),
    BUBBLE_COLUMN( new ItemBubbleColumn() ),
    BARRIER( new ItemBarrier() ),
    REAL_DOUBLE_END_STONE_BRICK_SLAB( new ItemRealDoubleEndStoneBrickSlab() ),
    BAMBOO( new ItemBamboo() ),
    BAMBOO_SAPLING( new ItemBambooSapling() ),
    SCAFFOLDING( new ItemScaffolding() ),
    REAL_DOUBLE_MOSSY_STONE_BRICK_SLAB( new ItemRealDoubleMossyStoneBrickSlab() ),
    DOUBLE_END_STONE_BRICK_SLAB( new ItemStoneSlab3() ),
    DOUBLE_MOSSY_STONE_BRICK_SLAB( new ItemStoneSlab4() ),
    GRANITE_STAIRS( new ItemGraniteStairs() ),
    DIORITE_STAIRS( new ItemDioriteStairs() ),
    ANDESITE_STAIRS( new ItemAndesiteStairs() ),
    POLISHED_GRANITE_STAIRS( new ItemPolishedGraniteStairs() ),
    POLISHED_DIORITE_STAIRS( new ItemPolishedDioriteStairs() ),
    POLISHED_ANDESITE_STAIRS( new ItemPolishedAndesiteStairs() ),
    MOSSY_STONE_BRICK_STAIRS( new ItemMossyStoneBrickStairs() ),
    SMOOTH_RED_SANDSTONE_STAIRS( new ItemSmoothRedSandstoneStairs() ),
    SMOOTH_SANDSTONE_STAIRS( new ItemSmoothSandstoneStairs() ),
    END_BRICK_STAIRS( new ItemEndBrickStairs() ),
    MOSSY_COBBLESTONE_STAIRS( new ItemMossyCobblestoneStairs() ),
    NORMAL_STONE_STAIRS( new ItemNormalStoneStairs() ),
    SPRUCE_STANDING_SIGN( new ItemSpruceStandingSign() ),
    SPURCE_WALL_SIGN( new ItemSpruceWallSign() ),
    SMOOTH_STONE( new ItemSmoothStone() ),
    RED_NETHER_BRICK_STAIRS( new ItemRedNetherBrickStairs() ),
    SMOOTH_QUARTZ_STAIRS( new ItemSmoothQuartzStairs() ),
    BIRCH_STANDING_SIGN( new ItemBirchStandingSign() ),
    BIRCH_WALL_SIGN( new ItemBirchWallSign() ),
    JUNGLE_STANDING_SIGN( new ItemJungleStandingSign() ),
    JUNGLE_WALL_SIGN( new ItemJungleWallSign() ),
    ACACIA_STANDING_SIGN( new ItemAcaciaStandingSign() ),
    ACACIA_WALL_SIGN( new ItemAcaciaWallSign() ),
    DARK_OAK_STANDING_SIGN( new ItemDarkOakStandingSign() ),
    DARK_OAK_WALL_SIGN( new ItemDarkOakWallSign() ),
    LECTERN( new ItemLectern() ),
    GRINDSTONE( new ItemGrindstone() ),
    BLAST_FURNACE( new ItemBlastFurnace() ),
    STONECUTTER_BLOCK( new ItemStonecutterBlock() ),
    SMOKER( new ItemSmoker() ),
    LIT_SMOKER( new ItemLitSmoker() ),
    CARTOGHRAPHY( new ItemCartographyTable() ),
    FLETCHING_TABLE( new ItemFletchingTable() ),
    SMITHING_TABLE( new ItemSmithingTable() ),
    BARREL( new ItemBarrel() ),
    LOOM( new ItemLoom() ),
    BELL( new ItemBell() ),
    SWEETY_BERRY_BUSH( new ItemSweetBerryBush() ),
    LANTERN( new ItemLantern() ),
    CAMPFIRE_BLOCK( new ItemCampfireBlock() ),
    LAVA_CAULDRON( new ItemLavaCauldron() ),
    JIGSAW( new ItemJigsaw() ),
    WOOD( new ItemWood() ),
    COMPOSTER( new ItemComposter() ),
    LIT_BLAST_FURNACE( new ItemLitBlastFurnace() ),
    LIGHT_BLOCK( new ItemLightBlock() ),
    WITHER_ROSE( new ItemWitherRose() ),
    STICKY_PISTONARMCOLLISION( new ItemStickypistonarmcollision() ),
    BBE_NEST( new ItemBeeNest() ),
    BEEHIVE( new ItemBeehive() ),
    HONEY_BLOCK( new ItemHoneyBlock() ),
    HONEYCOMB_BLOCK( new ItemHoneycomBlock() ),
    LODESTONE( new ItemLodestone() ),
    CRIMSON_ROOTS( new ItemCrimsonRoots() ),
    WARPED_ROOTS( new ItemWarpedRoots() ),
    CRIMSON_STEM( new ItemCrimsonStem() ),
    WARPED_STEM( new ItemWarpedStem() ),
    WARPED_WART_BLOCK( new ItemWarpedWartBlock() ),
    CRIMSON_FUNGUS( new ItemCrimsonFungus() ),
    SHROOMLIGHT( new ItemShroomlight() ),
    WEEPING_VINES( new ItemWeepingVines() ),
    CRIMSON_NYLIUM( new ItemCrimsonNylium() ),
    WARPED_NYLIUM( new ItemWarpedNylium() ),
    BASALT( new ItemBasalt() ),
    POLISHED_BASALT( new ItemPolishedBasalt() ),
    SOUL_SOIL( new ItemSoulSoil() ),
    SOUL_FIRE( new ItemSoulFire() ),
    NETHER_SPROCUTS( new ItemNetherSproutsBlock() ),
    TARGET( new ItemTarget() ),
    STRIPPED_CRIMSON_STEM( new ItemStrippedCrimsonStem() ),
    STRIPPED_WARPED_STEM( new ItemStrippedWarpedStem() ),
    CRIMSON_PLANKS( new ItemCrimsonPlanks() ),
    WARPED_PLANKS( new ItemWarpedPlanks() ),
    CRIMSON_DOOR_DOOR( new ItemCrimsonDoorBlock() ),
    WARPED_DOOR_DOOR( new ItemWarpedDoorBlock() ),
    CRIMSON_TRAPDOOR( new ItemCrimsonTrapdoor() ),
    WARPED_TRAPDOOR( new ItemWarpedTrapdoor() ),
    CRIMSON_STANDING_SIGN( new ItemCrimsonStandingSign() ),
    WARPED_STANDING_SIGN( new ItemWarpedStandingSign() ),
    CRIMSON_WALL_SIGN( new ItemCrimsonWallSign() ),
    WARPED_WALL_SIGN( new ItemWarpedWallSign() ),
    CRIMSON_STAIRS( new ItemCrimsonStairs() ),
    WARPED_STAIRS( new ItemWarpedStairs() ),
    CRIMSON_FENCE( new ItemCrimsonFence() ),
    WARPED_FENCE( new ItemWarpedFence() ),
    CRIMSON_FENCE_GATE( new ItemCrimsonFenceGate() ),
    WARPED_FENCE_GATE( new ItemWarpedFenceGate() ),
    CRIMSON_BUTTON( new ItemCrimsonButton() ),
    WARPED_BUTTON( new ItemWarpedButton() ),
    CRIMSON_PRESSURE_PLATE( new ItemCrimsonPressurePlate() ),
    WARPED_PRESSURE_PLATE( new ItemWarpedPressurePlate() ),
    CRIMSON_SLAB( new ItemCrimsonSlab() ),
    WARPED_SLAB( new ItemWarpedSlab() ),
    CRIMSON_DOUBLE_SLAB( new ItemCrimsonDoubleSlab() ),
    WARPED_DOUBLE_SLAB( new ItemWarpedDoubleSlab() ),
    SOUL_TORCH( new ItemSoulTorch() ),
    SOUL_LANTERN( new ItemSoulLantern() ),
    NETHERITE_BLOCK( new ItemNetheriteBlock() ),
    ANCIENT_DEBRIS( new ItemAncientDebris() ),
    RESPAWN_ANCHOR( new ItemRespawnAnchor() ),
    BLACKSTONE( new ItemBlackstone() ),
    POLISHED_BLACKSTONE_BRICKS( new ItemPolishedBlackstoneBricks() ),
    POLISHED_BLACKSTONE_BRICK_STAIRS( new ItemPolishedBlackstoneBrickStairs() ),
    BLACKSTONE_STAIRS( new ItemBlackstoneStairs() ),
    BLACKSTONE_WALL( new ItemBlackstoneWall() ),
    POLISHED_BLACKSTONE_BRICK_WALL( new ItemPolishedBlackstoneBrickWall() ),
    CHISELED_POLISHED_BLACKSTONE( new ItemChiseledPolishedBlackstone() ),
    CRACKED_POLISHED_BLACKSTONE_BRICKS( new ItemCrackedPolishedBlackstoneBricks() ),
    GLIDED_BLACKSTONE( new ItemGlidedBlackstone() ),
    BLACKSTONE_SLAB( new ItemBlackstoneSlab() ),
    BLACKSTONE_DOUBLE_SLAB( new ItemBlackstoneDoubleSlab() ),
    POLISHED_BLACKSTONE_BRICK_SLAB( new ItemPolishedBlackstoneBrickSlab() ),
    POLISHED_BLACKSTONE_BRICK_DOUBLE_SLAB( new ItemPolishedBlackstoneBrickDoubleSlab() ),
    CHAIN_BLOCK( new ItemChainBlock() ),
    TWISTING_VINES( new ItemTwistingVines() ),
    NETHER_GOLD_ORE( new ItemNetherGoldOre() ),
    CRYING_OBSIDIAN( new ItemCryingObsidian() ),
    SOUL_CAMPFIRE_BLOCK( new ItemSoulCampfireBlock() ),
    POLISHED_BLACKSTONE( new ItemPolishedBlackstone() ),
    POLISHED_BLACKSTONE_STAIRS( new ItemPolishedBlackstoneStairs() ),
    POLISHED_BLACKSTONE_SLAB( new ItemPolishedBlackstoneSlab() ),
    POLISHED_BLACKSTONE_DOUBLE_SLAB( new ItemPolishedBlackstoneDoubleSlab() ),
    POLISHED_BLACKSTONE_PRESSURE_PLATE( new ItemPolishedBlackstonePressurePlate() ),
    POLISHED_BLACKSTONE_BUTTON( new ItemPolishedBlackstoneButton() ),
    POLISHED_BLACKSTONE_WALL( new ItemPolishedBlackstoneWall() ),
    WARPED_HYPHAE( new ItemWarpedHyphae() ),
    CRIMSON_HYPHAE( new ItemCrimsonHyphae() ),
    STRIPPED_CRIMSON_HYPHAE( new ItemStrippedCrimsonHyphae() ),
    STRIPPED_WARPED_HYPHAE( new ItemStrippedWarpedHyphae() ),
    CHISELED_NETHER_BRICKS( new ItemChiseledNetherBricks() ),
    CRACKED_NETHER_BRICKS( new ItemCrackedNetherBricks() ),
    QUARTZ_BRICKS( new ItemQuartzBricks() ), //To here are blocks

    IRON_SHOVEL( new ItemIronShovel() ), //From here items
    IRON_PICKAXE( new ItemIronPickaxe() ),
    IRON_AXE( new ItemIronAxe() ),
    FLINT_AND_STEEL( new ItemFlintAndSteel() ),
    APPLE( new ItemApple() ),
    BOW( new ItemBow() ),
    ARROW( new ItemArrow() ),
    COAL( new ItemCoal() ),
    DIAMOND( new ItemDiamond() ),
    IRON_INGOT( new ItemIronIngot() ),
    GOLD_INGOT( new ItemGoldIngot() ),
    IRON_SWORD( new ItemIronSword() ),
    WOODEN_SWORD( new ItemWoodenSword() ),
    WOODEN_SHOVEL( new ItemWoodenShovel() ),
    WOODEN_PICKAXE( new ItemWoodenPickaxe() ),
    WOODEN_AXE( new ItemWoodenAxe() ),
    STONE_SWORD( new ItemStoneSword() ),
    STONE_SHOVEL( new ItemStoneShovel() ),
    STONE_PICKAXE( new ItemStonePickaxe() ),
    STONE_AXE( new ItemStoneAxe() ),
    DIAMOND_SWORD( new ItemDiamondSword() ),
    DIAMOND_SHOVEL( new ItemDiamondShovel() ),
    DIAMOND_PICKAXE( new ItemDiamondPickaxe() ),
    DIAMOND_AXE( new ItemDiamondAxe() ),
    STICK( new ItemStick() ),
    BOWL( new ItemBowl() ),
    MUSHROOM_STEW( new ItemMushroomStew() ),
    GOLDEN_SWORD( new ItemGoldenSword() ),
    GOLDEN_SHOVEL( new ItemGoldenShovel() ),
    GOLDEN_PICKAXE( new ItemGoldenPickaxe() ),
    GOLDEN_AXE( new ItemGoldenAxe() ),
    STRING( new ItemString() ),
    FEATHER( new ItemFeather() ),
    GUNPOWDER( new ItemGunpowder() ),
    WOODEN_HOE( new ItemWoodenHoe() ),
    STONE_HOE( new ItemStoneHoe() ),
    IRON_HOE( new ItemIronHoe() ),
    DIAMOND_HOE( new ItemDiamondHoe() ),
    GOLDEN_HOE( new ItemGoldenHoe() ),
    WHEAT_SEEDS( new ItemWheatSeeds() ),
    WHEAT( new ItemWheat() ),
    BREAD( new ItemBread() ),
    LEATHER_HELMENT( new ItemLeatherHelmet() ),
    LEATHER_CHESTPLATE( new ItemLeatherChestplate() ),
    LEATHER_LEGGINGS( new ItemLeatherLeggings() ),
    LEATHER_BOOTS( new ItemLeatherBoots() ),
    CHAIN_HELMET( new ItemChainHelmet() ),
    CHAIN_CHESTPLATE( new ItemChainChestplate() ),
    CHAIN_LEGGINGS( new ItemChainLeggings() ),
    CHAIN_BOOTS( new ItemChainBoots() ),
    IRON_HELMET( new ItemIronHelmet() ),
    IRON_CHESTPLATE( new ItemIronChestplate() ),
    IRON_LEGGINGS( new ItemIronLeggings() ),
    IRON_BOOTS( new ItemIronBoots() ),
    DIAMOND_HELMET( new ItemDiamondHelment() ),
    DIAMOND_CHESTPLATE( new ItemDiamondChestplate() ),
    DIAMOND_LEGGINGS( new ItemDiamondLeggings() ),
    DIAMOND_BOOTS( new ItemDiamondBoots() ),
    GOLDEN_HELMET( new ItemGoldenHelmet() ),
    GOLDEN_CHESTPLATE( new ItemGoldenChestplate() ),
    GOLDEN_LEGGINGS( new ItemGoldenLeggings() ),
    GOLDEN_BOOTS( new ItemGoldenBoots() ),
    FLINT( new ItemFlint() ),
    PROKCHOP( new ItemPorkchop() ),
    COOKED_PORKCHOP( new ItemCookedPorkchop() ),
    PAINTING( new ItemPainting() ),
    GOLDEN_APPLE( new ItemGoldenApple() ),
    SIGN( new ItemOakSign() ),
    WOODEN_DOOR( new ItemOakDoor() ),
    BUCKET( new ItemBucket() ),
    MINECART( new ItemMinecart() ),
    SADDLE( new ItemSaddle() ),
    IRON_DOOR( new ItemIronDoor() ),
    REDSTONE( new ItemRedstone() ),
    SNOWBALL( new ItemSnowball() ),
    BOAT( new ItemBoat() ),
    LEATHER( new ItemLeather() ),
    KELP( new ItemKelp() ),
    BRICK( new ItemBrick() ),
    CLAY_BALL( new ItemClayBall() ),
    REEDS( new ItemReeds() ),
    PAPER( new ItemPaper() ),
    BOOK( new ItemBook() ),
    SLIME_BALL( new ItemSlimeBall() ),
    CHEST_MINECART( new ItemChestMinecart() ),
    EGG( new ItemEgg() ),
    COMPASS( new ItemCompass() ),
    FISHING_ROD( new ItemFishingRod() ),
    CLOCK( new ItemClock() ),
    GLOWSTONE_DUST( new ItemGlowstoneDust() ),
    RAW_COD( new ItemCod() ),
    COOKED_COD( new ItemCookedCod() ),
    DYE( new ItemDye() ),
    BONE( new ItemBone() ),
    SUGAR( new ItemSugar() ),
    CAKE( new ItemCake() ),
    BED( new ItemBed() ),
    REPEATER( new ItemRepeater() ),
    COOKIE( new ItemCookie() ),
    MAP( new ItemFilledMap() ),
    SHEARS( new ItemShears() ),
    MELON( new ItemMelonSlice() ), //Maybe wrong
    PUMPKIN_SEEDS( new ItemPumpkinSeeds() ),
    MELON_SEEDS( new ItemMelonSeeds() ),
    BEEF( new ItemBeef() ),
    COOKED_BEEF( new ItemCookedBeef() ),
    CHICKEN( new ItemChicken() ),
    COOKED_CHICKEN( new ItemCookedChicken() ),
    ROTTEN_FLESH( new ItemRottenFlesh() ),
    ENDER_PEARL( new ItemEnderPearl() ),
    BLAZE_ROD( new ItemBlazeRod() ),
    GHAST_TEAR( new ItemGhastTear() ),
    GOLD_NUGGET( new ItemGoldNugget() ),
    NETHER_WART( new ItemNetherWart() ),
    POTION( new ItemPotion() ),
    GLASS_BOTTLE( new ItemGlassBottle() ),
    SPIDER_EYE( new ItemSpiderEye() ),
    FERMENTED_SPIDER_EYE( new ItemFermentedSpiderEye() ),
    BLAZE_POWDER( new ItemBlazePowder() ),
    MAGMA_CREAM( new ItemMagmaCream() ),
    BREWING_STAND( new ItemBrewingStand() ),
    CAULDRON( new ItemCauldron() ),
    ENDER_EYE( new ItemEnderEye() ),
    SPECKLED_MELON( new ItemGlisteringMelonSlice() ),
    SPAWN_EGG( new ItemSpawnEgg() ),
    EXPERIENCE_BOTTLE( new ItemExperienceBottle() ),
    FIREBALL( new ItemFireCharge() ),
    WRITEABLE_BOOK( new ItemWriteableBook() ),
    WRITTEN_BOOK( new ItemWrittenBook() ),
    EMERALD( new ItemEmerald() ),
    FRAME( new ItemFrame() ),
    FLOWER_POT( new ItemFlowerPot() ),
    CARROT( new ItemCarrot() ),
    POTATO( new ItemPotato() ),
    BAKED_POTATO( new ItemBakedPotato() ),
    POISONOUS_POTATO( new ItemPoisonousPotato() ),
    EMPTY_MAP( new ItemEmptyMap() ),
    GOLDEN_CARROT( new ItemGoldenCarrot() ),
    SKULL( new ItemSkull() ),
    CARROT_ON_STICK( new ItemCarrotOnAStick() ),
    NETHER_START( new ItemNetherStar() ),
    PUMPKIN_PIE( new ItemPumpkinPie() ),
    FIREWORK_ROCKET( new ItemFireworkRocket() ),
    FIREWORK_SCHARGE( new ItemFireworkStar() ),
    ENCHANTED_BOOK( new ItemEnchantedBook() ),
    COMPARATOR( new ItemComparator() ),
    NETHERBRICK( new ItemNetherbrick() ),
    QUARTZ( new ItemQuartz() ),
    TNT_MINECART( new ItemTntMinecart() ),
    HOPPER_MINECART( new ItemHopperMinecart() ),
    PRISMARINE_SHARD( new ItemPrismarineShard() ),
    HOPPER( new ItemHopper() ),
    RABBIT( new ItemRabbit() ),
    COOKED_RABBIT( new ItemCookedRabbit() ),
    RABBIT_STEW( new ItemRabbitStew() ),
    RABBIT_FOOT( new ItemRabbitFoot() ),
    RABBIT_HIDE( new ItemRabbitHide() ),
    HORSE_ARMOR_LEATHER( new ItemLeatherHorseArmor() ),
    HORSE_ARMOR_IRON( new ItemIronHorseArmor() ),
    HORSE_ARMOR_GOLD( new ItemGoldenHorseArmor() ),
    HORSE_ARMOR_DIAMOND( new ItemDiamondHorseArmor() ),
    LEAD( new ItemLead() ),
    NAMETAG( new ItemNameTag() ),
    PRISMARINE_CRYSTALS( new ItemPrismarineCrystals() ),
    RAW_MUTTON( new ItemMutton() ),
    COOKED_MUTTON( new ItemCookedMutton() ),
    ARMOR_STAND( new ItemArmorStand() ),
    END_CRYSTAL( new ItemEndCrystal() ),
    SPRUCE_DOOR( new ItemSpruceDoor() ),
    BIRCH_DOOR( new ItemBirchDoor() ),
    JUNGLE_DOOR( new ItemJungleDoor() ),
    ACACIA_DOOR( new ItemAcaciaDoor() ),
    DARK_OAK_DOOR( new ItemDarkOakDoor() ),
    CHORUS_FRUIT( new ItemChorusFruit() ),
    CHORUS_FRUIT_POPPED( new ItemPoppedChorusFruit() ),
    BANNER_PATTERN( new ItemBannerPattern() ),
    DRAGON_BREATH( new ItemDragonBreath() ),
    SPLASH_POTION( new ItemSplashPotion() ),
    LINGERING_POTION( new ItemLingeringPotion() ),
    SPARKLER( new ItemSparkler() ),
    COMMAND_BLOCK_MINECART( new ItemCommandBlockMinecart() ),
    ELYTRA( new ItemElytra() ),
    SHULKER_SHELL( new ItemShulkerShell() ),
    BANNER( new ItemBanner() ),
    MEDICINE( new ItemMedicine() ),
    BALLON( new ItemBalloon() ),
    SUPER_FERTILIZER( new ItemRapidFertilizer() ),
    TOTEM( new ItemTotemOfUndying() ),
    BLEACH( new ItemBleach() ),
    IRON_NUGGET( new ItemIronNugget() ),
    ICE_BOMB( new ItemIceBomb() ),
    TRIDENT( new ItemTrident() ),
    BEETROOT( new ItemBeetroot() ),
    BEETROOT_SEEDS( new ItemBeetrootSeeds() ),
    BEETROOT_SOUP( new ItemBeetrootSoup() ),
    SALMON( new ItemSalmon() ),
    CLOWNFISH( new ItemTropicalFish() ),
    PUFFERFISH( new ItemPufferfish() ),
    COOKED_SALMON( new ItemCookedSalmon() ),
    DRIED_KELP( new ItemDriedKelp() ),
    NAUTILUS_SHELL( new ItemNautilusShell() ),
    ENCHANTED_APPLE( new ItemEnchantedGoldenApple() ),
    HEART_OF_THE_SEA( new ItemHeartOfTheSea() ),
    TURTLE_SHELL_PIECE( new ItemScute() ),
    TURTLE_HELMET( new ItemTurtleHelmet() ),
    PHANTOM_MEMBRANE( new ItemPhantomMembrane() ),
    CROSSBOW( new ItemCrossbow() ),
    SPRUCE_SIGN( new ItemSpruceSign() ),
    BIRCH_SIGN( new ItemBirchSign() ),
    JUNGLE_SIGN( new ItemJungleSign() ),
    ACACIA_SIGN( new ItemAcaciaSign() ),
    DARK_OAK_SIGN( new ItemDarkOakSign() ),
    SWEET_BERRIES( new ItemSweetBerries() ),
    CAMERA( new ItemCamera() ),
    COMPOUND( new ItemCompund() ),
    RECORD_13( new ItemMusicDisc13() ),
    RECORD_CAT( new ItemMusicDiscCat() ),
    RECORD_BLOCKS( new ItemMusicDiscBlocks() ),
    RECORD_CHIRP( new ItemMusicDiscChirp() ),
    RECORD_FAR( new ItemMusicDiscFar() ),
    RECORD_MALL( new ItemMusicDiscMall() ),
    RECORD_MELLOHI( new ItemMusicDiscMellohi() ),
    RECORD_STAL( new ItemMusicDiscStal() ),
    RECORD_STARD( new ItemMusicDiscStrad() ),
    RECORD_WARD( new ItemMusicDiscWard() ),
    RECORD_11( new ItemMusicDisc11() ),
    RECORD_WAIT( new ItemMusicDiscWait() ),
    SHIELD( new ItemShield() ),
    CAMPFIRE( new ItemCampfire() ),
    SUSPICIOUS_STEW( new ItemSuspiciousStew() ),
    HONEYCOMB( new ItemHoneycomb() ),
    HONEY_BOTTLE( new ItemHoneyBottle() ),
    LODESTONECOMPASS( new ItemLodestoneCompass() ),
    NETHERITE_INGOT( new ItemNetheriteIngot() ),
    NETHERITE_SWORD( new ItemNetheriteSword() ),
    NETHERITE_SHOVEL( new ItemNetheriteShovel() ),
    NETHERITE_PICKAXE( new ItemNetheritePickaxe() ),
    NETHERITE_AXE( new ItemNetheriteAxe() ),
    NETHERITE_HOE( new ItemNetheriteHoe() ),
    NETHERITE_HELMET( new ItemNetheriteHelmet() ),
    NETHERITE_CHESTPLATE( new ItemNetheriteChestplate() ),
    NETHERITE_LEGGINGS( new ItemNetheriteLeggings() ),
    NETHERITE_BOOTS( new ItemNetheriteBoots() ),
    NETHERITE_SCRAP( new ItemNetheriteScrap() ),
    CRIMSON_SIGN( new ItemCrimsonSign() ),
    WARPED_SIGN( new ItemWarpedSign() ),
    CRIMSON_DOOR( new ItemCrimsonDoor() ),
    WARPED_DOOR( new ItemWarpedDoor() ),
    WARPED_FUNGUS_ON_A_STICK( new ItemWarpedFungusOnAStick() ),
    CHAIN( new ItemChain() ),
    RECORD_PIGSTEP( new ItemMusicDiscPigstep() ),
    NETHER_SPROUTS( new ItemNetherSproutsBlock() ),
    SOUL_CAMPFIRE( new ItemSoulCampfire() ),
    WARPED_FUNGUS( new ItemWarpedFungus() ),
    NETHER_SQROUTS( new ItemNetherSprouts() ),
    BORDURER_INDENTED_BANNER_PATTERN( new ItemBordureIndentedBannerPattern() ),
    PUFFERFISH_SPAWN_EGG( new ItemPufferfishSpawnEgg() ),
    BAT_SPAWN_EGG( new ItemBatSpawnEgg() ),
    DONKEY_SPAWN_EGG( new ItemDonkeySpawnEgg() ),
    CAVE_SPIDER_SPAWN_EGG( new ItemCaveSpiderSpawnEgg() ),
    PIGLIN_BRUTE_SPAWN_EGG( new ItemPiglinBruteSpawnEgg() ),
    ZOGLIN_SPAWN_EGG( new ItemZoglinSpawnEgg() ),
    PIGLIN_SPAWN_EGG( new ItemPiglinSpawnEgg() ),
    HOGLIN_SPAWN_EGG( new ItemHoglinSpawnEgg() ),
    WANDERING_TRADER_SPAWN_EGG( new ItemWanderingTraderSpawnEgg() ),
    PILLAGER_SPAWN_EGG( new ItemPillagerSpawnEgg() ),
    PHANTOM_SPAWN_EGG( new ItemPhantomSpawnEgg() ),
    DROWNED_SPAWN_EGG( new ItemDrownedSpawnEgg() ),
    TROPICAL_FISH_SPAWN_EGG( new ItemTropicalFishSpawnEgg() ),
    VINDICATOR_SPAWN_EGG( new ItemVindicatorSpawnEgg() ),
    LLAMA_SPAWN_EGG( new ItemLlamaSpawnEgg() ),
    SKELETON_HORSE_SPAWN_EGG( new ItemSkeletonHorseSpawnEgg() ),
    BLAZE_SPAWN_EGG( new ItemBlazeSpawnEgg() ),
    VEX_SPAWN_EGG( new ItemVexSpawnEgg() ), //
    SQUID_SPAWN_EGG( new ItemSquidSpawnEgg() ),
    ORANGE_DYE( new ItemOrangeDye() ),
    VILLAGER_SPAWN_EGG( new ItemVillagerSpawnEgg() ),
    ZOMBIE_SPAWN_EGG( new ItemZombieSpawnEgg() ),
    TURTLE_SPAWN_EGG( new ItemTurtleSpawnEgg() ),
    SLIME_SPAWN_EGG( new ItemSlimeSpawnEgg() ),
    SILVERFISH_SPAWN_EGG( new ItemSilverfishSpawnEgg() ),
    GHAST_SPAWN_EGG( new ItemGhastSpawnEgg() ),
    MOOSHROOM_SPAWN_EGG( new ItemMooshroomSpawnEgg() ),
    WOLF_SPAWN_EGG( new ItemWolfSpawnEgg() ),
    CHICKEN_SPAWN_EGG( new ItemChickenSpawnEgg() ),
    DARK_OAK_BOAT( new ItemDarkOakBoat() ),
    WITHER_SKELETON_SPAWN_EGG( new ItemWitherSkeletonSpawnEgg() ),
    STRAY_SPAWN_EGG( new ItemStraySpawnEgg() ),
    FIELD_MASONED_BANNER_PATTERN( new ItemFieldMasonedBannerPattern() ),
    PIGLIN_BANNER_PATTERN( new ItemPiglinBannerPattern() ),
    COD_BUCKET( new ItemCodBucket() ),
    ENDERMITE_SPAWN_EGG( new ItemEndermiteSpawnEgg() ),
    PARROT_SPAWN_EGG( new ItemParrotSpawnEgg() ),
    COCOA_BEANS( new ItemCocoaBeans() ),
    BLUE_DYE( new ItemBlueDye() ),
    CREEPER_BANNER_PATTERN( new ItemCreeperBannerPattern() ),
    EVOKER_SPAWN_EGG( new ItemEvokerSpawnEgg() ),
    RED_DYE( new ItemRedDye() ),
    CREEPER_SPAWN_EGG( new ItemCreeperSpawnEgg() ),
    GRAY_DYE( new ItemGrayDye() ),
    CHARCOAL( new ItemCharcoal() ),
    WHITE_DYE( new ItemWhiteDye() ),
    SHULKER_SPAWN_EGG( new ItemShulkerSpawnEgg() ),
    PUFFERFISH_BUCKET( new ItemPufferfishBucket() ),
    ELDER_GUARDIAN_SPAWN_EGG( new ItemElderGuardianSpawnEgg() ),
    WATER_BUCKET( new ItemWaterBucket() ),
    ZOMBIE_VILLAGER_SPAWN_EGG( new ItemZombieVillagerSpawnEgg() ),
    SKULL_BANNER_PATTERN( new ItemSkullBannerPattern() ),
    WITCH_SPAWN_EGG( new ItemWitchSpawnEgg() ),
    PANDA_SPAWN_EGG( new ItemPandaSpawnEgg() ),
    OCELOT_SPAWN_EGG( new ItemOcelotSpawnEgg() ),
    POLAR_BEAR_SPAWN_EGG( new ItemPolarBearSpawnEgg() ),
    SALMON_BUCKET( new ItemSalmonBucket() ),
    COW_SPAWN_EGG( new ItemCowSpawnEgg() ),
    LIGHT_BLUE_DYE( new ItemLightBlueDye() ),
    ENDERMAN_SPAWN_EGG( new ItemEndermanSpawnEgg() ),
    CAT_SPAWN_EGG( new ItemCatSpawnEgg() ),
    LIME_DYE( new ItemLimeDye() ),
    LAVA_BUCKET( new ItemLavaBucket() ),
    HUSK_SPAWN_SPAWN_EGG( new ItemHuskSpawnEgg() ),
    OAK_BOAT( new ItemOakBoat() ),
    DOLPHIN_SPAWN_EGG( new ItemDolphinSpawnEgg() ),
    HORSE_SPAWN_EGG( new ItemHorseSpawnEgg() ),
    MILK_BUCKET( new ItemMilkBucket() ),
    JUNGLE_BOAT( new ItemJungleBoat() ),
    MAGMA_CUBE_SPAWN_EGG( new ItemMagmaCubeSpawnEgg() ),
    BEE_SPAWN_EGG( new ItemBeeSpawnEgg() ),
    ACACIA_BOAT( new ItemAcaciaBoat() ),
    SPIDER_SPAWN_EGG( new ItemSpiderSpawnEgg() ),
    ZOMBIE_PIGMAN_SPAWN_EGG( new ItemZombiePigmanSpawnEgg() ),
    SHEEP_SPAWN_EGG( new ItemSheepSpawnEgg() ),
    SKELETON_SPAWN_EGG( new ItemSkeletonSpawnEgg() ),
    BLACK_DYE( new ItemBlackDye() ),
    FOX_SPAWN_EGG( new ItemFoxSpawnEgg() ),
    SALMON_SPAWN_EGG( new ItemSalmonSpawnEgg() ),
    MAGENTA_DYE( new ItemMagentaDye() ),
    MULE_SPAWN_EGG( new ItemMuleSpawnEgg() ),
    GREEN_DYE( new ItemGreenDye() ),
    BROWN_DYE( new ItemBrownDye() ),
    PINK_DYE( new ItemPinkDye() ),
    INC_SAC( new ItemIncSac() ),
    YELLOW_DYE( new ItemYellowDye() ),
    LAPIS_LAZULI( new ItemLapisLazuli() ),
    RAVAGER_SPAWN_EGG( new ItemRavagerSpawnEgg() ),
    TROPICAL_FISH_BUCKET( new ItemTropicalFishBucket() ),
    FLOWER_BANNER_PATTERN( new ItemFlowerBannerPattern() ),
    NPC_SPAWN_EGG( new ItemNPCSpawnEgg() ),
    BONE_MEAL( new ItemBoneMeal() ),
    BIRCH_BOAT( new ItemBirchBoat() ),
    UNKNOWN( new ItemUnknown() ),
    AGENT_SPAWN_EGG( new ItemAgentSpawnEgg() ),
    LIGHT_GRAY_DYE( new ItemLightGrayDye() ),
    SPRUCE_BOAT( new ItemSpruceBoat() ),
    COD_SPAWN_EGG( new ItemCodSpawnEgg() ),
    GUARDIAN_SPAWN_EGG( new ItemGuardianSpawnEgg() ),
    PIG_SPAWN_EGG( new ItemPigSpawnEgg() ),
    ZOMBIE_HORSE_SPAWN_EGG( new ItemZombieHorseSpawnEgg() ),
    RABBIT_SPAWN_EGG( new ItemRabbitSpawnEgg() ),
    STRIDER_SPAWN_EGG( new ItemStriderSpawnEgg() ),
    ITEM_WOODEN_DOOR( new ItemWoodenDoorBlock() ),
    CYAN_DYE( new ItemCyanDye() ),
    PURPLE_DYE( new ItemPurpleDye() ),
    MOJANG_BANNER_PATTERN( new ItemMojangBannerPattern() );

    private static List<Map<String, Object>> creativeItems = new ArrayList<>();
    private static List<Map<String, Object>> itemPalette = new ArrayList<>();

    private static Map<String, Integer> itemIdByName = new HashMap<>();

    private static final List<Item> CACHED_ITEMS = new ArrayList<>();

    public static void init() {
        Gson gson = new GsonBuilder().setPrettyPrinting().create();

        InputStream creativeItems = JukeboxMC.class.getClassLoader().getResourceAsStream( "creative_items.json" );
        JsonArray parseCreative = new JsonParser().parse( new InputStreamReader( creativeItems ) ).getAsJsonObject().getAsJsonArray( "items" );
        ItemType.setCreativeItems( ( gson.fromJson( parseCreative, List.class ) ) );

        InputStream itemPalette = JukeboxMC.class.getClassLoader().getResourceAsStream( "itempalette.json" );
        JsonElement parseItem = new JsonParser().parse( new InputStreamReader( itemPalette ) );
        List<Map<String, Object>> map = gson.fromJson( parseItem, List.class );
        ItemType.setItemPalette( map );

        for ( Map<String, Object> objectMap : map ) {
            itemIdByName.put( (String) objectMap.get( "name" ), (int) (double) objectMap.get( "id" ) );
        }

       /*
        final JsonArray jsonItemPalette = (JsonArray) parseItem;
        jsonItemPalette.forEach( jsonItemPaletteEntryElement -> {
            final JsonObject jsonItemPaletteEntry = (JsonObject) jsonItemPaletteEntryElement;
            itemIdByName.put( jsonItemPaletteEntry.get( "name" ).getAsString(), jsonItemPaletteEntry.get( "id" ).getAsInt() );
        } );

        for ( ItemType value : ItemType.values() ) {
            CACHED_ITEMS.add( value.getItem() );
        }

        final JsonObject itemPalette2 = new JsonParser().parse( new InputStreamReader( JukeboxMC().getClassLoader().getResourceAsStream( "itempalette2.json" ) ) ).getAsJsonObject();
        itemPalette2.entrySet().forEach( it -> {
            final JsonObject it2 = it.getValue().getAsJsonObject();
            itemSubIdByIdAndBlockRuntimeId.put( new ItemIdBlockRuntimeIdPair(it2.get( "bedrock_id" ).getAsInt(), it2.has( "bedrock_data" ) ? it2.get( "bedrock_data" ).getAsInt() : 0), it2.has( "blockRuntimeId" ) ? it2.get( "blockRuntimeId" ).getAsInt() : 0 );
        } );
        */
    }

    public static List<Item> getItems() {
        return CACHED_ITEMS;
    }

    public static Item getItemFormNetwork( int networkId, int meta, int blockruntimeId ) {
        for ( ItemType itemType : values() ) {
            Item item = itemType.getItem();
            if ( item.getRuntimeId() == networkId && item.getMeta() == meta ) {
                return item;
            } else if ( item.getRuntimeId() == networkId ) {
                return item;
            }
        }
        return ItemType.AIR.getItem();
    }

    public static List<Map<String, Object>> getCreativeItems() {
        return creativeItems;
    }

    public static void setCreativeItems( List<Map<String, Object>> creativeItems ) {
        ItemType.creativeItems = creativeItems;
    }

    public static List<Map<String, Object>> getItemPalette() {
        return itemPalette;
    }

    public static Map<String, Integer> getItemIdByName() {
        return itemIdByName;
    }

    public static void setItemPalette( List<Map<String, Object>> itemPalette ) {
        ItemType.itemPalette = itemPalette;
    }

    private Item item;

    @SneakyThrows
    public <B extends Item> B getItem() {
        return (B) this.item;
    }

}
