package org.jukeboxmc.block;

import com.google.gson.Gson;
import org.jukeboxmc.Bootstrap;
import org.jukeboxmc.block.behavior.*;
import org.jukeboxmc.block.data.BlockProperties;
import org.jukeboxmc.item.TierType;
import org.jukeboxmc.item.ToolType;
import org.jukeboxmc.util.Identifier;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;

/**
 * @author LucGamesYT
 * @version 1.0
 */
public class BlockRegistry {

    private static final Map<BlockType, Identifier> IDENTIFIER_FROM_BLOCKTYPE = new LinkedHashMap<>();
    private static final Map<Identifier, BlockType> BLOCKTYPE_FROM_IDENTIFIER = new LinkedHashMap<>();
    private static final Map<Identifier, BlockProperties> BLOCK_PROPERTIES = new LinkedHashMap<>();
    private static final Map<BlockType, Class<? extends Block>> BLOCKCLASS_FROM_BLOCKTYPE = new LinkedHashMap<>();

    public static void init() {
        register( BlockType.ACACIA_BUTTON, Identifier.fromString( "minecraft:acacia_button" ), BlockButton.class );
        register( BlockType.ACACIA_DOOR, Identifier.fromString( "minecraft:acacia_door" ), BlockDoor.class );
        register( BlockType.ACACIA_FENCE_GATE, Identifier.fromString( "minecraft:acacia_fence_gate" ), BlockFenceGate.class );
        register( BlockType.ACACIA_PRESSURE_PLATE, Identifier.fromString( "minecraft:acacia_pressure_plate" ), BlockPressurePlate.class );
        register( BlockType.ACACIA_STAIRS, Identifier.fromString( "minecraft:acacia_stairs" ), BlockStairs.class );
        register( BlockType.ACACIA_STANDING_SIGN, Identifier.fromString( "minecraft:acacia_standing_sign" ), BlockAcaciaStandingSign.class );
        register( BlockType.ACACIA_TRAPDOOR, Identifier.fromString( "minecraft:acacia_trapdoor" ), BlockTrapdoor.class );
        register( BlockType.ACACIA_WALL_SIGN, Identifier.fromString( "minecraft:acacia_wall_sign" ), BlockAcaciaWallSign.class );
        register( BlockType.ACTIVATOR_RAIL, Identifier.fromString( "minecraft:activator_rail" ), BlockRail.class );
        register( BlockType.AIR, Identifier.fromString( "minecraft:air" ), BlockAir.class );
        register( BlockType.ALLOW, Identifier.fromString( "minecraft:allow" ) );
        register( BlockType.AMETHYST_BLOCK, Identifier.fromString( "minecraft:amethyst_block" ) );
        register( BlockType.AMETHYST_CLUSTER, Identifier.fromString( "minecraft:amethyst_cluster" ) );
        register( BlockType.ANCIENT_DEBRIS, Identifier.fromString( "minecraft:ancient_debris" ) );
        register( BlockType.ANDESITE_STAIRS, Identifier.fromString( "minecraft:andesite_stairs" ), BlockStairs.class );
        register( BlockType.ANVIL, Identifier.fromString( "minecraft:anvil" ), BlockAnvil.class );
        register( BlockType.AZALEA, Identifier.fromString( "minecraft:azalea" ) );
        register( BlockType.AZALEA_LEAVES, Identifier.fromString( "minecraft:azalea_leaves" ) );
        register( BlockType.AZALEA_LEAVES_FLOWERED, Identifier.fromString( "minecraft:azalea_leaves_flowered" ) );
        register( BlockType.BAMBOO, Identifier.fromString( "minecraft:bamboo" ), BlockBamboo.class );
        register( BlockType.BAMBOO_SAPLING, Identifier.fromString( "minecraft:bamboo_sapling" ) );
        register( BlockType.BARREL, Identifier.fromString( "minecraft:barrel" ), BlockBarrel.class );
        register( BlockType.BARRIER, Identifier.fromString( "minecraft:barrier" ) );
        register( BlockType.BASALT, Identifier.fromString( "minecraft:basalt" ), BlockBasalt.class );
        register( BlockType.BEACON, Identifier.fromString( "minecraft:beacon" ) );
        register( BlockType.BED, Identifier.fromString( "minecraft:bed" ), BlockBed.class );
        register( BlockType.BEDROCK, Identifier.fromString( "minecraft:bedrock" ) );
        register( BlockType.BEEHIVE, Identifier.fromString( "minecraft:beehive" ) );
        register( BlockType.BEETROOT, Identifier.fromString( "minecraft:beetroot" ) );
        register( BlockType.BEE_NEST, Identifier.fromString( "minecraft:bee_nest" ) );
        register( BlockType.BELL, Identifier.fromString( "minecraft:bell" ), BlockBell.class );
        register( BlockType.BIG_DRIPLEAF, Identifier.fromString( "minecraft:big_dripleaf" ) );
        register( BlockType.BIRCH_BUTTON, Identifier.fromString( "minecraft:birch_button" ), BlockButton.class );
        register( BlockType.BIRCH_DOOR, Identifier.fromString( "minecraft:birch_door" ), BlockDoor.class );
        register( BlockType.BIRCH_FENCE_GATE, Identifier.fromString( "minecraft:birch_fence_gate" ), BlockFenceGate.class );
        register( BlockType.BIRCH_PRESSURE_PLATE, Identifier.fromString( "minecraft:birch_pressure_plate" ), BlockPressurePlate.class );
        register( BlockType.BIRCH_STAIRS, Identifier.fromString( "minecraft:birch_stairs" ), BlockStairs.class );
        register( BlockType.BIRCH_STANDING_SIGN, Identifier.fromString( "minecraft:birch_standing_sign" ), BlockAcaciaStandingSign.class );
        register( BlockType.BIRCH_TRAPDOOR, Identifier.fromString( "minecraft:birch_trapdoor" ), BlockTrapdoor.class );
        register( BlockType.BIRCH_WALL_SIGN, Identifier.fromString( "minecraft:birch_wall_sign" ), BlockBirchWallSign.class );
        register( BlockType.BLACKSTONE, Identifier.fromString( "minecraft:blackstone" ) );
        register( BlockType.BLACKSTONE_DOUBLE_SLAB, Identifier.fromString( "minecraft:blackstone_double_slab" ), BlockDoubleBlackStoneSlab.class );
        register( BlockType.BLACKSTONE_SLAB, Identifier.fromString( "minecraft:blackstone_slab" ), BlockBlackStoneSlab.class );
        register( BlockType.BLACKSTONE_STAIRS, Identifier.fromString( "minecraft:blackstone_stairs" ), BlockStairs.class );
        register( BlockType.BLACKSTONE_WALL, Identifier.fromString( "minecraft:blackstone_wall" ), BlockWall.class );
        register( BlockType.BLACK_CANDLE, Identifier.fromString( "minecraft:black_candle" ), BlockCandle.class );
        register( BlockType.BLACK_CANDLE_CAKE, Identifier.fromString( "minecraft:black_candle_cake" ) );
        register( BlockType.BLACK_GLAZED_TERRACOTTA, Identifier.fromString( "minecraft:black_glazed_terracotta" ) );
        register( BlockType.BLAST_FURNACE, Identifier.fromString( "minecraft:blast_furnace" ), BlockBlastFurnace.class );
        register( BlockType.BLUE_CANDLE, Identifier.fromString( "minecraft:blue_candle" ), BlockCandle.class );
        register( BlockType.BLUE_CANDLE_CAKE, Identifier.fromString( "minecraft:blue_candle_cake" ) );
        register( BlockType.BLUE_GLAZED_TERRACOTTA, Identifier.fromString( "minecraft:blue_glazed_terracotta" ) );
        register( BlockType.BLUE_ICE, Identifier.fromString( "minecraft:blue_ice" ) );
        register( BlockType.BONE_BLOCK, Identifier.fromString( "minecraft:bone_block" ) );
        register( BlockType.BOOKSHELF, Identifier.fromString( "minecraft:bookshelf" ) );
        register( BlockType.BORDER_BLOCK, Identifier.fromString( "minecraft:border_block" ) );
        register( BlockType.BREWING_STAND, Identifier.fromString( "minecraft:brewing_stand" ), BlockBrewingStand.class );
        register( BlockType.BRICK_BLOCK, Identifier.fromString( "minecraft:brick_block" ) );
        register( BlockType.BRICK_STAIRS, Identifier.fromString( "minecraft:brick_stairs" ), BlockStairs.class );
        register( BlockType.BROWN_CANDLE, Identifier.fromString( "minecraft:brown_candle" ), BlockCandle.class );
        register( BlockType.BROWN_CANDLE_CAKE, Identifier.fromString( "minecraft:brown_candle_cake" ) );
        register( BlockType.BROWN_GLAZED_TERRACOTTA, Identifier.fromString( "minecraft:brown_glazed_terracotta" ) );
        register( BlockType.BROWN_MUSHROOM, Identifier.fromString( "minecraft:brown_mushroom" ) );
        register( BlockType.BROWN_MUSHROOM_BLOCK, Identifier.fromString( "minecraft:brown_mushroom_block" ) );
        register( BlockType.BUBBLE_COLUMN, Identifier.fromString( "minecraft:bubble_column" ) );
        register( BlockType.BUDDING_AMETHYST, Identifier.fromString( "minecraft:budding_amethyst" ) );
        register( BlockType.CACTUS, Identifier.fromString( "minecraft:cactus" ) );
        register( BlockType.CAKE, Identifier.fromString( "minecraft:cake" ) );
        register( BlockType.CALCITE, Identifier.fromString( "minecraft:calcite" ) );
        register( BlockType.CAMERA, Identifier.fromString( "minecraft:camera" ) );
        register( BlockType.CAMPFIRE, Identifier.fromString( "minecraft:campfire" ), BlockCampfire.class );
        register( BlockType.CANDLE, Identifier.fromString( "minecraft:candle" ), BlockCandle.class );
        register( BlockType.CANDLE_CAKE, Identifier.fromString( "minecraft:candle_cake" ) );
        register( BlockType.CARPET, Identifier.fromString( "minecraft:carpet" ), BlockCarpet.class );
        register( BlockType.CARROTS, Identifier.fromString( "minecraft:carrots" ) );
        register( BlockType.CARTOGRAPHY_TABLE, Identifier.fromString( "minecraft:cartography_table" ), BlockCartographyTable.class );
        register( BlockType.CARVED_PUMPKIN, Identifier.fromString( "minecraft:carved_pumpkin" ) );
        register( BlockType.CAULDRON, Identifier.fromString( "minecraft:cauldron" ), BlockCauldron.class );
        register( BlockType.CAVE_VINES, Identifier.fromString( "minecraft:cave_vines" ) );
        register( BlockType.CAVE_VINES_BODY_WITH_BERRIES, Identifier.fromString( "minecraft:cave_vines_body_with_berries" ) );
        register( BlockType.CAVE_VINES_HEAD_WITH_BERRIES, Identifier.fromString( "minecraft:cave_vines_head_with_berries" ) );
        register( BlockType.CHAIN, Identifier.fromString( "minecraft:chain" ), BlockChain.class );
        register( BlockType.CHAIN_COMMAND_BLOCK, Identifier.fromString( "minecraft:chain_command_block" ) );
        register( BlockType.CHEMICAL_HEAT, Identifier.fromString( "minecraft:chemical_heat" ) );
        register( BlockType.CHEMISTRY_TABLE, Identifier.fromString( "minecraft:chemistry_table" ) );
        register( BlockType.CHEST, Identifier.fromString( "minecraft:chest" ), BlockChest.class );
        register( BlockType.CHISELED_DEEPSLATE, Identifier.fromString( "minecraft:chiseled_deepslate" ) );
        register( BlockType.CHISELED_NETHER_BRICKS, Identifier.fromString( "minecraft:chiseled_nether_bricks" ) );
        register( BlockType.CHISELED_POLISHED_BLACKSTONE, Identifier.fromString( "minecraft:chiseled_polished_blackstone" ) );
        register( BlockType.CHORUS_FLOWER, Identifier.fromString( "minecraft:chorus_flower" ) );
        register( BlockType.CHORUS_PLANT, Identifier.fromString( "minecraft:chorus_plant" ) );
        register( BlockType.CLAY, Identifier.fromString( "minecraft:clay" ) );
        register( BlockType.CLIENT_REQUEST_PLACEHOLDER_BLOCK, Identifier.fromString( "minecraft:client_request_placeholder_block" ) );
        register( BlockType.COAL_BLOCK, Identifier.fromString( "minecraft:coal_block" ) );
        register( BlockType.COAL_ORE, Identifier.fromString( "minecraft:coal_ore" ), BlockCoalOre.class );
        register( BlockType.COBBLED_DEEPSLATE, Identifier.fromString( "minecraft:cobbled_deepslate" ) );
        register( BlockType.COBBLED_DEEPSLATE_DOUBLE_SLAB, Identifier.fromString( "minecraft:cobbled_deepslate_double_slab" ), BlockDoubleCobbledDeepslateSlab.class );
        register( BlockType.COBBLED_DEEPSLATE_SLAB, Identifier.fromString( "minecraft:cobbled_deepslate_slab" ), BlockCobbledDeepslateSlab.class );
        register( BlockType.COBBLED_DEEPSLATE_STAIRS, Identifier.fromString( "minecraft:cobbled_deepslate_stairs" ), BlockStairs.class );
        register( BlockType.COBBLED_DEEPSLATE_WALL, Identifier.fromString( " minecraft:cobbled_deepslate_wall" ), BlockWall.class );
        register( BlockType.COBBLESTONE, Identifier.fromString( "minecraft:cobblestone" ) );
        register( BlockType.COBBLESTONE_WALL, Identifier.fromString( "minecraft:cobblestone_wall" ), BlockCobblestoneWall.class );
        register( BlockType.COCOA, Identifier.fromString( "minecraft:cocoa" ) );
        register( BlockType.COLORED_TORCH_BP, Identifier.fromString( "minecraft:colored_torch_bp" ) );
        register( BlockType.COLORED_TORCH_RG, Identifier.fromString( "minecraft:colored_torch_rg" ) );
        register( BlockType.COMMAND_BLOCK, Identifier.fromString( "minecraft:command_block" ) );
        register( BlockType.COMPOSTER, Identifier.fromString( "minecraft:composter" ), BlockComposter.class );
        register( BlockType.CONCRETE, Identifier.fromString( "minecraft:concrete" ), BlockConcrete.class );
        register( BlockType.CONCRETE_POWDER, Identifier.fromString( "minecraft:concrete_powder" ), BlockConcretePowder.class );
        register( BlockType.CONDUIT, Identifier.fromString( "minecraft:conduit" ) );
        register( BlockType.COPPER_BLOCK, Identifier.fromString( "minecraft:copper_block" ) );
        register( BlockType.COPPER_ORE, Identifier.fromString( "minecraft:copper_ore" ), BlockCopperOre.class );
        register( BlockType.CORAL, Identifier.fromString( "minecraft:coral" ), BlockCoral.class );
        register( BlockType.CORAL_BLOCK, Identifier.fromString( "minecraft:coral_block" ), BlockCoralBlock.class );
        register( BlockType.CORAL_FAN, Identifier.fromString( "minecraft:coral_fan" ), BlockCoralFan.class );
        register( BlockType.CORAL_FAN_DEAD, Identifier.fromString( "minecraft:coral_fan_dead" ), BlockCoralFanDead.class );
        register( BlockType.CORAL_FAN_HANG, Identifier.fromString( "minecraft:coral_fan_hang" ) );
        register( BlockType.CORAL_FAN_HANG2, Identifier.fromString( "minecraft:coral_fan_hang2" ) );
        register( BlockType.CORAL_FAN_HANG3, Identifier.fromString( "minecraft:coral_fan_hang3" ) );
        register( BlockType.CRACKED_DEEPSLATE_BRICKS, Identifier.fromString( "minecraft:cracked_deepslate_bricks" ) );
        register( BlockType.CRACKED_DEEPSLATE_TILES, Identifier.fromString( "minecraft:cracked_deepslate_tiles" ) );
        register( BlockType.CRACKED_NETHER_BRICKS, Identifier.fromString( "minecraft:cracked_nether_bricks" ) );
        register( BlockType.CRACKED_POLISHED_BLACKSTONE_BRICKS, Identifier.fromString( "minecraft:cracked_polished_blackstone_bricks" ) );
        register( BlockType.CRAFTING_TABLE, Identifier.fromString( "minecraft:crafting_table" ), BlockCraftingTable.class );
        register( BlockType.CRIMSON_BUTTON, Identifier.fromString( "minecraft:crimson_button" ), BlockButton.class );
        register( BlockType.CRIMSON_DOOR, Identifier.fromString( "minecraft:crimson_door" ), BlockDoor.class );
        register( BlockType.CRIMSON_DOUBLE_SLAB, Identifier.fromString( "minecraft:crimson_double_slab" ), BlockDoubleCrimsonSlab.class );
        register( BlockType.CRIMSON_FENCE, Identifier.fromString( "minecraft:crimson_fence" ), BlockFence.class );
        register( BlockType.CRIMSON_FENCE_GATE, Identifier.fromString( "minecraft:crimson_fence_gate" ), BlockFenceGate.class );
        register( BlockType.CRIMSON_FUNGUS, Identifier.fromString( "minecraft:crimson_fungus" ) );
        register( BlockType.CRIMSON_HYPHAE, Identifier.fromString( "minecraft:crimson_hyphae" ), BlockCrimsonHyphae.class );
        register( BlockType.CRIMSON_NYLIUM, Identifier.fromString( "minecraft:crimson_nylium" ) );
        register( BlockType.CRIMSON_PLANKS, Identifier.fromString( "minecraft:crimson_planks" ) );
        register( BlockType.CRIMSON_PRESSURE_PLATE, Identifier.fromString( "minecraft:crimson_pressure_plate" ), BlockPressurePlate.class );
        register( BlockType.CRIMSON_ROOTS, Identifier.fromString( "minecraft:crimson_roots" ) );
        register( BlockType.CRIMSON_SLAB, Identifier.fromString( "minecraft:crimson_slab" ), BlockCrimsonSlab.class );
        register( BlockType.CRIMSON_STAIRS, Identifier.fromString( "minecraft:crimson_stairs" ), BlockStairs.class );
        register( BlockType.CRIMSON_STANDING_SIGN, Identifier.fromString( "minecraft:crimson_standing_sign" ), BlockCrimsonStandingSign.class );
        register( BlockType.CRIMSON_STEM, Identifier.fromString( "minecraft:crimson_stem" ), BlockCrimsonStem.class );
        register( BlockType.CRIMSON_TRAPDOOR, Identifier.fromString( "minecraft:crimson_trapdoor" ), BlockTrapdoor.class );
        register( BlockType.CRIMSON_WALL_SIGN, Identifier.fromString( "minecraft:crimson_wall_sign" ), BlockCrimsonWallSign.class );
        register( BlockType.CRYING_OBSIDIAN, Identifier.fromString( "minecraft:crying_obsidian" ) );
        register( BlockType.CUT_COPPER, Identifier.fromString( "minecraft:cut_copper" ) );
        register( BlockType.CUT_COPPER_SLAB, Identifier.fromString( "minecraft:cut_copper_slab" ), BlockCutCopperSlab.class );
        register( BlockType.CUT_COPPER_STAIRS, Identifier.fromString( "minecraft:cut_copper_stairs" ), BlockStairs.class );
        register( BlockType.CYAN_CANDLE, Identifier.fromString( "minecraft:cyan_candle" ), BlockCandle.class );
        register( BlockType.CYAN_CANDLE_CAKE, Identifier.fromString( "minecraft:cyan_candle_cake" ) );
        register( BlockType.CYAN_GLAZED_TERRACOTTA, Identifier.fromString( "minecraft:cyan_glazed_terracotta" ) );
        register( BlockType.DARKOAK_STANDING_SIGN, Identifier.fromString( "minecraft:darkoak_standing_sign" ), BlockDarkOakStandingSign.class );
        register( BlockType.DARKOAK_WALL_SIGN, Identifier.fromString( "minecraft:darkoak_wall_sign" ), BlockDarkOakWallSign.class );
        register( BlockType.DARK_OAK_BUTTON, Identifier.fromString( "minecraft:dark_oak_button" ), BlockButton.class );
        register( BlockType.DARK_OAK_DOOR, Identifier.fromString( "minecraft:dark_oak_door" ), BlockDoor.class );
        register( BlockType.DARK_OAK_FENCE_GATE, Identifier.fromString( "minecraft:dark_oak_fence_gate" ), BlockFenceGate.class );
        register( BlockType.DARK_OAK_PRESSURE_PLATE, Identifier.fromString( "minecraft:dark_oak_pressure_plate" ), BlockPressurePlate.class );
        register( BlockType.DARK_OAK_STAIRS, Identifier.fromString( "minecraft:dark_oak_stairs" ), BlockStairs.class );
        register( BlockType.DARK_OAK_TRAPDOOR, Identifier.fromString( "minecraft:dark_oak_trapdoor" ), BlockTrapdoor.class );
        register( BlockType.DARK_PRISMARINE_STAIRS, Identifier.fromString( "minecraft:dark_prismarine_stairs" ), BlockStairs.class );
        register( BlockType.DAYLIGHT_DETECTOR, Identifier.fromString( "minecraft:daylight_detector" ), BlockDaylightDetector.class );
        register( BlockType.DAYLIGHT_DETECTOR_INVERTED, Identifier.fromString( "minecraft:daylight_detector_inverted" ), BlockDaylightDetectorInverted.class );
        register( BlockType.DEADBUSH, Identifier.fromString( "minecraft:deadbush" ) );
        register( BlockType.DEEPSLATE, Identifier.fromString( "minecraft:deepslate" ) );
        register( BlockType.DEEPSLATE_BRICKS, Identifier.fromString( "minecraft:deepslate_bricks" ) );
        register( BlockType.DEEPSLATE_BRICK_DOUBLE_SLAB, Identifier.fromString( "minecraft:deepslate_brick_double_slab" ), BlockDoubleDeepslateBrickSlab.class );
        register( BlockType.DEEPSLATE_BRICK_SLAB, Identifier.fromString( "minecraft:deepslate_brick_slab" ), BlockDeepslateBrickSlab.class );
        register( BlockType.DEEPSLATE_BRICK_STAIRS, Identifier.fromString( "minecraft:deepslate_brick_stairs" ), BlockStairs.class );
        register( BlockType.DEEPSLATE_BRICK_WALL, Identifier.fromString( "minecraft:deepslate_brick_wall" ), BlockWall.class );
        register( BlockType.DEEPSLATE_COAL_ORE, Identifier.fromString( "minecraft:deepslate_coal_ore" ), BlockCoalOre.class );
        register( BlockType.DEEPSLATE_COPPER_ORE, Identifier.fromString( "minecraft:deepslate_copper_ore" ), BlockCopperOre.class );
        register( BlockType.DEEPSLATE_DIAMOND_ORE, Identifier.fromString( "minecraft:deepslate_diamond_ore" ), BlockDiamondOre.class );
        register( BlockType.DEEPSLATE_EMERALD_ORE, Identifier.fromString( "minecraft:deepslate_emerald_ore" ), BlockEmeraldOre.class );
        register( BlockType.DEEPSLATE_GOLD_ORE, Identifier.fromString( "minecraft:deepslate_gold_ore" ), BlockGoldOre.class );
        register( BlockType.DEEPSLATE_IRON_ORE, Identifier.fromString( "minecraft:deepslate_iron_ore" ), BlockIronOre.class );
        register( BlockType.DEEPSLATE_LAPIS_ORE, Identifier.fromString( "minecraft:deepslate_lapis_ore" ), BlockLapisOre.class );
        register( BlockType.DEEPSLATE_REDSTONE_ORE, Identifier.fromString( "minecraft:deepslate_redstone_ore" ), BlockRedstoneOre.class );
        register( BlockType.DEEPSLATE_TILES, Identifier.fromString( "minecraft:deepslate_tiles" ) );
        register( BlockType.DEEPSLATE_TILE_DOUBLE_SLAB, Identifier.fromString( "minecraft:deepslate_tile_double_slab" ), BlockDoubleDeepslateTileSlab.class );
        register( BlockType.DEEPSLATE_TILE_SLAB, Identifier.fromString( "minecraft:deepslate_tile_slab" ), BlockDeepslateTileSlab.class );
        register( BlockType.DEEPSLATE_TILE_STAIRS, Identifier.fromString( "minecraft:deepslate_tile_stairs" ), BlockStairs.class );
        register( BlockType.DEEPSLATE_TILE_WALL, Identifier.fromString( "minecraft:deepslate_tile_wall" ), BlockWall.class );
        register( BlockType.DENY, Identifier.fromString( "minecraft:deny" ) );
        register( BlockType.DETECTOR_RAIL, Identifier.fromString( "minecraft:detector_rail" ), BlockRail.class );
        register( BlockType.DIAMOND_BLOCK, Identifier.fromString( "minecraft:diamond_block" ) );
        register( BlockType.DIAMOND_ORE, Identifier.fromString( "minecraft:diamond_ore" ), BlockDiamondOre.class );
        register( BlockType.DIORITE_STAIRS, Identifier.fromString( "minecraft:diorite_stairs" ), BlockStairs.class );
        register( BlockType.DIRT, Identifier.fromString( "minecraft:dirt" ), BlockDirt.class );
        register( BlockType.DIRT_WITH_ROOTS, Identifier.fromString( "minecraft:dirt_with_roots" ) );
        register( BlockType.DISPENSER, Identifier.fromString( "minecraft:dispenser" ), BlockDispenser.class );
        register( BlockType.DOUBLE_CUT_COPPER_SLAB, Identifier.fromString( "minecraft:double_cut_copper_slab" ), BlockDoubleCutCopperSlab.class );
        register( BlockType.DOUBLE_PLANT, Identifier.fromString( "minecraft:double_plant" ), BlockDoublePlant.class );
        register( BlockType.DOUBLE_STONE_BLOCK_SLAB, Identifier.fromString( "minecraft:double_stone_block_slab" ), BlockDoubleStoneSlab.class );
        register( BlockType.DOUBLE_STONE_BLOCK_SLAB2, Identifier.fromString( "minecraft:double_stone_block_slab2" ), BlockDoubleStoneSlab2.class );
        register( BlockType.DOUBLE_STONE_BLOCK_SLAB3, Identifier.fromString( "minecraft:double_stone_block_slab3" ), BlockDoubleStoneSlab3.class );
        register( BlockType.DOUBLE_STONE_BLOCK_SLAB4, Identifier.fromString( "minecraft:double_stone_block_slab4" ), BlockDoubleStoneSlab4.class );
        register( BlockType.DOUBLE_WOODEN_SLAB, Identifier.fromString( "minecraft:double_wooden_slab" ), BlockDoubleWoodenSlab.class );
        register( BlockType.DRAGON_EGG, Identifier.fromString( "minecraft:dragon_egg" ) );
        register( BlockType.DRIED_KELP_BLOCK, Identifier.fromString( "minecraft:dried_kelp_block" ) );
        register( BlockType.DRIPSTONE_BLOCK, Identifier.fromString( "minecraft:dripstone_block" ) );
        register( BlockType.DROPPER, Identifier.fromString( "minecraft:dropper" ), BlockDropper.class );
        register( BlockType.ELEMENT_0, Identifier.fromString( "minecraft:element_0" ) );
        register( BlockType.ELEMENT_1, Identifier.fromString( "minecraft:element_1" ) );
        register( BlockType.ELEMENT_10, Identifier.fromString( "minecraft:element_10" ) );
        register( BlockType.ELEMENT_100, Identifier.fromString( "minecraft:element_100" ) );
        register( BlockType.ELEMENT_101, Identifier.fromString( "minecraft:element_101" ) );
        register( BlockType.ELEMENT_102, Identifier.fromString( "minecraft:element_102" ) );
        register( BlockType.ELEMENT_103, Identifier.fromString( "minecraft:element_103" ) );
        register( BlockType.ELEMENT_104, Identifier.fromString( "minecraft:element_104" ) );
        register( BlockType.ELEMENT_105, Identifier.fromString( "minecraft:element_105" ) );
        register( BlockType.ELEMENT_106, Identifier.fromString( "minecraft:element_106" ) );
        register( BlockType.ELEMENT_107, Identifier.fromString( "minecraft:element_107" ) );
        register( BlockType.ELEMENT_108, Identifier.fromString( "minecraft:element_108" ) );
        register( BlockType.ELEMENT_109, Identifier.fromString( "minecraft:element_109" ) );
        register( BlockType.ELEMENT_11, Identifier.fromString( "minecraft:element_11" ) );
        register( BlockType.ELEMENT_110, Identifier.fromString( "minecraft:element_110" ) );
        register( BlockType.ELEMENT_111, Identifier.fromString( "minecraft:element_111" ) );
        register( BlockType.ELEMENT_112, Identifier.fromString( "minecraft:element_112" ) );
        register( BlockType.ELEMENT_113, Identifier.fromString( "minecraft:element_113" ) );
        register( BlockType.ELEMENT_114, Identifier.fromString( "minecraft:element_114" ) );
        register( BlockType.ELEMENT_115, Identifier.fromString( "minecraft:element_115" ) );
        register( BlockType.ELEMENT_116, Identifier.fromString( "minecraft:element_116" ) );
        register( BlockType.ELEMENT_117, Identifier.fromString( "minecraft:element_117" ) );
        register( BlockType.ELEMENT_118, Identifier.fromString( "minecraft:element_118" ) );
        register( BlockType.ELEMENT_12, Identifier.fromString( "minecraft:element_12" ) );
        register( BlockType.ELEMENT_13, Identifier.fromString( "minecraft:element_13" ) );
        register( BlockType.ELEMENT_14, Identifier.fromString( "minecraft:element_14" ) );
        register( BlockType.ELEMENT_15, Identifier.fromString( "minecraft:element_15" ) );
        register( BlockType.ELEMENT_16, Identifier.fromString( "minecraft:element_16" ) );
        register( BlockType.ELEMENT_17, Identifier.fromString( "minecraft:element_17" ) );
        register( BlockType.ELEMENT_18, Identifier.fromString( "minecraft:element_18" ) );
        register( BlockType.ELEMENT_19, Identifier.fromString( "minecraft:element_19" ) );
        register( BlockType.ELEMENT_2, Identifier.fromString( "minecraft:element_2" ) );
        register( BlockType.ELEMENT_20, Identifier.fromString( "minecraft:element_20" ) );
        register( BlockType.ELEMENT_21, Identifier.fromString( "minecraft:element_21" ) );
        register( BlockType.ELEMENT_22, Identifier.fromString( "minecraft:element_22" ) );
        register( BlockType.ELEMENT_23, Identifier.fromString( "minecraft:element_23" ) );
        register( BlockType.ELEMENT_24, Identifier.fromString( "minecraft:element_24" ) );
        register( BlockType.ELEMENT_25, Identifier.fromString( "minecraft:element_25" ) );
        register( BlockType.ELEMENT_26, Identifier.fromString( "minecraft:element_26" ) );
        register( BlockType.ELEMENT_27, Identifier.fromString( "minecraft:element_27" ) );
        register( BlockType.ELEMENT_28, Identifier.fromString( "minecraft:element_28" ) );
        register( BlockType.ELEMENT_29, Identifier.fromString( "minecraft:element_29" ) );
        register( BlockType.ELEMENT_3, Identifier.fromString( "minecraft:element_3" ) );
        register( BlockType.ELEMENT_30, Identifier.fromString( "minecraft:element_30" ) );
        register( BlockType.ELEMENT_31, Identifier.fromString( "minecraft:element_31" ) );
        register( BlockType.ELEMENT_32, Identifier.fromString( "minecraft:element_32" ) );
        register( BlockType.ELEMENT_33, Identifier.fromString( "minecraft:element_33" ) );
        register( BlockType.ELEMENT_34, Identifier.fromString( "minecraft:element_34" ) );
        register( BlockType.ELEMENT_35, Identifier.fromString( "minecraft:element_35" ) );
        register( BlockType.ELEMENT_36, Identifier.fromString( "minecraft:element_36" ) );
        register( BlockType.ELEMENT_37, Identifier.fromString( "minecraft:element_37" ) );
        register( BlockType.ELEMENT_38, Identifier.fromString( "minecraft:element_38" ) );
        register( BlockType.ELEMENT_39, Identifier.fromString( "minecraft:element_39" ) );
        register( BlockType.ELEMENT_4, Identifier.fromString( "minecraft:element_4" ) );
        register( BlockType.ELEMENT_40, Identifier.fromString( "minecraft:element_40" ) );
        register( BlockType.ELEMENT_41, Identifier.fromString( "minecraft:element_41" ) );
        register( BlockType.ELEMENT_42, Identifier.fromString( "minecraft:element_42" ) );
        register( BlockType.ELEMENT_43, Identifier.fromString( "minecraft:element_43" ) );
        register( BlockType.ELEMENT_44, Identifier.fromString( "minecraft:element_44" ) );
        register( BlockType.ELEMENT_45, Identifier.fromString( "minecraft:element_45" ) );
        register( BlockType.ELEMENT_46, Identifier.fromString( "minecraft:element_46" ) );
        register( BlockType.ELEMENT_47, Identifier.fromString( "minecraft:element_47" ) );
        register( BlockType.ELEMENT_48, Identifier.fromString( "minecraft:element_48" ) );
        register( BlockType.ELEMENT_49, Identifier.fromString( "minecraft:element_49" ) );
        register( BlockType.ELEMENT_5, Identifier.fromString( "minecraft:element_5" ) );
        register( BlockType.ELEMENT_50, Identifier.fromString( "minecraft:element_50" ) );
        register( BlockType.ELEMENT_51, Identifier.fromString( "minecraft:element_51" ) );
        register( BlockType.ELEMENT_52, Identifier.fromString( "minecraft:element_52" ) );
        register( BlockType.ELEMENT_53, Identifier.fromString( "minecraft:element_53" ) );
        register( BlockType.ELEMENT_54, Identifier.fromString( "minecraft:element_54" ) );
        register( BlockType.ELEMENT_55, Identifier.fromString( "minecraft:element_55" ) );
        register( BlockType.ELEMENT_56, Identifier.fromString( "minecraft:element_56" ) );
        register( BlockType.ELEMENT_57, Identifier.fromString( "minecraft:element_57" ) );
        register( BlockType.ELEMENT_58, Identifier.fromString( "minecraft:element_58" ) );
        register( BlockType.ELEMENT_59, Identifier.fromString( "minecraft:element_59" ) );
        register( BlockType.ELEMENT_6, Identifier.fromString( "minecraft:element_6" ) );
        register( BlockType.ELEMENT_60, Identifier.fromString( "minecraft:element_60" ) );
        register( BlockType.ELEMENT_61, Identifier.fromString( "minecraft:element_61" ) );
        register( BlockType.ELEMENT_62, Identifier.fromString( "minecraft:element_62" ) );
        register( BlockType.ELEMENT_63, Identifier.fromString( "minecraft:element_63" ) );
        register( BlockType.ELEMENT_64, Identifier.fromString( "minecraft:element_64" ) );
        register( BlockType.ELEMENT_65, Identifier.fromString( "minecraft:element_65" ) );
        register( BlockType.ELEMENT_66, Identifier.fromString( "minecraft:element_66" ) );
        register( BlockType.ELEMENT_67, Identifier.fromString( "minecraft:element_67" ) );
        register( BlockType.ELEMENT_68, Identifier.fromString( "minecraft:element_68" ) );
        register( BlockType.ELEMENT_69, Identifier.fromString( "minecraft:element_69" ) );
        register( BlockType.ELEMENT_7, Identifier.fromString( "minecraft:element_7" ) );
        register( BlockType.ELEMENT_70, Identifier.fromString( "minecraft:element_70" ) );
        register( BlockType.ELEMENT_71, Identifier.fromString( "minecraft:element_71" ) );
        register( BlockType.ELEMENT_72, Identifier.fromString( "minecraft:element_72" ) );
        register( BlockType.ELEMENT_73, Identifier.fromString( "minecraft:element_73" ) );
        register( BlockType.ELEMENT_74, Identifier.fromString( "minecraft:element_74" ) );
        register( BlockType.ELEMENT_75, Identifier.fromString( "minecraft:element_75" ) );
        register( BlockType.ELEMENT_76, Identifier.fromString( "minecraft:element_76" ) );
        register( BlockType.ELEMENT_77, Identifier.fromString( "minecraft:element_77" ) );
        register( BlockType.ELEMENT_78, Identifier.fromString( "minecraft:element_78" ) );
        register( BlockType.ELEMENT_79, Identifier.fromString( "minecraft:element_79" ) );
        register( BlockType.ELEMENT_8, Identifier.fromString( "minecraft:element_8" ) );
        register( BlockType.ELEMENT_80, Identifier.fromString( "minecraft:element_80" ) );
        register( BlockType.ELEMENT_81, Identifier.fromString( "minecraft:element_81" ) );
        register( BlockType.ELEMENT_82, Identifier.fromString( "minecraft:element_82" ) );
        register( BlockType.ELEMENT_83, Identifier.fromString( "minecraft:element_83" ) );
        register( BlockType.ELEMENT_84, Identifier.fromString( "minecraft:element_84" ) );
        register( BlockType.ELEMENT_85, Identifier.fromString( "minecraft:element_85" ) );
        register( BlockType.ELEMENT_86, Identifier.fromString( "minecraft:element_86" ) );
        register( BlockType.ELEMENT_87, Identifier.fromString( "minecraft:element_87" ) );
        register( BlockType.ELEMENT_88, Identifier.fromString( "minecraft:element_88" ) );
        register( BlockType.ELEMENT_89, Identifier.fromString( "minecraft:element_89" ) );
        register( BlockType.ELEMENT_9, Identifier.fromString( "minecraft:element_9" ) );
        register( BlockType.ELEMENT_90, Identifier.fromString( "minecraft:element_90" ) );
        register( BlockType.ELEMENT_91, Identifier.fromString( "minecraft:element_91" ) );
        register( BlockType.ELEMENT_92, Identifier.fromString( "minecraft:element_92" ) );
        register( BlockType.ELEMENT_93, Identifier.fromString( "minecraft:element_93" ) );
        register( BlockType.ELEMENT_94, Identifier.fromString( "minecraft:element_94" ) );
        register( BlockType.ELEMENT_95, Identifier.fromString( "minecraft:element_95" ) );
        register( BlockType.ELEMENT_96, Identifier.fromString( "minecraft:element_96" ) );
        register( BlockType.ELEMENT_97, Identifier.fromString( "minecraft:element_97" ) );
        register( BlockType.ELEMENT_98, Identifier.fromString( "minecraft:element_98" ) );
        register( BlockType.ELEMENT_99, Identifier.fromString( "minecraft:element_99" ) );
        register( BlockType.EMERALD_BLOCK, Identifier.fromString( "minecraft:emerald_block" ) );
        register( BlockType.EMERALD_ORE, Identifier.fromString( "minecraft:emerald_ore" ), BlockEmeraldOre.class );
        register( BlockType.ENCHANTING_TABLE, Identifier.fromString( "minecraft:enchanting_table" ), BlockEnchantingTable.class );
        register( BlockType.ENDER_CHEST, Identifier.fromString( "minecraft:ender_chest" ), BlockEnderChest.class );
        register( BlockType.END_BRICKS, Identifier.fromString( "minecraft:end_bricks" ) );
        register( BlockType.END_BRICK_STAIRS, Identifier.fromString( "minecraft:end_brick_stairs" ), BlockStairs.class );
        register( BlockType.END_GATEWAY, Identifier.fromString( "minecraft:end_gateway" ) );
        register( BlockType.END_PORTAL, Identifier.fromString( "minecraft:end_portal" ) );
        register( BlockType.END_PORTAL_FRAME, Identifier.fromString( "minecraft:end_portal_frame" ), BlockEndPortalFrame.class );
        register( BlockType.END_ROD, Identifier.fromString( "minecraft:end_rod" ), BlockEndRod.class );
        register( BlockType.END_STONE, Identifier.fromString( "minecraft:end_stone" ) );
        register( BlockType.EXPOSED_COPPER, Identifier.fromString( "minecraft:exposed_copper" ) );
        register( BlockType.EXPOSED_CUT_COPPER, Identifier.fromString( "minecraft:exposed_cut_copper" ) );
        register( BlockType.EXPOSED_CUT_COPPER_SLAB, Identifier.fromString( "minecraft:exposed_cut_copper_slab" ), BlockExposedCutCopperSlab.class );
        register( BlockType.EXPOSED_CUT_COPPER_STAIRS, Identifier.fromString( "minecraft:exposed_cut_copper_stairs" ), BlockStairs.class );
        register( BlockType.EXPOSED_DOUBLE_CUT_COPPER_SLAB, Identifier.fromString( "minecraft:exposed_double_cut_copper_slab" ), BlockDoubleExposedCutCopperSlab.class );
        register( BlockType.FARMLAND, Identifier.fromString( "minecraft:farmland" ) );
        register( BlockType.FENCE, Identifier.fromString( "minecraft:fence" ), BlockWoodenFence.class );
        register( BlockType.FENCE_GATE, Identifier.fromString( "minecraft:fence_gate" ), BlockFenceGate.class );
        register( BlockType.FIRE, Identifier.fromString( "minecraft:fire" ) );
        register( BlockType.FLETCHING_TABLE, Identifier.fromString( "minecraft:fletching_table" ) );
        register( BlockType.FLOWERING_AZALEA, Identifier.fromString( "minecraft:flowering_azalea" ) );
        register( BlockType.FLOWER_POT, Identifier.fromString( "minecraft:flower_pot" ) );
        register( BlockType.FLOWING_LAVA, Identifier.fromString( "minecraft:flowing_lava" ), BlockLava.class );
        register( BlockType.FLOWING_WATER, Identifier.fromString( "minecraft:flowing_water" ), BlockWater.class );
        register( BlockType.FRAME, Identifier.fromString( "minecraft:frame" ) );
        register( BlockType.FROG_SPAWN, Identifier.fromString( "minecraft:frog_spawn" ) );
        register( BlockType.FROSTED_ICE, Identifier.fromString( "minecraft:frosted_ice" ) );
        register( BlockType.FURNACE, Identifier.fromString( "minecraft:furnace" ), BlockFurnace.class );
        register( BlockType.GILDED_BLACKSTONE, Identifier.fromString( "minecraft:gilded_blackstone" ) );
        register( BlockType.GLASS, Identifier.fromString( "minecraft:glass" ) );
        register( BlockType.GLASS_PANE, Identifier.fromString( "minecraft:glass_pane" ) );
        register( BlockType.GLOWINGOBSIDIAN, Identifier.fromString( "minecraft:glowingobsidian" ) );
        register( BlockType.GLOWSTONE, Identifier.fromString( "minecraft:glowstone" ) );
        register( BlockType.GLOW_FRAME, Identifier.fromString( "minecraft:glow_frame" ) );
        register( BlockType.GLOW_LICHEN, Identifier.fromString( "minecraft:glow_lichen" ) );
        register( BlockType.GOLDEN_RAIL, Identifier.fromString( "minecraft:golden_rail" ), BlockRail.class );
        register( BlockType.GOLD_BLOCK, Identifier.fromString( "minecraft:gold_block" ) );
        register( BlockType.GOLD_ORE, Identifier.fromString( "minecraft:gold_ore" ), BlockGoldOre.class );
        register( BlockType.GRANITE_STAIRS, Identifier.fromString( "minecraft:granite_stairs" ), BlockStairs.class );
        register( BlockType.GRASS, Identifier.fromString( "minecraft:grass" ), BlockGrass.class );
        register( BlockType.GRASS_PATH, Identifier.fromString( "minecraft:grass_path" ) );
        register( BlockType.GRAVEL, Identifier.fromString( "minecraft:gravel" ), BlockGravel.class );
        register( BlockType.GRAY_CANDLE, Identifier.fromString( "minecraft:gray_candle" ), BlockCandle.class );
        register( BlockType.GRAY_CANDLE_CAKE, Identifier.fromString( "minecraft:gray_candle_cake" ) );
        register( BlockType.GRAY_GLAZED_TERRACOTTA, Identifier.fromString( "minecraft:gray_glazed_terracotta" ) );
        register( BlockType.GREEN_CANDLE, Identifier.fromString( "minecraft:green_candle" ), BlockCandle.class );
        register( BlockType.GREEN_CANDLE_CAKE, Identifier.fromString( "minecraft:green_candle_cake" ) );
        register( BlockType.GREEN_GLAZED_TERRACOTTA, Identifier.fromString( "minecraft:green_glazed_terracotta" ) );
        register( BlockType.GRINDSTONE, Identifier.fromString( "minecraft:grindstone" ), BlockGrindstone.class );
        register( BlockType.HANGING_ROOTS, Identifier.fromString( "minecraft:hanging_roots" ), BlockHangingRoots.class );
        register( BlockType.HARDENED_CLAY, Identifier.fromString( "minecraft:hardened_clay" ) );
        register( BlockType.HARD_GLASS, Identifier.fromString( "minecraft:hard_glass" ) );
        register( BlockType.HARD_GLASS_PANE, Identifier.fromString( "minecraft:hard_glass_pane" ) );
        register( BlockType.HARD_STAINED_GLASS, Identifier.fromString( "minecraft:hard_stained_glass" ) );
        register( BlockType.HARD_STAINED_GLASS_PANE, Identifier.fromString( "minecraft:hard_stained_glass_pane" ) );
        register( BlockType.HAY_BLOCK, Identifier.fromString( "minecraft:hay_block" ) );
        register( BlockType.HEAVY_WEIGHTED_PRESSURE_PLATE, Identifier.fromString( "minecraft:heavy_weighted_pressure_plate" ), BlockPressurePlate.class );
        register( BlockType.HONEYCOMB_BLOCK, Identifier.fromString( "minecraft:honeycomb_block" ) );
        register( BlockType.HONEY_BLOCK, Identifier.fromString( "minecraft:honey_block" ) );
        register( BlockType.HOPPER, Identifier.fromString( "minecraft:hopper" ), BlockHopper.class );
        register( BlockType.ICE, Identifier.fromString( "minecraft:ice" ) );
        register( BlockType.INFESTED_DEEPSLATE, Identifier.fromString( "minecraft:infested_deepslate" ) );
        register( BlockType.INFO_UPDATE, Identifier.fromString( "minecraft:info_update" ) );
        register( BlockType.INFO_UPDATE2, Identifier.fromString( "minecraft:info_update2" ) );
        register( BlockType.INVISIBLE_BEDROCK, Identifier.fromString( "minecraft:invisible_bedrock" ) );
        register( BlockType.IRON_BARS, Identifier.fromString( "minecraft:iron_bars" ) );
        register( BlockType.IRON_BLOCK, Identifier.fromString( "minecraft:iron_block" ) );
        register( BlockType.IRON_DOOR, Identifier.fromString( "minecraft:iron_door" ), BlockDoor.class );
        register( BlockType.IRON_ORE, Identifier.fromString( "minecraft:iron_ore" ), BlockIronOre.class );
        register( BlockType.IRON_TRAPDOOR, Identifier.fromString( "minecraft:iron_trapdoor" ), BlockTrapdoor.class );
        register( BlockType.JIGSAW, Identifier.fromString( "minecraft:jigsaw" ) );
        register( BlockType.JUKEBOX, Identifier.fromString( "minecraft:jukebox" ) );
        register( BlockType.JUNGLE_BUTTON, Identifier.fromString( "minecraft:jungle_button" ), BlockButton.class );
        register( BlockType.JUNGLE_DOOR, Identifier.fromString( "minecraft:jungle_door" ), BlockDoor.class );
        register( BlockType.JUNGLE_FENCE_GATE, Identifier.fromString( "minecraft:jungle_fence_gate" ), BlockFenceGate.class );
        register( BlockType.JUNGLE_PRESSURE_PLATE, Identifier.fromString( "minecraft:jungle_pressure_plate" ), BlockPressurePlate.class );
        register( BlockType.JUNGLE_STAIRS, Identifier.fromString( "minecraft:jungle_stairs" ), BlockStairs.class );
        register( BlockType.JUNGLE_STANDING_SIGN, Identifier.fromString( "minecraft:jungle_standing_sign" ), BlockJungleStandingSign.class );
        register( BlockType.JUNGLE_TRAPDOOR, Identifier.fromString( "minecraft:jungle_trapdoor" ), BlockTrapdoor.class );
        register( BlockType.JUNGLE_WALL_SIGN, Identifier.fromString( "minecraft:jungle_wall_sign" ), BlockJungleWallSign.class );
        register( BlockType.KELP, Identifier.fromString( "minecraft:kelp" ), BlockKelp.class );
        register( BlockType.LADDER, Identifier.fromString( "minecraft:ladder" ), BlockLadder.class );
        register( BlockType.LANTERN, Identifier.fromString( "minecraft:lantern" ), BlockLantern.class );
        register( BlockType.LAPIS_BLOCK, Identifier.fromString( "minecraft:lapis_block" ) );
        register( BlockType.LAPIS_ORE, Identifier.fromString( "minecraft:lapis_ore" ), BlockLapisOre.class );
        register( BlockType.LARGE_AMETHYST_BUD, Identifier.fromString( "minecraft:large_amethyst_bud" ) );
        register( BlockType.LAVA, Identifier.fromString( "minecraft:lava" ), BlockLava.class );
        register( BlockType.LAVA_CAULDRON, Identifier.fromString( "minecraft:lava_cauldron" ) );
        register( BlockType.LEAVES, Identifier.fromString( "minecraft:leaves" ), BlockLeaves.class );
        register( BlockType.LEAVES2, Identifier.fromString( "minecraft:leaves2" ), BlockLeaves2.class );
        register( BlockType.LECTERN, Identifier.fromString( "minecraft:lectern" ), BlockLectern.class );
        register( BlockType.LEVER, Identifier.fromString( "minecraft:lever" ), BlockLever.class );
        register( BlockType.LIGHTNING_ROD, Identifier.fromString( "minecraft:lightning_rod" ), BlockLightningRod.class );
        register( BlockType.LIGHT_BLOCK, Identifier.fromString( "minecraft:light_block" ) );
        register( BlockType.LIGHT_BLUE_CANDLE, Identifier.fromString( "minecraft:light_blue_candle" ), BlockCandle.class );
        register( BlockType.LIGHT_BLUE_CANDLE_CAKE, Identifier.fromString( "minecraft:light_blue_candle_cake" ) );
        register( BlockType.LIGHT_BLUE_GLAZED_TERRACOTTA, Identifier.fromString( "minecraft:light_blue_glazed_terracotta" ) );
        register( BlockType.LIGHT_GRAY_CANDLE, Identifier.fromString( "minecraft:light_gray_candle" ), BlockCandle.class );
        register( BlockType.LIGHT_GRAY_CANDLE_CAKE, Identifier.fromString( "minecraft:light_gray_candle_cake" ) );
        register( BlockType.LIGHT_WEIGHTED_PRESSURE_PLATE, Identifier.fromString( "minecraft:light_weighted_pressure_plate" ), BlockPressurePlate.class );
        register( BlockType.LIME_CANDLE, Identifier.fromString( "minecraft:lime_candle" ), BlockCandle.class );
        register( BlockType.LIME_CANDLE_CAKE, Identifier.fromString( "minecraft:lime_candle_cake" ) );
        register( BlockType.LIME_GLAZED_TERRACOTTA, Identifier.fromString( "minecraft:lime_glazed_terracotta" ) );
        register( BlockType.LIT_BLAST_FURNACE, Identifier.fromString( "minecraft:lit_blast_furnace" ), BlockBlastFurnace.class );
        register( BlockType.LIT_DEEPSLATE_REDSTONE_ORE, Identifier.fromString( "minecraft:lit_deepslate_redstone_ore" ), BlockRedstoneOre.class );
        register( BlockType.LIT_FURNACE, Identifier.fromString( "minecraft:lit_furnace" ), BlockFurnace.class );
        register( BlockType.LIT_PUMPKIN, Identifier.fromString( "minecraft:lit_pumpkin" ) );
        register( BlockType.LIT_REDSTONE_LAMP, Identifier.fromString( "minecraft:lit_redstone_lamp" ) );
        register( BlockType.LIT_REDSTONE_ORE, Identifier.fromString( "minecraft:lit_redstone_ore" ), BlockRedstoneOre.class );
        register( BlockType.LIT_SMOKER, Identifier.fromString( "minecraft:lit_smoker" ) );
        register( BlockType.LODESTONE, Identifier.fromString( "minecraft:lodestone" ) );
        register( BlockType.LOG, Identifier.fromString( "minecraft:log" ), BlockLog.class );
        register( BlockType.LOG2, Identifier.fromString( "minecraft:log2" ), BlockLog2.class );
        register( BlockType.LOOM, Identifier.fromString( "minecraft:loom" ) );
        register( BlockType.MAGENTA_CANDLE, Identifier.fromString( "minecraft:magenta_candle" ), BlockCandle.class );
        register( BlockType.MAGENTA_CANDLE_CAKE, Identifier.fromString( "minecraft:magenta_candle_cake" ) );
        register( BlockType.MAGENTA_GLAZED_TERRACOTTA, Identifier.fromString( "minecraft:magenta_glazed_terracotta" ) );
        register( BlockType.MAGMA, Identifier.fromString( "minecraft:magma" ) );
        register( BlockType.MANGROVE_BUTTON, Identifier.fromString( "minecraft:mangrove_button" ), BlockButton.class );
        register( BlockType.MANGROVE_DOOR, Identifier.fromString( "minecraft:mangrove_door" ), BlockDoor.class );
        register( BlockType.MANGROVE_DOUBLE_SLAB, Identifier.fromString( "minecraft:mangrove_double_slab" ), BlockDoubleMangroveSlab.class );
        register( BlockType.MANGROVE_FENCE, Identifier.fromString( "minecraft:mangrove_fence" ), BlockFence.class );
        register( BlockType.MANGROVE_FENCE_GATE, Identifier.fromString( "minecraft:mangrove_fence_gate" ), BlockFenceGate.class );
        register( BlockType.MANGROVE_LEAVES, Identifier.fromString( "minecraft:mangrove_leaves" ) );
        register( BlockType.MANGROVE_LOG, Identifier.fromString( "minecraft:mangrove_log" ), BlockMangroveLog.class );
        register( BlockType.MANGROVE_PLANKS, Identifier.fromString( "minecraft:mangrove_planks" ) );
        register( BlockType.MANGROVE_PRESSURE_PLATE, Identifier.fromString( "minecraft:mangrove_pressure_plate" ), BlockPressurePlate.class );
        register( BlockType.MANGROVE_PROPAGULE, Identifier.fromString( "minecraft:mangrove_propagule" ) );
        register( BlockType.MANGROVE_ROOTS, Identifier.fromString( "minecraft:mangrove_roots" ) );
        register( BlockType.MANGROVE_SLAB, Identifier.fromString( "minecraft:mangrove_slab" ), BlockMangroveSlab.class );
        register( BlockType.MANGROVE_STAIRS, Identifier.fromString( "minecraft:mangrove_stairs" ), BlockStairs.class );
        register( BlockType.MANGROVE_STANDING_SIGN, Identifier.fromString( "minecraft:mangrove_standing_sign" ), BlockMangroveStandingSign.class );
        register( BlockType.MANGROVE_TRAPDOOR, Identifier.fromString( "minecraft:mangrove_trapdoor" ), BlockTrapdoor.class );
        register( BlockType.MANGROVE_WALL_SIGN, Identifier.fromString( "minecraft:mangrove_wall_sign" ), BlockMangroveWallSign.class );
        register( BlockType.MANGROVE_WOOD, Identifier.fromString( "minecraft:mangrove_wood" ), BlockMangroveWood.class );
        register( BlockType.MEDIUM_AMETHYST_BUD, Identifier.fromString( "minecraft:medium_amethyst_bud" ) );
        register( BlockType.MELON_BLOCK, Identifier.fromString( "minecraft:melon_block" ) );
        register( BlockType.MELON_STEM, Identifier.fromString( "minecraft:melon_stem" ) );
        register( BlockType.MOB_SPAWNER, Identifier.fromString( "minecraft:mob_spawner" ) );
        register( BlockType.INFESTED_STONE, Identifier.fromString( "minecraft:monster_egg" ) );
        register( BlockType.MOSSY_COBBLESTONE, Identifier.fromString( "minecraft:mossy_cobblestone" ) );
        register( BlockType.MOSSY_COBBLESTONE_STAIRS, Identifier.fromString( "minecraft:mossy_cobblestone_stairs" ), BlockStairs.class );
        register( BlockType.MOSSY_STONE_BRICK_STAIRS, Identifier.fromString( "minecraft:mossy_stone_brick_stairs" ), BlockStairs.class );
        register( BlockType.MOSS_BLOCK, Identifier.fromString( "minecraft:moss_block" ) );
        register( BlockType.MOSS_CARPET, Identifier.fromString( "minecraft:moss_carpet" ) );
        register( BlockType.MOVING_BLOCK, Identifier.fromString( "minecraft:moving_block" ) );
        register( BlockType.MUD, Identifier.fromString( "minecraft:mud" ) );
        register( BlockType.MUDDY_MANGROVE_ROOTS, Identifier.fromString( "minecraft:muddy_mangrove_roots" ), BlockMuddyMangroveRoots.class );
        register( BlockType.MUD_BRICKS, Identifier.fromString( "minecraft:mud_bricks" ) );
        register( BlockType.MUD_BRICK_DOUBLE_SLAB, Identifier.fromString( "minecraft:mud_brick_double_slab" ), BlockDoubleMudBrickSlab.class );
        register( BlockType.MUD_BRICK_SLAB, Identifier.fromString( "minecraft:mud_brick_slab" ), BlockMudBrickSlab.class );
        register( BlockType.MUD_BRICK_STAIRS, Identifier.fromString( "minecraft:mud_brick_stairs" ), BlockStairs.class );
        register( BlockType.MUD_BRICK_WALL, Identifier.fromString( "minecraft:mud_brick_wall" ), BlockWall.class );
        register( BlockType.MYCELIUM, Identifier.fromString( "minecraft:mycelium" ) );
        register( BlockType.NETHERITE_BLOCK, Identifier.fromString( "minecraft:netherite_block" ) );
        register( BlockType.NETHERRACK, Identifier.fromString( "minecraft:netherrack" ) );
        register( BlockType.NETHERREACTOR, Identifier.fromString( "minecraft:netherreactor" ) );
        register( BlockType.NETHER_BRICK, Identifier.fromString( "minecraft:nether_brick" ) );
        register( BlockType.NETHER_BRICK_FENCE, Identifier.fromString( "minecraft:nether_brick_fence" ), BlockFence.class );
        register( BlockType.NETHER_BRICK_STAIRS, Identifier.fromString( "minecraft:nether_brick_stairs" ), BlockStairs.class );
        register( BlockType.NETHER_GOLD_ORE, Identifier.fromString( "minecraft:nether_gold_ore" ), BlockNetherGoldOre.class );
        register( BlockType.NETHER_SPROUTS, Identifier.fromString( "minecraft:nether_sprouts" ) );
        register( BlockType.NETHER_WART, Identifier.fromString( "minecraft:nether_wart" ), BlockNetherWart.class );
        register( BlockType.NETHER_WART_BLOCK, Identifier.fromString( "minecraft:nether_wart_block" ) );
        register( BlockType.NORMAL_STONE_STAIRS, Identifier.fromString( "minecraft:normal_stone_stairs" ), BlockStairs.class );
        register( BlockType.NOTEBLOCK, Identifier.fromString( "minecraft:noteblock" ) );
        register( BlockType.OAK_STAIRS, Identifier.fromString( "minecraft:oak_stairs" ), BlockStairs.class );
        register( BlockType.OBSERVER, Identifier.fromString( "minecraft:observer" ) );
        register( BlockType.OBSIDIAN, Identifier.fromString( "minecraft:obsidian" ) );
        register( BlockType.OCHRE_FROGLIGHT, Identifier.fromString( "minecraft:ochre_froglight" ) );
        register( BlockType.ORANGE_CANDLE, Identifier.fromString( "minecraft:orange_candle" ), BlockCandle.class );
        register( BlockType.ORANGE_CANDLE_CAKE, Identifier.fromString( "minecraft:orange_candle_cake" ) );
        register( BlockType.ORANGE_GLAZED_TERRACOTTA, Identifier.fromString( "minecraft:orange_glazed_terracotta" ) );
        register( BlockType.OXIDIZED_COPPER, Identifier.fromString( "minecraft:oxidized_copper" ) );
        register( BlockType.OXIDIZED_CUT_COPPER, Identifier.fromString( "minecraft:oxidized_cut_copper" ) );
        register( BlockType.OXIDIZED_CUT_COPPER_SLAB, Identifier.fromString( "minecraft:oxidized_cut_copper_slab" ), BlockOxidizedCutCopperSlab.class );
        register( BlockType.OXIDIZED_CUT_COPPER_STAIRS, Identifier.fromString( "minecraft:oxidized_cut_copper_stairs" ), BlockStairs.class );
        register( BlockType.OXIDIZED_DOUBLE_CUT_COPPER_SLAB, Identifier.fromString( "minecraft:oxidized_double_cut_copper_slab" ), BlockDoubleOxidizedCutCopperSlab.class );
        register( BlockType.PACKED_ICE, Identifier.fromString( "minecraft:packed_ice" ) );
        register( BlockType.PACKED_MUD, Identifier.fromString( "minecraft:packed_mud" ) );
        register( BlockType.PEARLESCENT_FROGLIGHT, Identifier.fromString( "minecraft:pearlescent_froglight" ) );
        register( BlockType.PINK_CANDLE, Identifier.fromString( "minecraft:pink_candle" ), BlockCandle.class );
        register( BlockType.PINK_CANDLE_CAKE, Identifier.fromString( "minecraft:pink_candle_cake" ) );
        register( BlockType.PINK_GLAZED_TERRACOTTA, Identifier.fromString( "minecraft:pink_glazed_terracotta" ) );
        register( BlockType.PISTON, Identifier.fromString( "minecraft:piston" ), BlockPiston.class );
        register( BlockType.PISTON_ARM_COLLISION, Identifier.fromString( "minecraft:piston_arm_collision" ) );
        register( BlockType.PLANKS, Identifier.fromString( "minecraft:planks" ), BlockPlanks.class );
        register( BlockType.PODZOL, Identifier.fromString( "minecraft:podzol" ) );
        register( BlockType.POINTED_DRIPSTONE, Identifier.fromString( "minecraft:pointed_dripstone" ), BlockPointedDripstone.class );
        register( BlockType.POLISHED_ANDESITE_STAIRS, Identifier.fromString( "minecraft:polished_andesite_stairs" ), BlockStairs.class );
        register( BlockType.POLISHED_BASALT, Identifier.fromString( "minecraft:polished_basalt" ), BlockPolishedBasalt.class );
        register( BlockType.POLISHED_BLACKSTONE, Identifier.fromString( "minecraft:polished_blackstone" ) );
        register( BlockType.POLISHED_BLACKSTONE_BRICKS, Identifier.fromString( "minecraft:polished_blackstone_bricks" ) );
        register( BlockType.POLISHED_BLACKSTONE_BRICK_DOUBLE_SLAB, Identifier.fromString( "minecraft:polished_blackstone_brick_double_slab" ), BlockDoublePolishedBlackstoneBrickSlab.class );
        register( BlockType.POLISHED_BLACKSTONE_BRICK_SLAB, Identifier.fromString( "minecraft:polished_blackstone_brick_slab" ), BlockPolishedBlackstoneBrickSlab.class );
        register( BlockType.POLISHED_BLACKSTONE_BRICK_STAIRS, Identifier.fromString( "minecraft:polished_blackstone_brick_stairs" ), BlockStairs.class );
        register( BlockType.POLISHED_BLACKSTONE_BRICK_WALL, Identifier.fromString( "minecraft:polished_blackstone_brick_wall" ), BlockWall.class );
        register( BlockType.POLISHED_BLACKSTONE_BUTTON, Identifier.fromString( "minecraft:polished_blackstone_button" ), BlockButton.class );
        register( BlockType.POLISHED_BLACKSTONE_DOUBLE_SLAB, Identifier.fromString( "minecraft:polished_blackstone_double_slab" ), BlockDoublePolishedBlackstoneSlab.class );
        register( BlockType.POLISHED_BLACKSTONE_PRESSURE_PLATE, Identifier.fromString( "minecraft:polished_blackstone_pressure_plate" ), BlockPressurePlate.class );
        register( BlockType.POLISHED_BLACKSTONE_SLAB, Identifier.fromString( "minecraft:polished_blackstone_slab" ), BlockPolishedBlackstoneSlab.class );
        register( BlockType.POLISHED_BLACKSTONE_STAIRS, Identifier.fromString( "minecraft:polished_blackstone_stairs" ), BlockStairs.class );
        register( BlockType.POLISHED_BLACKSTONE_WALL, Identifier.fromString( "minecraft:polished_blackstone_wall" ), BlockWall.class );
        register( BlockType.POLISHED_DEEPSLATE, Identifier.fromString( "minecraft:polished_deepslate" ) );
        register( BlockType.POLISHED_DEEPSLATE_DOUBLE_SLAB, Identifier.fromString( "minecraft:polished_deepslate_double_slab" ), BlockDoublePolishedDeepslateSlab.class );
        register( BlockType.POLISHED_DEEPSLATE_SLAB, Identifier.fromString( "minecraft:polished_deepslate_slab" ), BlockPolishedDeepslateSlab.class );
        register( BlockType.POLISHED_DEEPSLATE_STAIRS, Identifier.fromString( "minecraft:polished_deepslate_stairs" ), BlockStairs.class );
        register( BlockType.POLISHED_DEEPSLATE_WALL, Identifier.fromString( "minecraft:polished_deepslate_wall" ), BlockWall.class );
        register( BlockType.POLISHED_DIORITE_STAIRS, Identifier.fromString( "minecraft:polished_diorite_stairs" ), BlockStairs.class );
        register( BlockType.POLISHED_GRANITE_STAIRS, Identifier.fromString( "minecraft:polished_granite_stairs" ), BlockStairs.class );
        register( BlockType.PORTAL, Identifier.fromString( "minecraft:portal" ) );
        register( BlockType.POTATOES, Identifier.fromString( "minecraft:potatoes" ) );
        register( BlockType.POWDER_SNOW, Identifier.fromString( "minecraft:powder_snow" ) );
        register( BlockType.POWERED_COMPARATOR, Identifier.fromString( "minecraft:powered_comparator" ) );
        register( BlockType.POWERED_REPEATER, Identifier.fromString( "minecraft:powered_repeater" ) );
        register( BlockType.PRISMARINE, Identifier.fromString( "minecraft:prismarine" ), BlockPrismarine.class );
        register( BlockType.PRISMARINE_BRICKS_STAIRS, Identifier.fromString( "minecraft:prismarine_bricks_stairs" ), BlockStairs.class );
        register( BlockType.PRISMARINE_STAIRS, Identifier.fromString( "minecraft:prismarine_stairs" ), BlockStairs.class );
        register( BlockType.PUMPKIN, Identifier.fromString( "minecraft:pumpkin" ) );
        register( BlockType.PUMPKIN_STEM, Identifier.fromString( "minecraft:pumpkin_stem" ) );
        register( BlockType.PURPLE_CANDLE, Identifier.fromString( "minecraft:purple_candle" ), BlockCandle.class );
        register( BlockType.PURPLE_CANDLE_CAKE, Identifier.fromString( "minecraft:purple_candle_cake" ) );
        register( BlockType.PURPLE_GLAZED_TERRACOTTA, Identifier.fromString( "minecraft:purple_glazed_terracotta" ) );
        register( BlockType.PURPUR_BLOCK, Identifier.fromString( "minecraft:purpur_block" ), BlockPurpurBlock.class );
        register( BlockType.PURPUR_STAIRS, Identifier.fromString( "minecraft:purpur_stairs" ), BlockStairs.class );
        register( BlockType.QUARTZ_BLOCK, Identifier.fromString( "minecraft:quartz_block" ), BlockQuartzBlock.class );
        register( BlockType.QUARTZ_BRICKS, Identifier.fromString( "minecraft:quartz_bricks" ) );
        register( BlockType.QUARTZ_ORE, Identifier.fromString( "minecraft:quartz_ore" ), BlockQuartzOre.class );
        register( BlockType.QUARTZ_STAIRS, Identifier.fromString( "minecraft:quartz_stairs" ), BlockStairs.class );
        register( BlockType.RAIL, Identifier.fromString( "minecraft:rail" ), BlockRail.class );
        register( BlockType.RAW_COPPER_BLOCK, Identifier.fromString( "minecraft:raw_copper_block" ) );
        register( BlockType.RAW_GOLD_BLOCK, Identifier.fromString( "minecraft:raw_gold_block" ) );
        register( BlockType.RAW_IRON_BLOCK, Identifier.fromString( "minecraft:raw_iron_block" ) );
        register( BlockType.REDSTONE_BLOCK, Identifier.fromString( "minecraft:redstone_block" ) );
        register( BlockType.REDSTONE_LAMP, Identifier.fromString( "minecraft:redstone_lamp" ) );
        register( BlockType.REDSTONE_ORE, Identifier.fromString( "minecraft:redstone_ore" ), BlockRedstoneOre.class );
        register( BlockType.REDSTONE_TORCH, Identifier.fromString( "minecraft:redstone_torch" ), BlockTorch.class );
        register( BlockType.REDSTONE_WIRE, Identifier.fromString( "minecraft:redstone_wire" ) );
        register( BlockType.RED_CANDLE, Identifier.fromString( "minecraft:red_candle" ), BlockCandle.class );
        register( BlockType.RED_CANDLE_CAKE, Identifier.fromString( "minecraft:red_candle_cake" ) );
        register( BlockType.RED_FLOWER, Identifier.fromString( "minecraft:red_flower" ), BlockRedFlower.class );
        register( BlockType.RED_GLAZED_TERRACOTTA, Identifier.fromString( "minecraft:red_glazed_terracotta" ) );
        register( BlockType.RED_MUSHROOM, Identifier.fromString( "minecraft:red_mushroom" ) );
        register( BlockType.RED_MUSHROOM_BLOCK, Identifier.fromString( "minecraft:red_mushroom_block" ) );
        register( BlockType.RED_NETHER_BRICK, Identifier.fromString( "minecraft:red_nether_brick" ) );
        register( BlockType.RED_NETHER_BRICK_STAIRS, Identifier.fromString( "minecraft:red_nether_brick_stairs" ), BlockStairs.class );
        register( BlockType.RED_SANDSTONE, Identifier.fromString( "minecraft:red_sandstone" ), BlockRedSandstone.class );
        register( BlockType.RED_SANDSTONE_STAIRS, Identifier.fromString( "minecraft:red_sandstone_stairs" ), BlockStairs.class );
        register( BlockType.SUGAR_CANE, Identifier.fromString( "minecraft:reeds" ), BlockSugarCane.class );
        register( BlockType.REINFORCED_DEEPSLATE, Identifier.fromString( "minecraft:reinforced_deepslate" ) );
        register( BlockType.REPEATING_COMMAND_BLOCK, Identifier.fromString( "minecraft:repeating_command_block" ) );
        register( BlockType.RESERVED6, Identifier.fromString( "minecraft:reserved6" ) );
        register( BlockType.RESPAWN_ANCHOR, Identifier.fromString( "minecraft:respawn_anchor" ) );
        register( BlockType.SAND, Identifier.fromString( "minecraft:sand" ), BlockSand.class );
        register( BlockType.SANDSTONE, Identifier.fromString( "minecraft:sandstone" ), BlockSandstone.class );
        register( BlockType.SANDSTONE_STAIRS, Identifier.fromString( "minecraft:sandstone_stairs" ), BlockStairs.class );
        register( BlockType.SAPLING, Identifier.fromString( "minecraft:sapling" ), BlockSapling.class );
        register( BlockType.SCAFFOLDING, Identifier.fromString( "minecraft:scaffolding" ) );
        register( BlockType.SCULK, Identifier.fromString( "minecraft:sculk" ) );
        register( BlockType.SCULK_CATALYST, Identifier.fromString( "minecraft:sculk_catalyst" ) );
        register( BlockType.SCULK_SENSOR, Identifier.fromString( "minecraft:sculk_sensor" ) );
        register( BlockType.SCULK_SHRIEKER, Identifier.fromString( "minecraft:sculk_shrieker" ) );
        register( BlockType.SCULK_VEIN, Identifier.fromString( "minecraft:sculk_vein" ) );
        register( BlockType.SEAGRASS, Identifier.fromString( "minecraft:seagrass" ), BlockSeagrass.class );
        register( BlockType.SEA_LANTERN, Identifier.fromString( "minecraft:sea_lantern" ));
        register( BlockType.SEA_PICKLE, Identifier.fromString( "minecraft:sea_pickle" ), BlockSeaPickle.class );
        register( BlockType.SHROOMLIGHT, Identifier.fromString( "minecraft:shroomlight" ) );
        register( BlockType.SHULKER_BOX, Identifier.fromString( "minecraft:shulker_box" ), BlockShulkerBox.class );
        register( BlockType.SILVER_GLAZED_TERRACOTTA, Identifier.fromString( "minecraft:silver_glazed_terracotta" ) );
        register( BlockType.SKULL, Identifier.fromString( "minecraft:skull" ), BlockSkull.class );
        register( BlockType.SLIME, Identifier.fromString( "minecraft:slime" ) );
        register( BlockType.SMALL_AMETHYST_BUD, Identifier.fromString( "minecraft:small_amethyst_bud" ) );
        register( BlockType.SMALL_DRIPLEAF_BLOCK, Identifier.fromString( "minecraft:small_dripleaf_block" ) );
        register( BlockType.SMITHING_TABLE, Identifier.fromString( "minecraft:smithing_table" ), BlockSmithingTable.class );
        register( BlockType.SMOKER, Identifier.fromString( "minecraft:smoker" ), BlockSmoker.class );
        register( BlockType.SMOOTH_BASALT, Identifier.fromString( "minecraft:smooth_basalt" ) );
        register( BlockType.SMOOTH_QUARTZ_STAIRS, Identifier.fromString( "minecraft:smooth_quartz_stairs" ), BlockStairs.class );
        register( BlockType.SMOOTH_RED_SANDSTONE_STAIRS, Identifier.fromString( "minecraft:smooth_red_sandstone_stairs" ), BlockStairs.class );
        register( BlockType.SMOOTH_SANDSTONE_STAIRS, Identifier.fromString( "minecraft:smooth_sandstone_stairs" ), BlockStairs.class );
        register( BlockType.SMOOTH_STONE, Identifier.fromString( "minecraft:smooth_stone" ) );
        register( BlockType.SNOW, Identifier.fromString( "minecraft:snow" ) );
        register( BlockType.SNOW_LAYER, Identifier.fromString( "minecraft:snow_layer" ), BlockSnowLayer.class );
        register( BlockType.SOUL_CAMPFIRE, Identifier.fromString( "minecraft:soul_campfire" ), BlockCampfire.class );
        register( BlockType.SOUL_FIRE, Identifier.fromString( "minecraft:soul_fire" ) );
        register( BlockType.SOUL_LANTERN, Identifier.fromString( "minecraft:soul_lantern" ), BlockLantern.class );
        register( BlockType.SOUL_SAND, Identifier.fromString( "minecraft:soul_sand" ) );
        register( BlockType.SOUL_SOIL, Identifier.fromString( "minecraft:soul_soil" ) );
        register( BlockType.SOUL_TORCH, Identifier.fromString( "minecraft:soul_torch" ), BlockTorch.class );
        register( BlockType.SPONGE, Identifier.fromString( "minecraft:sponge" ), BlockSponge.class );
        register( BlockType.SPORE_BLOSSOM, Identifier.fromString( "minecraft:spore_blossom" ) );
        register( BlockType.SPRUCE_BUTTON, Identifier.fromString( "minecraft:spruce_button" ), BlockButton.class );
        register( BlockType.SPRUCE_DOOR, Identifier.fromString( "minecraft:spruce_door" ), BlockDoor.class );
        register( BlockType.SPRUCE_FENCE_GATE, Identifier.fromString( "minecraft:spruce_fence_gate" ), BlockFenceGate.class );
        register( BlockType.SPRUCE_PRESSURE_PLATE, Identifier.fromString( "minecraft:spruce_pressure_plate" ), BlockPressurePlate.class );
        register( BlockType.SPRUCE_STAIRS, Identifier.fromString( "minecraft:spruce_stairs" ), BlockStairs.class );
        register( BlockType.SPRUCE_STANDING_SIGN, Identifier.fromString( "minecraft:spruce_standing_sign" ), BlockSpruceStandingSign.class );
        register( BlockType.SPRUCE_TRAPDOOR, Identifier.fromString( "minecraft:spruce_trapdoor" ), BlockTrapdoor.class );
        register( BlockType.SPRUCE_WALL_SIGN, Identifier.fromString( "minecraft:spruce_wall_sign" ), BlockSpruceWallSign.class );
        register( BlockType.STAINED_GLASS, Identifier.fromString( "minecraft:stained_glass" ), BlockStainedGlass.class );
        register( BlockType.STAINED_GLASS_PANE, Identifier.fromString( "minecraft:stained_glass_pane" ), BlockStainedGlassPane.class );
        register( BlockType.STAINED_HARDENED_CLAY, Identifier.fromString( "minecraft:stained_hardened_clay" ), BlockStainedHardenedClay.class );
        register( BlockType.STANDING_BANNER, Identifier.fromString( "minecraft:standing_banner" ), BlockStandingBanner.class );
        register( BlockType.OAK_STANDING_SIGN, Identifier.fromString( "minecraft:standing_sign" ), BlockOakStandingSign.class );
        register( BlockType.STICKY_PISTON, Identifier.fromString( "minecraft:sticky_piston" ), BlockStickyPiston.class );
        register( BlockType.STICKY_PISTON_ARM_COLLISION, Identifier.fromString( "minecraft:sticky_piston_arm_collision" ) );
        register( BlockType.STONE, Identifier.fromString( "minecraft:stone" ), BlockStone.class );
        register( BlockType.STONEBRICK, Identifier.fromString( "minecraft:stonebrick" ), BlockStonebrick.class );
        register( BlockType.STONECUTTER, Identifier.fromString( "minecraft:stonecutter" ) );
        register( BlockType.STONECUTTER_BLOCK, Identifier.fromString( "minecraft:stonecutter_block" ), BlockStonecutterBlock.class );
        register( BlockType.STONE_BLOCK_SLAB, Identifier.fromString( "minecraft:stone_block_slab" ), BlockStoneSlab.class );
        register( BlockType.STONE_BLOCK_SLAB2, Identifier.fromString( "minecraft:stone_block_slab2" ), BlockStoneSlab2.class );
        register( BlockType.STONE_BLOCK_SLAB3, Identifier.fromString( "minecraft:stone_block_slab3" ), BlockStoneSlab3.class );
        register( BlockType.STONE_BLOCK_SLAB4, Identifier.fromString( "minecraft:stone_block_slab4" ), BlockStoneSlab4.class );
        register( BlockType.STONE_BRICK_STAIRS, Identifier.fromString( "minecraft:stone_brick_stairs" ), BlockStairs.class );
        register( BlockType.STONE_BUTTON, Identifier.fromString( "minecraft:stone_button" ), BlockButton.class );
        register( BlockType.STONE_PRESSURE_PLATE, Identifier.fromString( "minecraft:stone_pressure_plate" ), BlockPressurePlate.class );
        register( BlockType.STONE_STAIRS, Identifier.fromString( "minecraft:stone_stairs" ), BlockStairs.class );
        register( BlockType.STRIPPED_ACACIA_LOG, Identifier.fromString( "minecraft:stripped_acacia_log" ), BlockStippedLog.class );
        register( BlockType.STRIPPED_BIRCH_LOG, Identifier.fromString( "minecraft:stripped_birch_log" ), BlockStippedLog.class );
        register( BlockType.STRIPPED_CRIMSON_HYPHAE, Identifier.fromString( "minecraft:stripped_crimson_hyphae" ), BlockStrippedCrimsonHyphae.class );
        register( BlockType.STRIPPED_CRIMSON_STEM, Identifier.fromString( "minecraft:stripped_crimson_stem" ), BlockStippedLog.class );
        register( BlockType.STRIPPED_DARK_OAK_LOG, Identifier.fromString( "minecraft:stripped_dark_oak_log" ), BlockStippedLog.class );
        register( BlockType.STRIPPED_JUNGLE_LOG, Identifier.fromString( "minecraft:stripped_jungle_log" ), BlockStippedLog.class );
        register( BlockType.STRIPPED_MANGROVE_LOG, Identifier.fromString( "minecraft:stripped_mangrove_log" ), BlockStippedLog.class );
        register( BlockType.STRIPPED_MANGROVE_WOOD, Identifier.fromString( "minecraft:stripped_mangrove_wood" ), BlockStrippedMangroveWood.class );
        register( BlockType.STRIPPED_OAK_LOG, Identifier.fromString( "minecraft:stripped_oak_log" ), BlockStippedLog.class );
        register( BlockType.STRIPPED_SPRUCE_LOG, Identifier.fromString( "minecraft:stripped_spruce_log" ), BlockStippedLog.class );
        register( BlockType.STRIPPED_WARPED_HYPHAE, Identifier.fromString( "minecraft:stripped_warped_hyphae" ), BlockStrippedWarpedHyphae.class );
        register( BlockType.STRIPPED_WARPED_STEM, Identifier.fromString( "minecraft:stripped_warped_stem" ), BlockStippedLog.class );
        register( BlockType.STRUCTURE_BLOCK, Identifier.fromString( "minecraft:structure_block" ) );
        register( BlockType.STRUCTURE_VOID, Identifier.fromString( "minecraft:structure_void" ) );
        register( BlockType.SWEET_BERRY_BUSH, Identifier.fromString( "minecraft:sweet_berry_bush" ) );
        register( BlockType.TALLGRASS, Identifier.fromString( "minecraft:tallgrass" ), BlockTallGrass.class );
        register( BlockType.TARGET, Identifier.fromString( "minecraft:target" ) );
        register( BlockType.TINTED_GLASS, Identifier.fromString( "minecraft:tinted_glass" ) );
        register( BlockType.TNT, Identifier.fromString( "minecraft:tnt" ) );
        register( BlockType.TORCH, Identifier.fromString( "minecraft:torch" ), BlockTorch.class );
        register( BlockType.TRAPDOOR, Identifier.fromString( "minecraft:trapdoor" ), BlockTrapdoor.class );
        register( BlockType.TRAPPED_CHEST, Identifier.fromString( "minecraft:trapped_chest" ), BlockTrappedChest.class );
        register( BlockType.TRIPWIRE_HOOK, Identifier.fromString( "minecraft:tripwire_hook" ), BlockTripwireHook.class );
        register( BlockType.TRIP_WIRE, Identifier.fromString( "minecraft:trip_wire" ) );
        register( BlockType.TUFF, Identifier.fromString( "minecraft:tuff" ) );
        register( BlockType.TURTLE_EGG, Identifier.fromString( "minecraft:turtle_egg" ) );
        register( BlockType.TWISTING_VINES, Identifier.fromString( "minecraft:twisting_vines" ) );
        register( BlockType.UNDERWATER_TORCH, Identifier.fromString( "minecraft:underwater_torch" ), BlockTorch.class );
        register( BlockType.UNDYED_SHULKER_BOX, Identifier.fromString( "minecraft:undyed_shulker_box" ), BlockUndyedShulkerBox.class );
        register( BlockType.UNKNOWN, Identifier.fromString( "minecraft:unknown" ) );
        register( BlockType.UNLIT_REDSTONE_TORCH, Identifier.fromString( "minecraft:unlit_redstone_torch" ), BlockTorch.class );
        register( BlockType.UNPOWERED_COMPARATOR, Identifier.fromString( "minecraft:unpowered_comparator" ), BlockCompartor.class );
        register( BlockType.UNPOWERED_REPEATER, Identifier.fromString( "minecraft:unpowered_repeater" ), BlockRepeater.class );
        register( BlockType.VERDANT_FROGLIGHT, Identifier.fromString( "minecraft:verdant_froglight" ) );
        register( BlockType.VINE, Identifier.fromString( "minecraft:vine" ), BlockVine.class );
        register( BlockType.WALL_BANNER, Identifier.fromString( "minecraft:wall_banner" ), BlockWallBanner.class );
        register( BlockType.OAK_WALL_SIGN, Identifier.fromString( "minecraft:wall_sign" ), BlockOakWallSign.class );
        register( BlockType.WARPED_BUTTON, Identifier.fromString( "minecraft:warped_button" ), BlockButton.class );
        register( BlockType.WARPED_DOOR, Identifier.fromString( "minecraft:warped_door" ), BlockDoor.class );
        register( BlockType.WARPED_DOUBLE_SLAB, Identifier.fromString( "minecraft:warped_double_slab" ), BlockDoubleWarpedSlab.class );
        register( BlockType.WARPED_FENCE, Identifier.fromString( "minecraft:warped_fence" ), BlockFence.class );
        register( BlockType.WARPED_FENCE_GATE, Identifier.fromString( "minecraft:warped_fence_gate" ), BlockFenceGate.class );
        register( BlockType.WARPED_FUNGUS, Identifier.fromString( "minecraft:warped_fungus" ) );
        register( BlockType.WARPED_HYPHAE, Identifier.fromString( "minecraft:warped_hyphae" ), BlockWarpedHyphae.class );
        register( BlockType.WARPED_NYLIUM, Identifier.fromString( "minecraft:warped_nylium" ) );
        register( BlockType.WARPED_PLANKS, Identifier.fromString( "minecraft:warped_planks" ) );
        register( BlockType.WARPED_PRESSURE_PLATE, Identifier.fromString( "minecraft:warped_pressure_plate" ), BlockPressurePlate.class );
        register( BlockType.WARPED_ROOTS, Identifier.fromString( "minecraft:warped_roots" ) );
        register( BlockType.WARPED_SLAB, Identifier.fromString( "minecraft:warped_slab" ), BlockWarpedSlab.class );
        register( BlockType.WARPED_STAIRS, Identifier.fromString( "minecraft:warped_stairs" ), BlockStairs.class );
        register( BlockType.WARPED_STANDING_SIGN, Identifier.fromString( "minecraft:warped_standing_sign" ), BlockWarpedStandingSign.class );
        register( BlockType.WARPED_STEM, Identifier.fromString( "minecraft:warped_stem" ), BlockWarpedStem.class );
        register( BlockType.WARPED_TRAPDOOR, Identifier.fromString( "minecraft:warped_trapdoor" ), BlockTrapdoor.class );
        register( BlockType.WARPED_WALL_SIGN, Identifier.fromString( "minecraft:warped_wall_sign" ), BlockWarpedWallSign.class );
        register( BlockType.WARPED_WART_BLOCK, Identifier.fromString( "minecraft:warped_wart_block" ) );
        register( BlockType.WATER, Identifier.fromString( "minecraft:water" ), BlockWater.class );
        register( BlockType.WATERLILY, Identifier.fromString( "minecraft:waterlily" ), BlockWaterlily.class );
        register( BlockType.WAXED_COPPER, Identifier.fromString( "minecraft:waxed_copper" ) );
        register( BlockType.WAXED_CUT_COPPER, Identifier.fromString( "minecraft:waxed_cut_copper" ) );
        register( BlockType.WAXED_CUT_COPPER_SLAB, Identifier.fromString( "minecraft:waxed_cut_copper_slab" ), BlockWaxedCutCopperSlab.class );
        register( BlockType.WAXED_CUT_COPPER_STAIRS, Identifier.fromString( "minecraft:waxed_cut_copper_stairs" ), BlockStairs.class );
        register( BlockType.WAXED_DOUBLE_CUT_COPPER_SLAB, Identifier.fromString( "minecraft:waxed_double_cut_copper_slab" ), BlockDoubleWaxedCutCopperSlab.class );
        register( BlockType.WAXED_EXPOSED_COPPER, Identifier.fromString( "minecraft:waxed_exposed_copper" ) );
        register( BlockType.WAXED_EXPOSED_CUT_COPPER, Identifier.fromString( "minecraft:waxed_exposed_cut_copper" ) );
        register( BlockType.WAXED_EXPOSED_CUT_COPPER_SLAB, Identifier.fromString( "minecraft:waxed_exposed_cut_copper_slab" ), BlockWaxedExposedCutCopperSlab.class );
        register( BlockType.WAXED_EXPOSED_CUT_COPPER_STAIRS, Identifier.fromString( "minecraft:waxed_exposed_cut_copper_stairs" ), BlockStairs.class );
        register( BlockType.WAXED_EXPOSED_DOUBLE_CUT_COPPER_SLAB, Identifier.fromString( "minecraft:waxed_exposed_double_cut_copper_slab" ), BlockDoubleWaxedExposedCutCopperSlab.class );
        register( BlockType.WAXED_OXIDIZED_COPPER, Identifier.fromString( "minecraft:waxed_oxidized_copper" ) );
        register( BlockType.WAXED_OXIDIZED_CUT_COPPER, Identifier.fromString( "minecraft:waxed_oxidized_cut_copper" ) );
        register( BlockType.WAXED_OXIDIZED_CUT_COPPER_SLAB, Identifier.fromString( "minecraft:waxed_oxidized_cut_copper_slab" ), BlockWaxedOxidizedCutCopperSlab.class );
        register( BlockType.WAXED_OXIDIZED_CUT_COPPER_STAIRS, Identifier.fromString( "minecraft:waxed_oxidized_cut_copper_stairs" ), BlockStairs.class );
        register( BlockType.WAXED_OXIDIZED_DOUBLE_CUT_COPPER_SLAB, Identifier.fromString( "minecraft:waxed_oxidized_double_cut_copper_slab" ), BlockDoubleWaxedOxidizedCutCopperSlab.class );
        register( BlockType.WAXED_WEATHERED_COPPER, Identifier.fromString( "minecraft:waxed_weathered_copper" ) );
        register( BlockType.WAXED_WEATHERED_CUT_COPPER, Identifier.fromString( "minecraft:waxed_weathered_cut_copper" ) );
        register( BlockType.WAXED_WEATHERED_CUT_COPPER_SLAB, Identifier.fromString( "minecraft:waxed_weathered_cut_copper_slab" ), BlockWaxedWeatheredCutCopperSlab.class );
        register( BlockType.WAXED_WEATHERED_CUT_COPPER_STAIRS, Identifier.fromString( "minecraft:waxed_weathered_cut_copper_stairs" ), BlockStairs.class );
        register( BlockType.WAXED_WEATHERED_DOUBLE_CUT_COPPER_SLAB, Identifier.fromString( "minecraft:waxed_weathered_double_cut_copper_slab" ), BlockDoubleWaxedWeatheredCutCopperSlab.class );
        register( BlockType.WEATHERED_COPPER, Identifier.fromString( "minecraft:weathered_copper" ) );
        register( BlockType.WEATHERED_CUT_COPPER, Identifier.fromString( "minecraft:weathered_cut_copper" ) );
        register( BlockType.WEATHERED_CUT_COPPER_SLAB, Identifier.fromString( "minecraft:weathered_cut_copper_slab" ), BlockWeatheredCutCopperSlab.class );
        register( BlockType.WEATHERED_CUT_COPPER_STAIRS, Identifier.fromString( "minecraft:weathered_cut_copper_stairs" ), BlockStairs.class );
        register( BlockType.WEATHERED_DOUBLE_CUT_COPPER_SLAB, Identifier.fromString( "minecraft:weathered_double_cut_copper_slab" ), BlockDoubleWeatheredCutCopperSlab.class );
        register( BlockType.WEB, Identifier.fromString( "minecraft:web" ) );
        register( BlockType.WEEPING_VINES, Identifier.fromString( "minecraft:weeping_vines" ) );
        register( BlockType.WHEAT, Identifier.fromString( "minecraft:wheat" ) );
        register( BlockType.WHITE_CANDLE, Identifier.fromString( "minecraft:white_candle" ), BlockCandle.class );
        register( BlockType.WHITE_CANDLE_CAKE, Identifier.fromString( "minecraft:white_candle_cake" ) );
        register( BlockType.WHITE_GLAZED_TERRACOTTA, Identifier.fromString( "minecraft:white_glazed_terracotta" ) );
        register( BlockType.WITHER_ROSE, Identifier.fromString( "minecraft:wither_rose" ) );
        register( BlockType.WOOD, Identifier.fromString( "minecraft:wood" ), BlockWood.class );
        register( BlockType.OAK_BUTTON, Identifier.fromString( "minecraft:wooden_button" ), BlockButton.class );
        register( BlockType.WOODEN_DOOR, Identifier.fromString( "minecraft:wooden_door" ), BlockDoor.class );
        register( BlockType.WOODEN_PRESSURE_PLATE, Identifier.fromString( "minecraft:wooden_pressure_plate" ), BlockPressurePlate.class );
        register( BlockType.WOODEN_SLAB, Identifier.fromString( "minecraft:wooden_slab" ), BlockWoodenSlab.class );
        register( BlockType.WHITE_WOOL, Identifier.fromString( "minecraft:white_wool" ), BlockWhiteWool.class );
        register( BlockType.ORANGE_WOOL, Identifier.fromString( "minecraft:orange_wool" ), BlockOrangeWool.class );
        register( BlockType.MAGENTA_WOOL, Identifier.fromString( "minecraft:magenta_wool" ), BlockMagentaWool.class );
        register( BlockType.LIGHT_BLUE_WOOL, Identifier.fromString( "minecraft:light_blue_wool" ), BlockLightBlueWool.class );
        register( BlockType.YELLOW_WOOL, Identifier.fromString( "minecraft:yellow_wool" ), BlockYellowWool.class );
        register( BlockType.LIME_WOOL, Identifier.fromString( "minecraft:lime_wool" ), BlockLimeWool.class );
        register( BlockType.PINK_WOOL, Identifier.fromString( "minecraft:pink_wool" ), BlockPinkWool.class );
        register( BlockType.GRAY_WOOL, Identifier.fromString( "minecraft:gray_wool" ), BlockGrayWool.class );
        register( BlockType.SILVER_WOOL, Identifier.fromString( "minecraft:silver_wool" ), BlockSilverWool.class );
        register( BlockType.CYAN_WOOL, Identifier.fromString( "minecraft:cyan_wool" ), BlockCyanWool.class );
        register( BlockType.PURPLE_WOOL, Identifier.fromString( "minecraft:purple_wool" ), BlockPurpleWool.class );
        register( BlockType.BLUE_WOOL, Identifier.fromString( "minecraft:blue_wool" ), BlockBlueWool.class );
        register( BlockType.BROWN_WOOL, Identifier.fromString( "minecraft:brown_wool" ), BlockBrownWool.class );
        register( BlockType.GREEN_WOOL, Identifier.fromString( "minecraft:green_wool" ), BlockGreenWool.class );
        register( BlockType.RED_WOOL, Identifier.fromString( "minecraft:red_wool" ), BlockRedWool.class );
        register( BlockType.BLACK_WOOL, Identifier.fromString( "minecraft:black_wool" ), BlockBlackWool.class );
        register( BlockType.YELLOW_CANDLE, Identifier.fromString( "minecraft:yellow_candle" ), BlockCandle.class );
        register( BlockType.YELLOW_CANDLE_CAKE, Identifier.fromString( "minecraft:yellow_candle_cake" ) );
        register( BlockType.YELLOW_FLOWER, Identifier.fromString( "minecraft:yellow_flower" ) );
        register( BlockType.YELLOW_GLAZED_TERRACOTTA, Identifier.fromString( "minecraft:yellow_glazed_terracotta" ) );
    }

    public static void initBlockProperties() {
        Gson GSON = new Gson();
        try ( InputStream inputStream = Objects.requireNonNull( Bootstrap.class.getClassLoader().getResourceAsStream( "block_properties.json" ) ) ) {
            InputStreamReader inputStreamReader = new InputStreamReader( inputStream );
            Map<String, Map<String, Object>> itemEntries = GSON.<Map<String, Map<String, Object>>>fromJson( inputStreamReader, Map.class );
            itemEntries.forEach( ( identifier, map ) -> {
                BLOCK_PROPERTIES.put( Identifier.fromString( identifier ), new BlockProperties(
                        (double) map.get( "hardness" ),
                        (boolean) map.get( "solid" ),
                        (boolean) map.get( "transparent" ),
                        ToolType.valueOf( (String) map.get( "tool_type" ) ),
                        TierType.valueOf( (String) map.get( "tier_type" ) ),
                        (boolean) map.get( "can_break_with_hand" ),
                        (boolean) map.get( "can_pass_through" )
                ) );
            } );
        } catch ( Exception e ) {
            e.printStackTrace();
        }
    }

    private static void register( BlockType blockType, Identifier identifier ) {
        register( blockType, identifier, null );
    }

    private static void register( BlockType blockType, Identifier identifier, Class<? extends Block> blockClass ) {
        IDENTIFIER_FROM_BLOCKTYPE.put( blockType, identifier );
        BLOCKTYPE_FROM_IDENTIFIER.put( identifier, blockType );
        if ( blockClass != null ) {
            BLOCKCLASS_FROM_BLOCKTYPE.put( blockType, blockClass );
        }
    }

    public static Identifier getIdentifier( BlockType blockType ) {
        return IDENTIFIER_FROM_BLOCKTYPE.get( blockType );
    }

    public static BlockType getBlockType( Identifier identifier ) {
        return BLOCKTYPE_FROM_IDENTIFIER.get( identifier );
    }

    public static Class<? extends Block> getBlockClass( BlockType blockType ) {
        return BLOCKCLASS_FROM_BLOCKTYPE.get( blockType );
    }

    public static boolean blockClassExists( BlockType blockType ) {
        return BLOCKCLASS_FROM_BLOCKTYPE.containsKey( blockType );
    }

    public static BlockProperties getBlockProperties( Identifier identifier ) {
        return BLOCK_PROPERTIES.get( identifier );
    }

}
