package org.jukeboxmc.api.effect

enum class EffectType {

    SPEED,
    SLOWNESS,
    HASTE,
    MINING_FATIGUE,
    STRENGTH,
    INSTANT_HEALTH,
    INSTANT_DAMAGE,
    JUMP_BOOST,
    NAUSEA,
    REGENERATION,
    RESISTANCE,
    FIRE_RESISTANCE,
    WATER_BREATHING,
    INVISIBILITY,
    BLINDNESS,
    NIGHT_VISION,
    HUNGER,
    WEAKNESS,
    POISON,
    WITHER,
    HEALTH_BOOST,
    ABSORPTION,
    SATURATION,
    LEVITATION,
    SLOW_FALLING,
    CONDUIT_POWER,
    BAD_OMEN,
    HERO_OF_THE_VILLAGE,
    DARKNESS,
    FATAL_POISON

}