package org.jukeboxmc.world;

/**
 * @author LucGamesYT
 * @version 1.0
 */
public enum Particle {

    ARROW_SPELL_EMITTER( "minecraft:arrow_spell_emitter" ),
    BALLOON_GAS_PARTICLE( "minecraft:balloon_gas_particle" ),
    BASIC_BUBBLE_PARTICLE( "minecraft:basic_bubble_particle" ),
    BASIC_BUBBLE_PARTICLE_MANUAL( "minecraft:basic_bubble_particle_manual" ),
    BASIC_CRIT_PARTICLE( "minecraft:basic_crit_particle" ),
    BASIC_FLAME_PARTICLE( "minecraft:basic_flame_particle" ),
    BASIC_PORTAL_PARTICLE( "minecraft:basic_portal_particle" ),
    BASIC_SMOKE_PARTICLE( "minecraft:basic_smoke_particle" ),
    BLEACH( "minecraft:bleach" ),
    BLOCK_DESTRUCT( "minecraft:block_destruct" ),
    BLOCK_SLIDE( "minecraft:block_slide" ),
    BLUE_FLAME_PARTICLE( "minecraft:blue_flame_particle" ),
    BREAKING_ITEM_ICON( "minecraft:breaking_item_icon" ),
    BREAKING_ITEM_TERRAIN( "minecraft:breaking_item_terrain" ),
    BUBBLE_COLUMN_BUBBLE( "minecraft:bubble_column_bubble" ),
    BUBBLE_COLUMN_DOWN_PARTICLE( "minecraft:bubble_column_down_particle" ),
    BUBBLE_COLUMN_UP_PARTICLE( "minecraft:bubble_column_up_particle" ),
    CAMERA_SHOOT_EXPLOSION( "minecraft:camera_shoot_explosion" ),
    CAMPFIRE_SMOKE_PARTICLE( "minecraft:campfire_smoke_particle" ),
    CAMPFIRE_TALL_SMOKE_PARTICLE( "minecraft:campfire_tall_smoke_particle" ),
    CAULDRON_BUBBLE_PARTICLE( "minecraft:cauldron_bubble_particle" ),
    CAULDRON_EXPLOSION_EMITTER( "minecraft:cauldron_explosion_emitter" ),
    CAULDRON_SPELL_EMITTER( "minecraft:cauldron_spell_emitter" ),
    CAULDRON_SPLASH_PARTICLE( "minecraft:cauldron_splash_particle" ),
    COLORED_FLAME_PARTICLE( "minecraft:colored_flame_particle" ),
    CONDUIT_ABSORB_PARTICLE( "minecraft:conduit_absorb_particle" ),
    CONDUIT_ATTACK_EMITTER( "minecraft:conduit_attack_emitter" ),
    CONDUIT_PARTICLE( "minecraft:conduit_particle" ),
    CRITICAL_HIT_EMITTER( "minecraft:critical_hit_emitter" ),
    CROP_GROWTH_EMITTER( "minecraft:crop_growth_emitter" ),
    DEATH_EXPLOSION_EMITTER( "minecraft:death_explosion_emitter" ),
    DOLPHIN_MOVE_PARTICLE( "minecraft:dolphin_move_particle" ),
    DRAGON_BREATH_FIRE( "minecraft:dragon_breath_fire" ),
    DRAGON_BREATH_LINGERING( "minecraft:dragon_breath_lingering" ),
    DRAGON_BREATH_TRAIL( "minecraft:dragon_breath_trail" ),
    DRAGON_DEATH_EXPLOSION_EMITTER( "minecraft:dragon_death_explosion_emitter" ),
    DRAGON_DESTROY_BLOCK( "minecraft:dragon_destroy_block" ),
    DRAGON_DYING_EXPLOSION( "minecraft:dragon_dying_explosion" ),
    EGG_DESTROY_EMITTER( "minecraft:egg_destroy_emitter" ),
    ELEPHANT_TOOTH_PASTE_VAPOR_PARTICLE( "minecraft:elephant_tooth_paste_vapor_particle" ),
    ENCHANTING_TABLE_PARTICLE( "minecraft:enchanting_table_particle" ),
    END_CHEST( "minecraft:end_chest" ),
    ENDROD( "minecraft:endrod" ),
    EVOCATION_FANG_PARTICLE( "minecraft:evocation_fang_particle" ),
    EVOKER_SPELL( "minecraft:evoker_spell" ),
    EXPLOSION_MANUAL( "minecraft:explosion_manual" ),
    EXPLOSION_PARTICLE( "minecraft:explosion_particle" ),
    EYE_OF_ENDER_BUBBLE_PARTICLE( "minecraft:eye_of_ender_bubble_particle" ),
    EYEOFENDER_DEATH_EXPLODE_PARTICLE( "minecraft:eyeofender_death_explode_particle" ),
    FALLING_BORDER_DUST_PARTICLE( "minecraft:falling_border_dust_particle" ),
    FALLING_DUST( "minecraft:falling_dust" ),
    FALLING_DUST_CONCRETE_POWDER_PARTICLE( "minecraft:falling_dust_concrete_powder_particle" ),
    FALLING_DUST_DRAGON_EGG_PARTICLE( "minecraft:falling_dust_dragon_egg_particle" ),
    FALLING_DUST_GRAVEL_PARTICLE( "minecraft:falling_dust_gravel_particle" ),
    FALLING_DUST_RED_SAND_PARTICLE( "minecraft:falling_dust_red_sand_particle" ),
    FALLING_DUST_SAND_PARTICLE( "minecraft:falling_dust_sand_particle" ),
    FALLING_DUST_SCAFFOLDING_PARTICLE( "minecraft:falling_dust_scaffolding_particle" ),
    FALLING_DUST_TOP_SNOW_PARTICLE( "minecraft:falling_dust_top_snow_particle" ),
    FISH_HOOK_PARTICLE( "minecraft:fish_hook_particle" ),
    FISH_POS_PARTICLE( "minecraft:fish_pos_particle" ),
    GUARDIAN_ATTACK_PARTICLE( "minecraft:guardian_attack_particle" ),
    GUARDIAN_WATER_MOVE_PARTICLE( "minecraft:guardian_water_move_particle" ),
    HEART_PARTICLE( "minecraft:heart_particle" ),
    HONEY_DRIP_PARTICLE( "minecraft:honey_drip_particle" ),
    HUGE_EXPLOSION_EMITTER( "minecraft:huge_explosion_emitter" ),
    HUGE_EXPLOSION_LAB_MISC_EMITTER( "minecraft:huge_explosion_lab_misc_emitter" ),
    ICE_EVAPORATION_EMITTER( "minecraft:ice_evaporation_emitter" ),
    INK_EMITTER( "minecraft:ink_emitter" ),
    KNOCKBACK_ROAR_PARTICLE( "minecraft:knockback_roar_particle" ),
    LAB_TABLE_HEATBLOCK_DUST_PARTICLE( "minecraft:lab_table_heatblock_dust_particle" ),
    LAB_TABLE_MISC_MYSTICAL_PARTICLE( "minecraft:lab_table_misc_mystical_particle" ),
    LARGE_EXPLOSION( "minecraft:large_explosion" ),
    LAVA_DRIP_PARTICLE( "minecraft:lava_drip_particle" ),
    LAVA_PARTICLE( "minecraft:lava_particle" ),
    LLAMA_SPIT_SMOKE( "minecraft:llama_spit_smoke" ),
    MAGNESIUM_SALTS_EMITTER( "minecraft:magnesium_salts_emitter" ),
    MISC_FIRE_VAPOR_PARTICLE( "minecraft:misc_fire_vapor_particle" ),
    MOB_BLOCK_SPAWN_EMITTER( "minecraft:mob_block_spawn_emitter" ),
    MOB_PORTAL( "minecraft:mob_portal" ),
    MOBFLAME_EMITTER( "minecraft:mobflame_emitter" ),
    MOBFLAME_SINGLE( "minecraft:mobflame_single" ),
    MOBSPELL_EMITTER( "minecraft:mobspell_emitter" ),
    MYCELIUM_DUST_PARTICLE( "minecraft:mycelium_dust_particle" ),
    NECTAR_DRIP_PARTICLE( "minecraft:nectar_drip_particle" ),
    NOTE_PARTICLE( "minecraft:note_particle" ),
    OBSIDIAN_GLOW_DUST_PARTICLE( "minecraft:obsidian_glow_dust_particle" ),
    OBSIDIAN_TEAR_PARTICLE( "minecraft:obsidian_tear_particle" ),
    PHANTOM_TRAIL_PARTICLE( "minecraft:phantom_trail_particle" ),
    PORTAL_DIRECTIONAL( "minecraft:portal_directional" ),
    PORTAL_EAST_WEST( "minecraft:portal_east_west" ),
    PORTAL_NORTH_SOUTH( "minecraft:portal_north_south" ),
    PORTAL_REVERSE_PARTICLE( "minecraft:portal_reverse_particle" ),
    RAIN_SPLASH_PARTICLE( "minecraft:rain_splash_particle" ),
    REDSTONE_ORE_DUST_PARTICLE( "minecraft:redstone_ore_dust_particle" ),
    REDSTONE_REPEATER_DUST_PARTICLE( "minecraft:redstone_repeater_dust_particle" ),
    REDSTONE_TORCH_DUST_PARTICLE( "minecraft:redstone_torch_dust_particle" ),
    REDSTONE_WIRE_DUST_PARTICLE( "minecraft:redstone_wire_dust_particle" ),
    RISING_BORDER_DUST_PARTICLE( "minecraft:rising_border_dust_particle" ),
    SHULKER_BULLET( "minecraft:shulker_bullet" ),
    SILVERFISH_GRIEF_EMITTER( "minecraft:silverfish_grief_emitter" ),
    SOUL_PARTICLE( "minecraft:soul_particle" ),
    SPARKLER_EMITTER( "minecraft:sparkler_emitter" ),
    SPLASH_SPELL_EMITTER( "minecraft:splash_spell_emitter" ),
    SPONGE_ABSORB_WATER_PARTICLE( "minecraft:sponge_absorb_water_particle" ),
    SQUID_FLEE_PARTICLE( "minecraft:squid_flee_particle" ),
    SQUID_INK_BUBBLE( "minecraft:squid_ink_bubble" ),
    SQUID_MOVE_PARTICLE( "minecraft:squid_move_particle" ),
    STUNNED_EMITTER( "minecraft:stunned_emitter" ),
    TOTEM_MANUAL( "minecraft:totem_manual" ),
    TOTEM_PARTICLE( "minecraft:totem_particle" ),
    UNDERWATER_TORCH_PARTICLE( "minecraft:underwater_torch_particle" ),
    VILLAGER_ANGRY( "minecraft:villager_angry" ),
    VILLAGER_HAPPY( "minecraft:villager_happy" ),
    WATER_DRIP_PARTICLE( "minecraft:water_drip_particle" ),
    WATER_EVAPORATION_ACTOR_EMITTER( "minecraft:water_evaporation_actor_emitter" ),
    WATER_EVAPORATION_BUCKET_EMITTER( "minecraft:water_evaporation_bucket_emitter" ),
    WATER_EVAPORATION_MANUAL( "minecraft:water_evaporation_manual" ),
    WATER_SPLASH_PARTICLE( "minecraft:water_splash_particle" ),
    WATER_SPLASH_PARTICLE_MANUAL( "minecraft:water_splash_particle_manual" ),
    WATER_WAKE_PARTICLE( "minecraft:water_wake_particle" ),
    WITHER_BOSS_INVULNERABLE( "minecraft:wither_boss_invulnerable" );

    private String identifer;

    Particle( String identifer ) {
        this.identifer = identifer;
    }

    public String getIdentifer() {
        return this.identifer;
    }
}
